(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';(class{constructor(a,b){this.i=b===f?a:""}}).prototype.toString=function(){return this.i.toString()};var f={};const g=Symbol("IS_REPEATED_FIELD");var h=Object,k=h.freeze,l=[];Array.isArray(l)&&!Object.isFrozen(l)&&(l[g]=!0);k.call(h,l);function m(a,b,e){a.addEventListener&&a.addEventListener(b,e,!1)};function n(a,b,e){if(Array.isArray(b))for(var c=0;c<b.length;c++)n(a,String(b[c]),e);else null!=b&&e.push(a+(""===b?"":"="+encodeURIComponent(String(b))))};function p(a,b,e=null){q(a,b,e)}function q(a,b,e){a.google_image_requests||(a.google_image_requests=[]);const c=a.document.createElement("img");if(e){const d=B=>{e&&e(B);c.removeEventListener&&c.removeEventListener("load",d,!1);c.removeEventListener&&c.removeEventListener("error",d,!1)};m(c,"load",d);m(c,"error",d)}c.src=b;a.google_image_requests.push(c)};function r(a=null){return a&&"22"===a.getAttribute("data-jc")?a:document.querySelector('[data-jc="22"]')};var t=document,u=window;function v(a){return"undefined"!==typeof a}function w(a){m(t,a.h,()=>{if(t[a.g])a.i&&(a.i=!1,a.j=Date.now(),x(a,0));else{if(-1!==a.j){const b=Date.now()-a.j;0<b&&(a.j=-1,x(a,1,b))}x(a,3)}})}function y(a){m(u,"click",b=>{a.handleClick(b)})} 
function x(a,b,e=0){var c={gqid:a.m,qqid:a.o};0===b&&(c["return"]=0);1===b&&(c["return"]=1,c.timeDelta=e);2===b&&(c.bgload=1);3===b&&(c.fg=1);b=[];for(var d in c)n(d,c[d],b);p(u,a.l+"&label=window_focus&"+b.join("&"),void 0);if(!(.01<Math.random())){a=r(document.currentScript);a=`https://${"pagead2.googlesyndication.com"}/pagead/gen_204?id=jca&jc=${22}&version=${a&&a.getAttribute("data-jc-version")||"unknown"}&sample=${.01}`;c=window;if(d=c.navigator)d=c.navigator.userAgent,d=/Chrome/.test(d)&&!/Edge/.test(d)? 
!0:!1;d&&c.navigator.sendBeacon?c.navigator.sendBeacon(a):p(c,a)}} 
var A=class{constructor(){var a=z["gws-id"],b=z["qem-id"];this.l=z.url;this.m=a;this.o=b;this.i=!1;a=v(t.hidden)?{g:"hidden",h:"visibilitychange"}:v(t.mozHidden)?{g:"mozHidden",h:"mozvisibilitychange"}:v(t.msHidden)?{g:"msHidden",h:"msvisibilitychange"}:v(t.webkitHidden)?{g:"webkitHidden",h:"webkitvisibilitychange"}:{g:"hidden",h:"visibilitychange"};this.g=a.g;this.h=a.h;this.j=-1;t[this.g]&&x(this,2);w(this);y(this)}handleClick(){this.i=!0;u.setTimeout(()=>{this.i=!1},5E3)}};const C=r(document.currentScript);if(null==C)throw Error("JSC not found 22");var z;const D={},E=C.attributes;for(let a=E.length-1;0<=a;a--){const b=E[a].name;0===b.indexOf("data-jcp-")&&(D[b.substring(9)]=E[a].value)}z=D;window.window_focus_for_click=new A;}).call(this);
