
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"1",
  
  "macros":[{
      "function":"__e"
    },{
      "function":"__cid"
    }],
  "tags":[{
      "function":"__rep",
      "once_per_event":true,
      "vtp_containerId":["macro",1],
      "tag_id":1
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    }],
  "rules":[
    [["if",0],["add",0]]]
},
"runtime":[]




};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ca=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ba(a)}},da="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ea;
if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;fa=ja.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=ea,la=function(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ji=b.prototype},ma=this||self,pa=function(a){return a};var qa={},ra=function(a,b){qa[a]=qa[a]||[];qa[a][b]=!0},sa=function(a){for(var b=[],c=qa[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};var ta=function(){},ua=function(a){return"function"==typeof a},va=function(a){return"string"==typeof a},wa=function(a){return"number"==typeof a&&!isNaN(a)},xa=function(a){var b="[object Array]"==Object.prototype.toString.call(Object(a));Array.isArray?Array.isArray(a)!==b&&ra("TAGGING",4):ra("TAGGING",5);return b},ya=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},za=function(a,b){if(a&&xa(a))for(var c=
0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},Ba=function(a,b){if(!wa(a)||!wa(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Ea=function(a,b){for(var c=new Ca,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},Fa=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},Ga=function(a){return!!a&&("[object Arguments]"==Object.prototype.toString.call(a)||Object.prototype.hasOwnProperty.call(a,"callee"))},Ia=
function(a){return Math.round(Number(a))||0},Ja=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Ka=function(a){var b=[];if(xa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Na=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},Oa=function(){return new Date(Date.now())},Pa=function(){return Oa().getTime()},Ca=function(){this.prefix="gtm.";this.values={}};Ca.prototype.set=function(a,b){this.values[this.prefix+a]=b};
Ca.prototype.get=function(a){return this.values[this.prefix+a]};
var Ua=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Xa=function(a){var b=a;return function(){if(b){var c=b;b=void 0;try{c()}catch(d){}}}},Ya=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Za=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},$a=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},ab=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},bb=/^\w{1,9}$/,
cb=function(a){var b=[];Fa(a,function(c,d){bb.test(c)&&d&&b.push(c)});return b.join(",")};var db,eb=function(){if(void 0===db){var a=null,b=ma.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:pa,createScript:pa,createScriptURL:pa})}catch(c){ma.console&&ma.console.error(c.message)}db=a}else db=a}return db};var hb=function(a,b){this.o=b===fb?a:""};hb.prototype.toString=function(){return this.o+""};var fb={};var ib=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var jb;a:{var kb=ma.navigator;if(kb){var lb=kb.userAgent;if(lb){jb=lb;break a}}jb=""}var mb=function(a){return-1!=jb.indexOf(a)};var ob=function(a,b,c){this.o=c===nb?a:""};ob.prototype.toString=function(){return this.o.toString()};var pb=function(a){return a instanceof ob&&a.constructor===ob?a.o:"type_error:SafeHtml"},nb={},qb=function(a){var b=eb(),c=b?b.createHTML(a):a;return new ob(c,null,nb)},rb=new ob(ma.trustedTypes&&ma.trustedTypes.emptyHTML||"",0,nb);var sb=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d},tb=function(a){var b=a;return function(){if(b){var c=b;b=null;c()}}};var ub=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);var c=a.firstChild.firstChild;a.innerHTML=pb(rb);return!c.parentElement}),vb=function(a,b){if(ub())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=pb(b)};var g=window,m=document,wb=navigator,xb=m.currentScript&&m.currentScript.src,yb=function(a,b){var c=g[a];g[a]=void 0===c?b:c;return g[a]},Db=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},Eb=function(a,b,c){var d=m.createElement("script");d.type="text/javascript";d.async=!0;var e,f=eb(),h=f?f.createScriptURL(a):a;e=new hb(h,fb);d.src=e instanceof hb&&e.constructor===hb?e.o:"type_error:TrustedResourceUrl";
var k,l,n=(d.ownerDocument&&d.ownerDocument.defaultView||window).document,q=null===(l=n.querySelector)||void 0===l?void 0:l.call(n,"script[nonce]");(k=q?q.nonce||q.getAttribute("nonce")||"":"")&&d.setAttribute("nonce",k);Db(d,b);c&&(d.onerror=c);var p=m.getElementsByTagName("script")[0]||m.body||m.head;p.parentNode.insertBefore(d,p);return d},Fb=function(){if(xb){var a=xb.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},Gb=function(a,b){var c=m.createElement("iframe");
c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=m.body&&m.body.lastChild||m.body||m.head;d.parentNode.insertBefore(c,d);Db(c,b);void 0!==a&&(c.src=a);return c},Hb=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},Ib=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},Jb=function(a,b,c){a.removeEventListener?a.removeEventListener(b,
c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},B=function(a){g.setTimeout(a,0)},Kb=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Lb=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Mb=function(a){var b=m.createElement("div"),c=qb("A<div>"+a+"</div>");vb(b,c);b=b.lastChild;for(var d=[];b.firstChild;)d.push(b.removeChild(b.firstChild));return d},Ob=function(a,
b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var f=a,h=0;f&&h<=c;h++){if(d[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},Pb=function(a){wb.sendBeacon&&wb.sendBeacon(a)||Hb(a)},Qb=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Rb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Sb=function(a){if(null==a)return String(a);var b=Rb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Tb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ub=function(a){if(!a||"object"!=Sb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Tb(a,"constructor")&&!Tb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Tb(a,b)},E=function(a,b){var c=b||("array"==Sb(a)?[]:{}),d;for(d in a)if(Tb(a,d)){var e=a[d];"array"==Sb(e)?("array"!=Sb(c[d])&&(c[d]=[]),c[d]=E(e,c[d])):Ub(e)?(Ub(c[d])||(c[d]={}),c[d]=E(e,c[d])):c[d]=e}return c};var Vb=function(a){if(void 0===a||xa(a)||Ub(a))return!0;switch(typeof a){case "boolean":case "number":case "string":case "function":return!0}return!1};var Wb=function(){var a=function(b){return{toString:function(){return b}}};return{gg:a("consent"),hg:a("consent_always_fire"),ye:a("convert_case_to"),ze:a("convert_false_to"),Ae:a("convert_null_to"),Be:a("convert_true_to"),Ce:a("convert_undefined_to"),oi:a("debug_mode_metadata"),ab:a("function"),Tg:a("instance_name"),Vg:a("live_only"),Wg:a("malware_disabled"),Xg:a("metadata"),ui:a("original_activity_id"),vi:a("original_vendor_template_id"),Zg:a("once_per_event"),ef:a("once_per_load"),xi:a("priority_override"),
yi:a("respected_consent_types"),pf:a("setup_tags"),rf:a("tag_id"),sf:a("teardown_tags")}}();var xc;
var yc=[],zc=[],Ac=[],Bc=[],Cc=[],Dc={},Ec,Fc,Gc,Hc=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=Dc[c],e={},f;for(f in a)if(a.hasOwnProperty(f))if(0===f.indexOf("vtp_"))d&&b&&b.zf&&b.zf(a[f]),e[void 0!==d?f:f.substr(4)]=a[f];else if(f===Wb.hg.toString()&&a[f]){}
d&&b&&b.yf&&(e.vtp_gtmCachedValues=b.yf);return void 0!==d?d(e):xc(c,e,b)},Jc=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Ic(a[e],b,c));return d},Ic=function(a,b,c){if(xa(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Ic(a[e],b,c));return d;case "macro":var f=a[1];if(c[f])return;var h=yc[f];if(!h||b.Zd(h))return;c[f]=!0;try{var k=Jc(h,b,c);k.vtp_gtmEventId=b.id;
d=Hc(k,b);Gc&&(d=Gc.oh(d,k))}catch(z){b.Lf&&b.Lf(z,Number(f)),d=!1}c[f]=!1;return d;case "map":d={};for(var l=1;l<a.length;l+=2)d[Ic(a[l],b,c)]=Ic(a[l+1],b,c);return d;case "template":d=[];for(var n=!1,q=1;q<a.length;q++){var p=Ic(a[q],b,c);Fc&&(n=n||p===Fc.Ec);d.push(p)}return Fc&&n?Fc.rh(d):d.join("");case "escape":d=Ic(a[1],b,c);if(Fc&&xa(a[1])&&"macro"===a[1][0]&&Fc.Jh(a))return Fc.Xh(d);d=String(d);for(var r=2;r<a.length;r++)Xb[a[r]]&&(d=Xb[a[r]](d));return d;case "tag":var t=a[1];if(!Bc[t])throw Error("Unable to resolve tag reference "+
t+".");return d={Gf:a[2],index:t};case "zb":var u={arg0:a[2],arg1:a[3],ignore_case:a[5]};u["function"]=a[1];var v=Kc(u,b,c),x=!!a[4];return x||2!==v?x!==(1===v):null;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Kc=function(a,b,c){try{return Ec(Jc(a,b,c))}catch(d){JSON.stringify(a)}return 2};var Nc=function(a){function b(r){for(var t=0;t<r.length;t++)d[r[t]]=!0}for(var c=[],d=[],e=Lc(a),f=0;f<zc.length;f++){var h=zc[f],k=Mc(h,e);if(k){for(var l=h.add||[],n=0;n<l.length;n++)c[l[n]]=!0;b(h.block||[])}else null===k&&b(h.block||[]);}for(var q=[],p=0;p<Bc.length;p++)c[p]&&!d[p]&&(q[p]=!0);return q},Mc=function(a,b){for(var c=a["if"]||[],d=0;d<c.length;d++){var e=b(c[d]);if(0===e)return!1;if(2===e)return null}for(var f=
a.unless||[],h=0;h<f.length;h++){var k=b(f[h]);if(2===k)return null;if(1===k)return!1}return!0},Lc=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=Kc(Ac[c],a));return b[c]}};var Oc={oh:function(a,b){b[Wb.ye]&&"string"===typeof a&&(a=1==b[Wb.ye]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(Wb.Ae)&&null===a&&(a=b[Wb.Ae]);b.hasOwnProperty(Wb.Ce)&&void 0===a&&(a=b[Wb.Ce]);b.hasOwnProperty(Wb.Be)&&!0===a&&(a=b[Wb.Be]);b.hasOwnProperty(Wb.ze)&&!1===a&&(a=b[Wb.ze]);return a}};var G={Mb:"_ee",Jc:"_syn_or_mod",zi:"_uei",Bd:"_eu",wi:"_pci",sd:"event_callback",sc:"event_timeout",sa:"gtag.config",Fa:"gtag.get",ia:"purchase",pb:"refund",Ua:"begin_checkout",nb:"add_to_cart",ob:"remove_from_cart",qg:"view_cart",Ge:"add_to_wishlist",Ea:"view_item",Fe:"view_promotion",Ee:"select_promotion",ed:"select_item",kc:"view_item_list",De:"add_payment_info",pg:"add_shipping_info",Qa:"value_key",Pa:"value_callback",va:"allow_ad_personalization_signals",Jb:"restricted_data_processing",Fb:"allow_google_signals",
ya:"cookie_expires",Gb:"cookie_update",Lb:"session_duration",xc:"session_engaged_time",Ia:"user_properties",ka:"transport_url",O:"ads_data_redaction",ub:"user_data",Hb:"first_party_collection",D:"ad_storage",H:"analytics_storage",we:"region",xe:"wait_for_update",xa:"conversion_linker",wa:"conversion_cookie_prefix",aa:"value",Z:"currency",Ye:"trip_type",V:"items",Re:"passengers",fd:"allow_custom_scripts",tb:"session_id",We:"quantity",$a:"transaction_id",Xa:"language",qc:"country",nc:"allow_enhanced_conversions",
ld:"aw_merchant_id",jd:"aw_feed_country",kd:"aw_feed_language",hd:"discount",Ke:"developer_id",zc:"delivery_postal_code",rd:"estimated_delivery_date",pd:"shipping",zd:"new_customer",md:"customer_lifetime_value",qd:"enhanced_conversions"};
G.Eb="page_view",G.He="user_engagement",G.kg="app_remove",G.lg="app_store_refund",G.mg="app_store_subscription_cancel",G.ng="app_store_subscription_convert",G.og="app_store_subscription_renew",G.rg="first_open",G.sg="first_visit",G.ug="in_app_purchase",G.vg="session_start",G.wg="user_data_login",G.xg="user_data_logout",G.yg="allow_display_features",G.Va="client_id",G.ca="cookie_domain",G.oc="cookie_name",G.Wa="cookie_path",G.Ga="cookie_flags",G.Je="custom_map",G.wd="groups",G.ri="non_interaction",
G.sb="page_location",G.Qe="page_path",G.Ra="page_referrer",G.Ad="page_title",G.Kb="send_page_view",G.Za="send_to",G.wc="session_engaged",G.Pe="_logged_in_state",G.yc="session_number",G.Pg="tracking_id",G.za="linker",G.Ha="url_passthrough",G.Ya="accept_incoming",G.N="domains",G.rb="url_position",G.qb="decorate_forms",G.Ue="phone_conversion_number",G.Se="phone_conversion_callback",G.Te="phone_conversion_css_class",G.Ve="phone_conversion_options",G.Lg="phone_conversion_ids",G.Kg="phone_conversion_country_code",
G.Ie="aw_remarketing",G.gd="aw_remarketing_only",G.mc="gclid",G.Cg="affiliation",G.Oe="tax",G.od="list_name",G.Ne="checkout_step",G.Me="checkout_option",G.Dg="coupon",G.Eg="promotions",G.vb="user_id",G.Mg="retoken",G.ja="cookie_prefix",G.Le="disable_merchant_reported_purchases",G.Bg="dc_natural_search",G.Ag="dc_custom_params",G.Ig="method",G.Og="search_term",G.zg="content_type",G.Jg="optimize_id",G.Fg="experiments",G.Ib="google_signals",G.vd="google_tld",G.Ac="update",G.ud="firebase_id",G.uc="ga_restrict_domain",
G.td="event_settings",G.nd="dynamic_event_settings",G.Ze="user_data_settings",G.Ng="screen_name",G.Hg="_x_19",G.Gg="_x_20",G.yd="internal_traffic_results",G.Xe="traffic_type",G.vc="referral_exclusion_definition",G.xd="ignore_referrer";G.bf=[G.ia,G.pb,G.Ua,G.nb,G.ob,G.qg,G.Ge,G.Ea,G.Fe,G.Ee,G.kc,G.ed,G.De,G.pg];G.af=[G.va,G.Fb,G.Gb];G.cf=[G.ya,G.sc,G.Lb,G.xc];var od=function(a){ra("GTM",a)};var pd=function(a,b){this.o=a;this.defaultValue=void 0===b?!1:b};var qd=new pd(1936,!0),rd=new pd(1933),sd=new pd(373442741);var xd=function(){var a={};this.o=function(b,c){return null!=a[b]?a[b]:c};this.s=function(){a[rd.o]=!0}};xd.o=void 0;xd.s=function(){return xd.o?xd.o:xd.o=new xd};var yd=function(a){return xd.s().o(a.o,a.defaultValue)};var zd=[];function Ad(){var a=yb("google_tag_data",{});a.ics||(a.ics={entries:{},set:Bd,update:Cd,addListener:Dd,notifyListeners:Ed,active:!1,usedDefault:!1});return a.ics}
function Bd(a,b,c,d,e,f){var h=Ad();h.active=!0;h.usedDefault=!0;if(void 0!=b){var k=h.entries,l=k[a]||{},n=l.region,q=c&&va(c)?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(""===d||q===e||(q===d?n!==e:!q&&!n)){var p=!!(f&&0<f&&void 0===l.update),r={region:q,initial:"granted"===b,update:l.update,quiet:p};if(""!==d||!1!==l.initial)k[a]=r;p&&g.setTimeout(function(){k[a]===r&&r.quiet&&(r.quiet=!1,Fd(a),Ed(),ra("TAGGING",2))},f)}}}
function Cd(a,b){var c=Ad();c.active=!0;if(void 0!=b){var d=Gd(a),e=c.entries,f=e[a]=e[a]||{};f.update="granted"===b;var h=Gd(a);f.quiet?(f.quiet=!1,Fd(a)):h!==d&&Fd(a)}}function Dd(a,b){zd.push({Pd:a,zh:b})}function Fd(a){for(var b=0;b<zd.length;++b){var c=zd[b];xa(c.Pd)&&-1!==c.Pd.indexOf(a)&&(c.Of=!0)}}function Ed(a){for(var b=0;b<zd.length;++b){var c=zd[b];if(c.Of){c.Of=!1;try{c.zh({nh:a})}catch(d){}}}}
var Gd=function(a){var b=Ad().entries[a]||{};return void 0!==b.update?b.update:b.initial},Hd=function(a){return(Ad().entries[a]||{}).initial},Id=function(a){return!(Ad().entries[a]||{}).quiet},Jd=function(){return yd(rd)?Ad().active:!1},Kd=function(){return Ad().usedDefault},Ld=function(a,b){Ad().addListener(a,b)},Md=function(a){Ad().notifyListeners(a)},Nd=function(a,b){function c(){for(var e=0;e<b.length;e++)if(!Id(b[e]))return!0;return!1}if(c()){var d=!1;Ld(b,function(e){d||c()||(d=!0,a(e))})}else a({})},
Od=function(a,b){function c(){for(var f=[],h=0;h<d.length;h++){var k=d[h];!1===Gd(k)||e[k]||(f.push(k),e[k]=!0)}return f}var d=va(b)?[b]:b,e={};c().length!==d.length&&Ld(d,function(f){var h=c();0<h.length&&(f.Pd=h,a(f))})};function Pd(a){for(var b=[],c=0;c<Qd.length;c++){var d=a(Qd[c]);b[c]=!0===d?"1":!1===d?"0":"-"}return b.join("")}
var Qd=[G.D,G.H],Rd=function(a){var b=a[G.we];b&&od(40);var c=a[G.xe];c&&od(41);for(var d=xa(b)?b:[b],e={Ab:0};e.Ab<d.length;e={Ab:e.Ab},++e.Ab)Fa(a,function(f){return function(h,k){if(h!==G.we&&h!==G.xe){var l=d[f.Ab];Ad().set(h,k,l,"US","US-CA",c)}}}(e))},Sd=function(a,b){Fa(a,function(c,d){Ad().update(c,d)});Md(b)},I=function(a){var b=Gd(a);return void 0!=b?b:!0},Td=function(){return"G1"+Pd(Gd)},Ud=function(a,b){Od(a,b)},Vd=function(a,b){Nd(a,b)};var Xd=function(a){return Wd?m.querySelectorAll(a):null},Yd=function(a,b){if(!Wd)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!m.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},Zd=!1;if(m.querySelectorAll)try{var $d=m.querySelectorAll(":root");$d&&1==$d.length&&$d[0]==m.documentElement&&(Zd=!0)}catch(a){}var Wd=Zd;var ae=function(a){if(m.hidden)return!0;var b=a.getBoundingClientRect();if(b.top==b.bottom||b.left==b.right||!g.getComputedStyle)return!0;var c=g.getComputedStyle(a,null);if("hidden"===c.visibility)return!0;for(var d=a,e=c;d;){if("none"===e.display)return!0;var f=e.opacity,h=e.filter;if(h){var k=h.indexOf("opacity(");0<=k&&(h=h.substring(k+8,h.indexOf(")",k)),"%"==h.charAt(h.length-1)&&(h=h.substring(0,h.length-1)),f=Math.min(h,f))}if(void 0!==f&&0>=f)return!0;(d=d.parentElement)&&(e=g.getComputedStyle(d,
null))}return!1};var je=/:[0-9]+$/,ke=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(decodeURIComponent(f[0]).replace(/\+/g," ")===b){var h=f.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},ne=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=le(a.protocol)||le(g.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:g.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||g.location.hostname).replace(je,"").toLowerCase());return me(a,b,c,d,e)},me=function(a,b,c,d,e){var f,h=le(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":f=oe(a);break;case "protocol":f=h;break;case "host":f=a.hostname.replace(je,"").toLowerCase();if(c){var k=/^www\d*\./.exec(f);k&&k[0]&&(f=f.substr(k[0].length))}break;case "port":f=String(Number(a.port)||("http"==h?80:"https"==h?443:""));break;case "path":a.pathname||a.hostname||ra("TAGGING",
1);f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=ya(d||[],l[l.length-1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");e&&(f=ke(f,e,void 0));break;case "extension":var n=a.pathname.split(".");f=1<n.length?n[n.length-1]:"";f=f.split("/")[0];break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},le=function(a){return a?a.replace(":","").toLowerCase():""},oe=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");
b=0>c?a.href:a.href.substr(0,c)}return b},pe=function(a){var b=m.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||ra("TAGGING",1),c="/"+c);var d=b.hostname.replace(je,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}},qe=function(a){function b(n){var q=n.split("=")[0];return 0>d.indexOf(q)?n:q+"=0"}function c(n){return n.split("&").map(b).filter(function(q){return void 0!=q}).join("&")}var d="gclid dclid gbraid wbraid gclaw gcldc gclha gclgf gclgb _gl".split(" "),
e=pe(a),f=a.split(/[?#]/)[0],h=e.search,k=e.hash;"?"===h[0]&&(h=h.substring(1));"#"===k[0]&&(k=k.substring(1));h=c(h);k=c(k);""!==h&&(h="?"+h);""!==k&&(k="#"+k);var l=""+f+h+k;"/"===l[l.length-1]&&(l=l.substring(0,l.length-1));return l};var re={};var se=new RegExp(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i),te=new RegExp(/@(gmail|googlemail)\./i),ue=new RegExp(/support|noreply/i),ve="SCRIPT STYLE IMG SVG PATH BR".split(" "),ye=["BR"],ze={};
function Ae(a){var b;if(a===m.body)b="body";else{var c;if(a.id)c="#"+a.id;else{var d;if(a.parentElement){var e;a:{var f=a.parentElement;if(f){for(var h=0;h<f.childElementCount;h++)if(f.children[h]===a){e=h+1;break a}e=-1}else e=1}d=Ae(a.parentElement)+">:nth-child("+e+")"}else d="";c=d}b=c}return b}function Be(a,b){if(1>=a.length)return a;var c=a.filter(b);return 0==c.length?a:c}
function Ce(a){if(0==a.length)return null;var b;b=Be(a,function(c){return!ue.test(c.ra)});b=Be(b,function(c){return"INPUT"===c.element.tagName.toUpperCase()});b=Be(b,function(c){return!ae(c.element)});return b[0]}
var De=function(){var a=ze["true.true"];if(a&&200>Pa()-a.timestamp)return a.result;var b;var c=[],d=m.body;if(d){for(var e=d.querySelectorAll("*"),f=0;f<e.length&&1E4>f;f++){var h=e[f];if(!(0<=ve.indexOf(h.tagName.toUpperCase()))){for(var k=!1,l=0;l<h.childElementCount&&1E4>l;l++)if(!(0<=ye.indexOf(h.children[l].tagName.toUpperCase()))){k=!0;break}k||c.push(h)}}b={elements:c,status:1E4<e.length?"2":"1"}}else b={elements:c,status:"4"};for(var n=b,q=n.elements,p=[],r=0;r<q.length;r++){var t=q[r],u=
t.textContent;t.value&&(u=t.value);if(u){var v=u.match(se);if(v){var x=v[0],z;if(g.location){var w=me(g.location,"host",!0);z=0<=x.toLowerCase().indexOf(w)}else z=!1;z||p.push({element:t,ra:x})}}}var y=Ce(p),A=[];if(y){var C=y.element,F={ra:y.ra,tagName:C.tagName,type:1};F.querySelector=Ae(C);F.isVisible=!ae(C);A.push(F)}var D={elements:A,status:10<p.length?"3":n.status};ze["true.true"]={timestamp:Pa(),result:D};return D},Ee=function(a){return a.tagName+":"+a.isVisible+":"+a.ra.length+":"+te.test(a.ra)};
var Xe={},Ye=null,Ze=Math.random();Xe.M="UA-77509369-1";Xe.Ic="6g0";Xe.si="";Xe.jg="ChAI8M67hgYQ4u6PtpvXz/g5EiYAdqyBOCI0GfaNJP1qKyPIihum6fdI9976nL3i+lRd7bPXGZ4lShoC6tA\x3d";var $e={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},af={__paused:!0,__tg:!0},bf;for(bf in $e)$e.hasOwnProperty(bf)&&(af[bf]=!0);var cf="www.googletagmanager.com/gtm.js";cf="www.googletagmanager.com/gtag/js";
var df=cf,ef=Ja(""),ff=null,gf=null,hf="https://www.googletagmanager.com/a?id="+Xe.M+"&cv=1",jf={},kf={},lf=function(){var a=Ye.sequence||1;Ye.sequence=a+1;return a};Xe.ig="";var mf={},nf=new Ca,of={},pf={},sf={name:"dataLayer",set:function(a,b){E(ab(a,b),of);qf()},get:function(a){return rf(a,2)},reset:function(){nf=new Ca;of={};qf()}},rf=function(a,b){return 2!=b?nf.get(a):tf(a)},tf=function(a){var b,c=a.split(".");b=b||[];for(var d=of,e=0;e<c.length;e++){if(null===d)return!1;if(void 0===d)break;d=d[c[e]];if(-1!==ya(b,d))return}return d},uf=function(a,b){pf.hasOwnProperty(a)||(nf.set(a,b),E(ab(a,b),of),qf())},qf=function(a){Fa(pf,function(b,c){nf.set(b,c);E(ab(b,
void 0),of);E(ab(b,c),of);a&&delete pf[b]})},wf=function(a,b,c){mf[a]=mf[a]||{};mf[a][b]=vf(b,c)},vf=function(a,b){var c,d=1!==(void 0===b?2:b)?tf(a):nf.get(a);"array"===Sb(d)||"object"===Sb(d)?c=E(d):c=d;return c},xf=function(a,b){if(mf[a])return mf[a][b]},yf=function(a,b){mf[a]&&delete mf[a][b]};var Bf={},Cf=function(a,b){if(g._gtmexpgrp&&g._gtmexpgrp.hasOwnProperty(a))return g._gtmexpgrp[a];void 0===Bf[a]&&(Bf[a]=Math.floor(Math.random()*b));return Bf[a]};function Df(a,b,c){for(var d=[],e=b.split(";"),f=0;f<e.length;f++){var h=e[f].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d};function Ef(a){return yd(sd)&&!a.navigator.cookieEnabled?!1:"null"!==a.origin};var Hf=function(a,b,c,d){return Ff(d)?Df(a,String(b||Gf()),c):[]},Kf=function(a,b,c,d,e){if(Ff(e)){var f=If(a,d,e);if(1===f.length)return f[0].id;if(0!==f.length){f=Jf(f,function(h){return h.Pc},b);if(1===f.length)return f[0].id;f=Jf(f,function(h){return h.Zb},c);return f[0]?f[0].id:void 0}}};function Lf(a,b,c,d){var e=Gf(),f=window;Ef(f)&&(f.document.cookie=a);var h=Gf();return e!=h||void 0!=c&&0<=Hf(b,h,!1,d).indexOf(c)}
var Pf=function(a,b,c){function d(t,u,v){if(null==v)return delete h[u],t;h[u]=v;return t+"; "+u+"="+v}function e(t,u){if(null==u)return delete h[u],t;h[u]=!0;return t+"; "+u}if(!Ff(c.Na))return 2;var f;void 0==b?f=a+"=deleted; expires="+(new Date(0)).toUTCString():(c.encode&&(b=encodeURIComponent(b)),b=Mf(b),f=a+"="+b);var h={};f=d(f,"path",c.path);var k;c.expires instanceof Date?k=c.expires.toUTCString():null!=c.expires&&(k=""+c.expires);f=d(f,"expires",k);f=d(f,"max-age",c.Fi);f=d(f,"samesite",
c.Hi);c.Ii&&(f=e(f,"secure"));var l=c.domain;if("auto"===l){for(var n=Nf(),q=0;q<n.length;++q){var p="none"!==n[q]?n[q]:void 0,r=d(f,"domain",p);r=e(r,c.flags);if(!Of(p,c.path)&&Lf(r,a,b,c.Na))return 0}return 1}l&&"none"!==l&&(f=d(f,"domain",l));f=e(f,c.flags);return Of(l,c.path)?1:Lf(f,a,b,c.Na)?0:1},Qf=function(a,b,c){null==c.path&&(c.path="/");c.domain||(c.domain="auto");return Pf(a,b,c)};
function Jf(a,b,c){for(var d=[],e=[],f,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===f||l<f?(e=[k],f=l):l===f&&e.push(k)}return 0<d.length?d:e}function If(a,b,c){for(var d=[],e=Hf(a,void 0,void 0,c),f=0;f<e.length;f++){var h=e[f].split("."),k=h.shift();if(!b||-1!==b.indexOf(k)){var l=h.shift();l&&(l=l.split("-"),d.push({id:h.join("."),Pc:1*l[0]||1,Zb:1*l[1]||1}))}}return d}
var Mf=function(a){a&&1200<a.length&&(a=a.substring(0,1200));return a},Rf=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Sf=/(^|\.)doubleclick\.net$/i,Of=function(a,b){return Sf.test(window.document.location.hostname)||"/"===b&&Rf.test(a)},Gf=function(){return Ef(window)?window.document.cookie:""},Nf=function(){var a=[],b=window.document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));
var e=window.document.location.hostname;Sf.test(e)||Rf.test(e)||a.push("none");return a},Ff=function(a){if(!yd(rd)||!a||!Jd())return!0;if(!Id(a))return!1;var b=Gd(a);return null==b?!0:!!b};var Tf=function(){return[Math.round(2147483647*Math.random()),Math.round(Pa()/1E3)].join(".")},$f=function(a,b,c,d,e){var f=Yf(b);return Kf(a,f,Zf(c),d,e)},ag=function(a,b,c,d){var e=""+Yf(c),f=Zf(d);1<f&&(e+="-"+f);return[b,e,a].join(".")},Yf=function(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},Zf=function(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};function bg(a,b,c){var d,e=Number(null!=a.fb?a.fb:void 0);0!==e&&(d=new Date((b||Pa())+1E3*(e||7776E3)));return{path:a.path,domain:a.domain,flags:a.flags,encode:!!c,expires:d}};var cg=["1"],dg={},hg=function(a){var b=eg(a.prefix);if(!dg[b]&&!fg(b,a.path,a.domain)){var c=Tf();if(0===gg(b,c,a)){var d=yb("google_tag_data",{});d._gcl_au?ra("GTM",57):d._gcl_au=c}fg(b,a.path,a.domain)}};function gg(a,b,c){var d=ag(b,"1",c.domain,c.path),e=bg(c);e.Na="ad_storage";return Qf(a,d,e)}function fg(a,b,c){var d=$f(a,b,c,cg,"ad_storage");d&&(dg[a]=d);return d}function eg(a){return(a||"_gcl")+"_au"};var ig=function(a){for(var b=[],c=m.cookie.split(";"),d=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({pe:f[1],value:f[2],timestamp:Number(f[2].split(".")[1])||0})}b.sort(function(h,k){return k.timestamp-h.timestamp});return b};
function jg(a,b){var c=ig(a),d={};if(!c||!c.length)return d;for(var e=0;e<c.length;e++){var f=c[e].value.split(".");if(!("1"!==f[0]||b&&3>f.length||!b&&3!==f.length)&&Number(f[1])){d[c[e].pe]||(d[c[e].pe]=[]);var h={version:f[0],timestamp:1E3*Number(f[1]),na:f[2]};b&&3<f.length&&(h.labels=f.slice(3));d[c[e].pe].push(h)}}return d};function kg(){for(var a=lg,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function mg(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}var lg,ng;
function og(a){function b(l){for(;d<a.length;){var n=a.charAt(d++),q=ng[n];if(null!=q)return q;if(!/^[\s\xa0]*$/.test(n))throw Error("Unknown base64 encoding at char: "+n);}return l}lg=lg||mg();ng=ng||kg();for(var c="",d=0;;){var e=b(-1),f=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|f>>4);64!=h&&(c+=String.fromCharCode(f<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var pg;var tg=function(){var a=qg,b=rg,c=sg(),d=function(h){a(h.target||h.srcElement||{})},e=function(h){b(h.target||h.srcElement||{})};if(!c.init){Ib(m,"mousedown",d);Ib(m,"keyup",d);Ib(m,"submit",e);var f=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);f.call(this)};c.init=!0}},ug=function(a,b,c,d,e){var f={callback:a,domains:b,fragment:2===c,placement:c,forms:d,sameHost:e};sg().decorators.push(f)},vg=function(a,b,c){for(var d=sg().decorators,e={},f=0;f<d.length;++f){var h=
d[f],k;if(k=!c||h.forms)a:{var l=h.domains,n=a,q=!!h.sameHost;if(l&&(q||n!==m.location.hostname))for(var p=0;p<l.length;p++)if(l[p]instanceof RegExp){if(l[p].test(n)){k=!0;break a}}else if(0<=n.indexOf(l[p])||q&&0<=l[p].indexOf(n)){k=!0;break a}k=!1}if(k){var r=h.placement;void 0==r&&(r=h.fragment?2:1);r===b&&Ya(e,h.callback())}}return e},sg=function(){var a=yb("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var wg=/(.*?)\*(.*?)\*(.*)/,xg=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,yg=/^(?:www\.|m\.|amp\.)+/,zg=/([^?#]+)(\?[^#]*)?(#.*)?/;function Ag(a){return new RegExp("(.*?)(^|&)"+a+"=([^&]*)&?(.*)")}
var Cg=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];if(void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()){b.push(c);var e=b,f=e.push,h,k=String(d);lg=lg||mg();ng=ng||kg();for(var l=[],n=0;n<k.length;n+=3){var q=n+1<k.length,p=n+2<k.length,r=k.charCodeAt(n),t=q?k.charCodeAt(n+1):0,u=p?k.charCodeAt(n+2):0,v=r>>2,x=(r&3)<<4|t>>4,z=(t&15)<<2|u>>6,w=u&63;p||(w=64,q||(z=64));l.push(lg[v],lg[x],lg[z],lg[w])}h=l.join("");f.call(e,h)}}var y=b.join("*");return["1",Bg(y),
y].join("*")},Bg=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=pg)){for(var e=Array(256),f=0;256>f;f++){for(var h=f,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[f]=h}d=e}pg=d;for(var l=4294967295,n=0;n<c.length;n++)l=l>>>8^pg[(l^c.charCodeAt(n))&255];return((l^-1)>>>0).toString(36)},Eg=function(){return function(a){var b=pe(g.location.href),
c=b.search.replace("?",""),d=ke(c,"_gl",!0)||"";a.query=Dg(d)||{};var e=ne(b,"fragment").match(Ag("_gl"));a.fragment=Dg(e&&e[3]||"")||{}}},Fg=function(a){var b=Eg(),c=sg();c.data||(c.data={query:{},fragment:{}},b(c.data));var d={},e=c.data;e&&(Ya(d,e.query),a&&Ya(d,e.fragment));return d},Dg=function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var f=wg.exec(d);if(f){c=f;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var n=h[2],q=0;q<
b;++q)if(n===Bg(k,q)){l=!0;break a}l=!1}if(l){for(var p={},r=k?k.split("*"):[],t=0;t<r.length;t+=2)p[r[t]]=og(r[t+1]);return p}}}}catch(u){}};function Gg(a,b,c,d){function e(q){var p=q,r=Ag(a).exec(p),t=p;if(r){var u=r[2],v=r[4];t=r[1];v&&(t=t+u+v)}q=t;var x=q.charAt(q.length-1);q&&"&"!==x&&(q+="&");return q+n}d=void 0===d?!1:d;var f=zg.exec(c);if(!f)return"";var h=f[1],k=f[2]||"",l=f[3]||"",n=a+"="+b;d?l="#"+e(l.substring(1)):k="?"+e(k.substring(1));return""+h+k+l}
function Hg(a,b){var c="FORM"===(a.tagName||"").toUpperCase(),d=vg(b,1,c),e=vg(b,2,c),f=vg(b,3,c);if(Za(d)){var h=Cg(d);c?Ig("_gl",h,a):Jg("_gl",h,a,!1)}if(!c&&Za(e)){var k=Cg(e);Jg("_gl",k,a,!0)}for(var l in f)if(f.hasOwnProperty(l))a:{var n=l,q=f[l],p=a;if(p.tagName){if("a"===p.tagName.toLowerCase()){Jg(n,q,p,void 0);break a}if("form"===p.tagName.toLowerCase()){Ig(n,q,p);break a}}"string"==typeof p&&Gg(n,q,p,void 0)}}
function Jg(a,b,c,d){if(c.href){var e=Gg(a,b,c.href,void 0===d?!1:d);ib.test(e)&&(c.href=e)}}
function Ig(a,b,c){if(c&&c.action){var d=(c.method||"").toLowerCase();if("get"===d){for(var e=c.childNodes||[],f=!1,h=0;h<e.length;h++){var k=e[h];if(k.name===a){k.setAttribute("value",b);f=!0;break}}if(!f){var l=m.createElement("input");l.setAttribute("type","hidden");l.setAttribute("name",a);l.setAttribute("value",b);c.appendChild(l)}}else if("post"===d){var n=Gg(a,b,c.action);ib.test(n)&&(c.action=n)}}}
var qg=function(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var f=e.protocol;"http:"!==f&&"https:"!==f||Hg(e,e.hostname)}}catch(h){}},rg=function(a){try{if(a.action){var b=ne(pe(a.action),"host");Hg(a,b)}}catch(c){}},Kg=function(a,b,c,d){tg();ug(a,b,"fragment"===c?2:1,!!d,!1)},Lg=function(a,b){tg();ug(a,[me(g.location,"host",!0)],b,!0,!0)},Mg=function(){var a=m.location.hostname,b=xg.exec(m.referrer);if(!b)return!1;
var c=b[2],d=b[1],e="";if(c){var f=c.split("/"),h=f[1];e="s"===h?decodeURIComponent(f[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}var k=a.replace(yg,""),l=e.replace(yg,""),n;if(!(n=k===l)){var q="."+l;n=k.substring(k.length-q.length,k.length)===q}return n},Ng=function(a,b){return!1===a?!1:a||b||Mg()};var Og={};var Pg=/^\w+$/,Qg=/^[\w-]+$/,Rg={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp",gb:"_gb"},Sg=function(){if(!yd(rd)||!Jd())return!0;var a=Gd("ad_storage");return null==a?!0:!!a},Tg=function(a,b){Id("ad_storage")?Sg()?a():Od(a,"ad_storage"):b?ra("TAGGING",3):Nd(function(){Tg(a,!0)},["ad_storage"])},Vg=function(a){return Ug(a).map(function(b){return b.na})},Ug=function(a){var b=[];if(!Ef(g)||!m.cookie)return b;var c=Hf(a,m.cookie,void 0,"ad_storage");if(!c||0==c.length)return b;for(var d={},e=0;e<c.length;d=
{hc:d.hc},e++){var f=Wg(c[e]);if(null!=f){var h=f,k=h.version;d.hc=h.na;var l=h.timestamp,n=h.labels,q=za(b,function(p){return function(r){return r.na===p.hc}}(d));q?(q.timestamp=Math.max(q.timestamp,l),q.labels=Xg(q.labels,n||[])):b.push({version:k,na:d.hc,timestamp:l,labels:n})}}b.sort(function(p,r){return r.timestamp-p.timestamp});return Yg(b)};function Xg(a,b){for(var c={},d=[],e=0;e<a.length;e++)c[a[e]]=!0,d.push(a[e]);for(var f=0;f<b.length;f++)c[b[f]]||d.push(b[f]);return d}
function Zg(a){return a&&"string"==typeof a&&a.match(Pg)?a:"_gcl"}
var ah=function(){var a=pe(g.location.href),b=ne(a,"query",!1,void 0,"gclid"),c=ne(a,"query",!1,void 0,"gclsrc"),d=ne(a,"query",!1,void 0,"wbraid"),e=ne(a,"query",!1,void 0,"dclid");if(!b||!c||!d){var f=a.hash.replace("#","");b=b||ke(f,"gclid",void 0);c=c||ke(f,"gclsrc",void 0);d=d||ke(f,"wbraid",void 0)}return $g(b,c,e,d)},$g=function(a,b,c,d){var e={},f=function(h,k){e[k]||(e[k]=[]);e[k].push(h)};e.gclid=a;e.gclsrc=b;e.dclid=c;void 0!==d&&Qg.test(d)&&(e.gbraid=d,f(d,"gb"));if(void 0!==a&&a.match(Qg))switch(b){case void 0:f(a,
"aw");break;case "aw.ds":f(a,"aw");f(a,"dc");break;case "ds":f(a,"dc");break;case "3p.ds":f(a,"dc");break;case "gf":f(a,"gf");break;case "ha":f(a,"ha")}c&&f(c,"dc");return e},bh=function(a,b){switch(a){case void 0:case "aw":return"aw"===b;case "aw.ds":return"aw"===b||"dc"===b;case "ds":case "3p.ds":return"dc"===b;case "gf":return"gf"===b;case "ha":return"ha"===b}return!1},dh=function(a){var b=ah();Tg(function(){ch(b,a)})};
function ch(a,b,c,d){function e(q,p){var r=eh(q,f);r&&(Qf(r,p,h),k=!0)}b=b||{};d=d||[];var f=Zg(b.prefix);c=c||Pa();var h=bg(b,c,!0);h.Na="ad_storage";var k=!1,l=Math.round(c/1E3),n=function(q){var p=["GCL",l,q];0<d.length&&p.push(d.join("."));return p.join(".")};a.aw&&e("aw",n(a.aw[0]));a.dc&&e("dc",n(a.dc[0]));a.gf&&e("gf",n(a.gf[0]));a.ha&&e("ha",n(a.ha[0]));a.gp&&e("gp",n(a.gp[0]));(void 0==Og.enable_gbraid_cookie_write?0:Og.enable_gbraid_cookie_write)&&!k&&a.gb&&e("gb",n(a.gb[0]))}
var gh=function(a,b){var c=Fg(!0);Tg(function(){for(var d=Zg(b.prefix),e=0;e<a.length;++e){var f=a[e];if(void 0!==Rg[f]){var h=eh(f,d),k=c[h];if(k){var l=Math.min(fh(k),Pa()),n;b:{var q=l,p=h;if(Ef(g))for(var r=Hf(p,m.cookie,void 0,"ad_storage"),t=0;t<r.length;++t)if(fh(r[t])>q){n=!0;break b}n=!1}if(!n){var u=bg(b,l,!0);u.Na="ad_storage";Qf(h,k,u)}}}}ch($g(c.gclid,c.gclsrc),b)})},eh=function(a,b){var c=Rg[a];if(void 0!==c)return b+c},fh=function(a){return 0!==hh(a.split(".")).length?1E3*(Number(a.split(".")[1])||
0):0};function Wg(a){var b=hh(a.split("."));return 0===b.length?null:{version:b[0],na:b[2],timestamp:1E3*(Number(b[1])||0),labels:b.slice(3)}}function hh(a){return 3>a.length||"GCL"!==a[0]&&"1"!==a[0]||!/^\d+$/.test(a[1])||!Qg.test(a[2])?[]:a}
var ih=function(a,b,c,d,e){if(xa(b)&&Ef(g)){var f=Zg(e),h=function(){for(var k={},l=0;l<a.length;++l){var n=eh(a[l],f);if(n){var q=Hf(n,m.cookie,void 0,"ad_storage");q.length&&(k[n]=q.sort()[q.length-1])}}return k};Tg(function(){Kg(h,b,c,d)})}},Yg=function(a){return a.filter(function(b){return Qg.test(b.na)})},jh=function(a,b){if(Ef(g)){for(var c=Zg(b.prefix),d={},e=0;e<a.length;e++)Rg[a[e]]&&(d[a[e]]=Rg[a[e]]);Tg(function(){Fa(d,function(f,h){var k=Hf(c+h,m.cookie,void 0,"ad_storage");k.sort(function(t,
u){return fh(u)-fh(t)});if(k.length){var l=k[0],n=fh(l),q=0!==hh(l.split(".")).length?l.split(".").slice(3):[],p={},r;r=0!==hh(l.split(".")).length?l.split(".")[2]:void 0;p[f]=[r];ch(p,b,n,q)}})})}};function kh(a,b){for(var c=0;c<b.length;++c)if(a[b[c]])return!0;return!1}
var lh=function(a){function b(e,f,h){h&&(e[f]=h)}if(Jd()){var c=ah();if(kh(c,a)){var d={};b(d,"gclid",c.gclid);b(d,"dclid",c.dclid);b(d,"gclsrc",c.gclsrc);b(d,"wbraid",c.gbraid);Lg(function(){return d},3);Lg(function(){var e={};return e._up="1",e},1)}}};function mh(a,b){var c=Zg(b),d=eh(a,c);if(!d)return 0;for(var e=Ug(d),f=0,h=0;h<e.length;h++)f=Math.max(f,e[h].timestamp);return f}
function nh(a){var b=0,c;for(c in a)for(var d=a[c],e=0;e<d.length;e++)b=Math.max(b,Number(d[e].timestamp));return b};var oh=/^\d+\.fls\.doubleclick\.net$/;function ph(a,b){Id(G.D)?I(G.D)?a():Od(a,G.D):b?od(42):Vd(function(){ph(a,!0)},[G.D])}function qh(a){var b=pe(g.location.href),c=ne(b,"host",!1);if(c&&c.match(oh)){var d=ne(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function rh(a,b,c){if("aw"===a||"dc"===a||"gb"===a){var d=qh("gcl"+a);if(d)return d.split(".")}var e=Zg(b);if("_gcl"==e){c=void 0===c?!0:c;var f=!I(G.D)&&c,h;h=ah()[a]||[];if(0<h.length)return f?["0"]:h}var k=eh(a,e);return k?Vg(k):[]}function sh(a){var b=[];Fa(a,function(c,d){d=Yg(d);for(var e=[],f=0;f<d.length;f++)e.push(d[f].na);e.length&&b.push(c+":"+e.join(","))});return b.join(";")}
var th=function(a){var b=qh("gac");return b?!I(G.D)&&a?"0":decodeURIComponent(b):sh(Sg()?jg():{})},uh=function(a){var b=qh("gacgb");return b?!I(G.D)&&a?"0":decodeURIComponent(b):sh(Sg()?jg("_gac_gb",!0):{})},vh=function(a,b,c){var d=ah(),e=[],f=d.gclid,h=d.dclid,k=d.gclsrc||"aw";!f||"aw.ds"!==k&&"aw"!==k&&"ds"!==k||c&&!bh(k,c)||e.push({na:f,Td:k});!h||c&&"dc"!==c||e.push({na:h,Td:"ds"});ph(function(){hg(b);var l=dg[eg(b.prefix)],n=!1;if(l&&0<e.length)for(var q=Ye.joined_auid=Ye.joined_auid||{},p=0;p<e.length;p++){var r=e[p],t=r.na,u=r.Td,v=(b.prefix||"_gcl")+"."+u+"."+t;if(!q[v]){var x="https://adservice.google.com/pagead/regclk";x="gb"===u?x+"?gbraid="+t+"&auid="+l:x+"?gclid="+t+"&auid="+l+"&gclsrc="+u;Pb(x);n=q[v]=!0}}null==a&&(a=n);
if(a&&l){var z=eg(b.prefix),w=dg[z];w&&gg(z,w,b)}})},wh=function(a){var b;if(qh("gclaw")||qh("gac")||0<(ah().aw||[]).length)b=!1;else{var c;if(0<(ah().gb||[]).length)c=!0;else{var d=Math.max(mh("aw",a),nh(Sg()?jg():{}));c=Math.max(mh("gb",a),nh(Sg()?jg("_gac_gb",!0):{}))>d}b=c}return b};var xh=/[A-Z]+/,yh=/\s/,zh=function(a){if(va(a)&&(a=Na(a),!yh.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(xh.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],L:d}}}}},Bh=function(a){for(var b={},c=0;c<a.length;++c){var d=zh(a[c]);d&&(b[d.id]=d)}Ah(b);var e=[];Fa(b,function(f,h){e.push(h)});return e};
function Ah(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.L[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var Ch=function(){var a=!1;return a};var Eh=function(a,b,c,d){return(2===Dh()||d||"http:"!=g.location.protocol?a:b)+c},Dh=function(){var a=Fb(),b;if(1===a)a:{var c=df;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,f=1,h=m.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===f&&0===l.indexOf(d)&&(f=2)}}b=f}else b=a;return b};
var Gh=function(a,b,c){if(g[a.functionName])return b.ce&&B(b.ce),g[a.functionName];var d=Fh();g[a.functionName]=d;if(a.Lc)for(var e=0;e<a.Lc.length;e++)g[a.Lc[e]]=g[a.Lc[e]]||Fh();a.Sc&&void 0===g[a.Sc]&&(g[a.Sc]=c);Eb(Eh("https://","http://",a.me),b.ce,b.Uh);return d},Fh=function(){var a=function(){a.q=a.q||[];a.q.push(arguments)};return a},Hh={functionName:"_googWcmImpl",Sc:"_googWcmAk",me:"www.gstatic.com/wcm/loader.js"},Ih={functionName:"_gaPhoneImpl",Sc:"ga_wpid",me:"www.gstatic.com/gaphone/loader.js"},
Jh={fg:"",$g:"5"},Kh={functionName:"_googCallTrackingImpl",Lc:[Ih.functionName,Hh.functionName],me:"www.gstatic.com/call-tracking/call-tracking_"+(Jh.fg||Jh.$g)+".js"},Lh={},Mh=function(a,b,c,d){od(22);if(c){d=d||{};var e=Gh(Hh,d,a),f={ak:a,cl:b};void 0===d.La&&(f.autoreplace=c);e(2,d.La,f,c,0,Oa(),d.options)}},Nh=function(a,b,c,d){od(21);if(b&&c){d=d||{};for(var e={countryNameCode:c,destinationNumber:b,retrievalTime:Oa()},f=0;f<a.length;f++){var h=a[f];Lh[h.id]||
(h&&"AW"===h.prefix&&!e.adData&&2<=h.L.length?(e.adData={ak:h.L[0],cl:h.L[1]},Lh[h.id]=!0):h&&"UA"===h.prefix&&!e.gaData&&(e.gaData={gaWpid:h.containerId},Lh[h.id]=!0))}(e.gaData||e.adData)&&Gh(Kh,d)(d.La,e,d.options)}},Oh=function(){var a=!1;return a},Ph=function(a,b){if(a)if(Ch()){}else{if(va(a)){var c=
zh(a);if(!c)return;a=c}var d=void 0,e=!1,f=b.getWithConfig(G.Lg);if(f&&xa(f)){d=[];for(var h=0;h<f.length;h++){var k=zh(f[h]);k&&(d.push(k),(a.id===k.id||a.id===a.containerId&&a.containerId===k.containerId)&&(e=!0))}}if(!d||e){var l=b.getWithConfig(G.Ue),n;if(l){xa(l)?n=l:n=[l];var q=b.getWithConfig(G.Se),p=b.getWithConfig(G.Te),r=b.getWithConfig(G.Ve),t=b.getWithConfig(G.Kg),u=q||p,v=1;"UA"!==a.prefix||d||(v=5);for(var x=0;x<n.length;x++)if(x<v)if(d)Nh(d,n[x],t,{La:u,options:r});else if("AW"===a.prefix&&
a.L[1])Oh()?Nh([a],n[x],t||"US",{La:u,options:r}):Mh(a.L[0],a.L[1],n[x],{La:u,options:r});else if("UA"===a.prefix)if(Oh())Nh([a],n[x],t||"US",{La:u});else{var z=a.containerId,w=n[x],y={La:u};od(23);if(w){y=y||{};var A=Gh(Ih,y,z),C={};void 0!==y.La?C.receiver=y.La:C.replace=w;C.ga_wpid=z;C.destination=w;A(2,Oa(),C)}}}}}};
var Rh=function(a){if(I(G.D))return a;a=a.replace(/&url=([^&#]+)/,function(b,c){var d=qe(decodeURIComponent(c));return"&url="+encodeURIComponent(d)});a=a.replace(/&ref=([^&#]+)/,function(b,c){var d=qe(decodeURIComponent(c));return"&ref="+encodeURIComponent(d)});return a},Sh=function(){var a;if(!(a=ef)){var b;if(!0===g._gtmdgs)b=!0;else{var c=wb&&wb.userAgent||"";b=0>c.indexOf("Safari")||/Chrome|Coast|Opera|Edg|Silk|Android/.test(c)||
11>((/Version\/([\d]+)/.exec(c)||[])[1]||"")?!1:!0}a=!b}if(a)return-1;var d=Ia("1");return Cf(1,100)<d?Cf(2,2):-1},Th=function(a){var b;if(!a||!a.length)return;for(var c=[],d=0;d<a.length;++d){var e=a[d];e&&e.estimated_delivery_date?c.push(""+e.estimated_delivery_date):c.push("")}b=c.join(",");return b};var Uh=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Vh={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Wh={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Xh="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var Yh=function(){var a=!1;a=!0;return a},$h=function(a){var b=rf("gtm.allowlist")||rf("gtm.whitelist");b&&od(9);Yh()&&(b="google gtagfl lcl zone oid op".split(" "));var c=b&&$a(Ka(b),Vh),d=rf("gtm.blocklist")||
rf("gtm.blacklist");d||(d=rf("tagTypeBlacklist"))&&od(3);d?od(8):d=[];Zh()&&(d=Ka(d),d.push("nonGooglePixels","nonGoogleScripts","sandboxedScripts"));0<=ya(Ka(d),"google")&&od(2);var e=d&&$a(Ka(d),Wh),f={};return function(h){var k=h&&h[Wb.ab];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==f[k])return f[k];var l=kf[k]||[],n=a(k,l);if(b){var q;if(q=
n)a:{if(0>ya(c,k))if(l&&0<l.length)for(var p=0;p<l.length;p++){if(0>ya(c,l[p])){od(11);q=!1;break a}}else{q=!1;break a}q=!0}n=q}var r=!1;if(d){var t=0<=ya(e,k);if(t)r=t;else{var u=Ea(e,l||[]);u&&od(10);r=u}}var v=!n||r;v||!(0<=ya(l,"sandboxedScripts"))||c&&-1!==ya(c,"sandboxedScripts")||(v=Ea(e,Xh));return f[k]=v}},Zh=function(){return Uh.test(g.location&&g.location.hostname)};var ai={active:!0,isAllowed:function(){return!0}},bi=function(a){var b=Ye.zones;return b?b.checkState(Xe.M,a):ai},ci=function(a){var b=Ye.zones;!b&&a&&(b=Ye.zones=a());return b};var di=function(){},ei=function(){};var fi=!1,gi=0,hi=[];function ii(a){if(!fi){var b=m.createEventObject,c="complete"==m.readyState,d="interactive"==m.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){fi=!0;for(var e=0;e<hi.length;e++)B(hi[e])}hi.push=function(){for(var f=0;f<arguments.length;f++)B(arguments[f]);return 0}}}function ji(){if(!fi&&140>gi){gi++;try{m.documentElement.doScroll("left"),ii()}catch(a){g.setTimeout(ji,50)}}}var ki=function(a){fi?a():hi.push(a)};var mi=function(a,b){this.o=!1;this.F=[];this.T={tags:[]};this.Y=!1;this.s=this.B=0;li(this,a,b)},ni=function(a,b,c,d){if(af.hasOwnProperty(b)||"__zone"===b)return-1;var e={};Ub(d)&&(e=E(d,e));e.id=c;e.status="timeout";return a.T.tags.push(e)-1},oi=function(a,b,c,d){var e=a.T.tags[b];e&&(e.status=c,e.executionTime=d)},pi=function(a){if(!a.o){for(var b=a.F,c=0;c<b.length;c++)b[c]();a.o=!0;a.F.length=0}},li=function(a,b,c){ua(b)&&qi(a,b);c&&g.setTimeout(function(){return pi(a)},Number(c))},qi=function(a,
b){var c=Xa(function(){return B(function(){b(Xe.M,a.T)})});a.o?c():a.F.push(c)},ri=function(a){a.B++;return Xa(function(){a.s++;a.Y&&a.s>=a.B&&pi(a)})};var si=function(){function a(d){return!wa(d)||0>d?0:d}if(!Ye._li&&g.performance&&g.performance.timing){var b=g.performance.timing.navigationStart,c=wa(sf.get("gtm.start"))?sf.get("gtm.start"):0;Ye._li={cst:a(c-b),cbt:a(gf-b)}}},ti=function(a){g.performance&&g.performance.mark(Xe.M+"_"+a+"_start")},ui=function(a){if(g.performance){var b=Xe.M+"_"+a+"_start",c=Xe.M+"_"+a+"_duration";g.performance.measure(c,b);var d=g.performance.getEntriesByName(c)[0];g.performance.clearMarks(b);g.performance.clearMeasures(c);
var e=Ye._p||{};void 0===e[a]&&(e[a]=d.duration,Ye._p=e);return d.duration}},vi=function(){if(g.performance&&g.performance.now){var a=Ye._p||{};a.PAGEVIEW=g.performance.now();Ye._p=a}};var wi={},xi=function(){return g.GoogleAnalyticsObject&&g[g.GoogleAnalyticsObject]},yi=!1;
var zi=function(a){g.GoogleAnalyticsObject||(g.GoogleAnalyticsObject=a||"ga");var b=g.GoogleAnalyticsObject;if(g[b])g.hasOwnProperty(b)||od(12);else{var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(Oa());g[b]=c}si();return g[b]},Fi=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=xi();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)},Gi=function(a){if(!Jd())return;var b=xi();b(a+"require","linker");b(a+"linker:passthrough",
!0);};
var Ii=function(a){},Hi=function(){return g.GoogleAnalyticsObject||"ga"},Ji=function(a,b){return function(){var c=xi(),d=c&&c.getByName&&c.getByName(a);if(d){var e=d.get("sendHitTask");d.set("sendHitTask",function(f){var h=f.get("hitPayload"),k=f.get("hitCallback"),l=0>h.indexOf("&tid="+b);l&&(f.set("hitPayload",h.replace(/&tid=UA-[0-9]+-[0-9]+/,"&tid="+
b),!0),f.set("hitCallback",void 0,!0));e(f);l&&(f.set("hitPayload",h,!0),f.set("hitCallback",k,!0),f.set("_x_19",void 0,!0),e(f))})}}};
var Qi=function(a){},Ui=function(a){},Vi=
function(){return"&tc="+Bc.filter(function(a){return a}).length},Yi=function(){2022<=Wi().length&&Xi()},$i=function(){Zi||(Zi=g.setTimeout(Xi,500))},Xi=function(){Zi&&(g.clearTimeout(Zi),Zi=void 0);void 0===aj||bj[aj]&&!cj&&!dj||(ej[aj]||fj.Kh()||0>=gj--?(od(1),ej[aj]=!0):(fj.bi(),Hb(Wi(!0)),bj[aj]=!0,hj=ij=jj=dj=cj=""))},Wi=function(a){var b=aj;if(void 0===b)return"";var c=sa("GTM"),d=sa("TAGGING");return[kj,bj[b]?"":"&es=1",lj[b],Qi(b),c?"&u="+c:"",d?"&ut="+d:"",Vi(),cj,dj,jj,ij,Ui(a),hj,"&z=0"].join("")},
nj=function(){kj=mj()},mj=function(){return[hf,"&v=3&t=t","&pid="+Ba(),"&rv="+Xe.Ic].join("")},Ti=["L","S","Y"],Pi=["S","E"],oj={ei:"0.005000",cg:""},pj=Math.random(),qj=oj.ei;var rj=pj<qj,kj=mj(),bj={},cj="",dj="",hj="",ij="",Si={},Oi={},Ri=!1,jj="",aj=void 0,lj={},ej={},Zi=void 0,fj=function(a,b){var c=0,d=
0;return{Kh:function(){if(c<a)return!1;Pa()-d>=b&&(c=0);return c>=a},bi:function(){Pa()-d>=b&&(c=0);c++;d=Pa()}}}(2,1E3),gj=1E3,sj=function(a,b,c,d){if(rj&&!ej[a]&&b){a!==aj&&(Xi(),aj=a);var e,f=String(b[Wb.ab]||"").replace(/_/g,"");0===f.indexOf("cvt")&&(f="cvt");e=f;var h=c+e;cj=cj?cj+"."+h:"&tr="+h;
var k=b["function"];if(!k)throw Error("Error: No function name given for function call.");var l=(Dc[k]?"1":"2")+e;hj=hj?hj+"."+l:"&ti="+l;$i();Yi()}};var vj=function(a,b,c){if(rj&&!ej[a]){a!==
aj&&(Xi(),aj=a);var d=c+b;dj=dj?dj+"."+d:"&epr="+d;$i();Yi()}},wj=function(a,b,c){};function xj(a,b,c,d){var e=Bc[a],f=yj(a,b,c,d);if(!f)return null;var h=Ic(e[Wb.pf],c,[]);if(h&&h.length){var k=h[0];f=xj(k.index,{onSuccess:f,onFailure:1===k.Gf?b.terminate:f,terminate:b.terminate},c,d)}return f}
function yj(a,b,c,d){function e(){if(f[Wb.Wg])k();else{var x=Jc(f,c,[]);var z=x[Wb.gg];if(null!=z)for(var w=0;w<z.length;w++)if(!I(z[w])){k();return}var y=ni(c.cb,String(f[Wb.ab]),Number(f[Wb.rf]),x[Wb.Xg]),A=!1;x.vtp_gtmOnSuccess=function(){if(!A){A=!0;var D=Pa()-F;sj(c.id,Bc[a],"5",D);oi(c.cb,y,"success",
D);h()}};x.vtp_gtmOnFailure=function(){if(!A){A=!0;var D=Pa()-F;sj(c.id,Bc[a],"6",D);oi(c.cb,y,"failure",D);k()}};x.vtp_gtmTagId=f.tag_id;x.vtp_gtmEventId=c.id;sj(c.id,f,"1");var C=function(){var D=Pa()-F;sj(c.id,f,"7",D);oi(c.cb,y,"exception",D);A||(A=!0,k())};var F=Pa();try{Hc(x,c)}catch(D){C(D)}}}var f=Bc[a],h=b.onSuccess,k=b.onFailure,l=b.terminate;if(c.Zd(f))return null;var n=Ic(f[Wb.sf],c,[]);if(n&&n.length){var q=n[0],p=xj(q.index,{onSuccess:h,onFailure:k,terminate:l},c,d);if(!p)return null;h=p;k=2===q.Gf?l:p}if(f[Wb.ef]||f[Wb.Zg]){var r=f[Wb.ef]?Cc:
c.ji,t=h,u=k;if(!r[a]){e=Xa(e);var v=zj(a,r,e);h=v.onSuccess;k=v.onFailure}return function(){r[a](t,u)}}return e}function zj(a,b,c){var d=[],e=[];b[a]=Aj(d,e,c);return{onSuccess:function(){b[a]=Bj;for(var f=0;f<d.length;f++)d[f]()},onFailure:function(){b[a]=Cj;for(var f=0;f<e.length;f++)e[f]()}}}function Aj(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function Bj(a){a()}function Cj(a,b){b()};var Fj=function(a,b){for(var c=[],d=0;d<Bc.length;d++)if(a[d]){var e=Bc[d];var f=ri(b.cb);try{var h=xj(d,{onSuccess:f,onFailure:f,terminate:f},b,d);if(h){var k=c,l=k.push,n=d,q=e["function"];if(!q)throw"Error: No function name given for function call.";var p=Dc[q];l.call(k,{Zf:n,Pf:p?p.priorityOverride||0:0,yh:h})}else Dj(d,b),f()}catch(u){f()}}var r=b.cb;r.Y=!0;r.s>=r.B&&pi(r);c.sort(Ej);for(var t=0;t<c.length;t++)c[t].yh();
return 0<c.length};function Ej(a,b){var c,d=b.Pf,e=a.Pf;c=d>e?1:d<e?-1:0;var f;if(0!==c)f=c;else{var h=a.Zf,k=b.Zf;f=h>k?1:h<k?-1:0}return f}function Dj(a,b){if(!rj)return;var c=function(d){var e=b.Zd(Bc[d])?"3":"4",f=Ic(Bc[d][Wb.pf],b,[]);f&&f.length&&c(f[0].index);sj(b.id,Bc[d],e);var h=Ic(Bc[d][Wb.sf],b,[]);h&&h.length&&c(h[0].index)};c(a);}
var Gj=!1,Mj=function(a){var b=Pa(),c=a["gtm.uniqueEventId"],d=a.event;if("gtm.js"===d){if(Gj)return!1;Gj=!0;}var h=bi(c),k=!1;if(!h.active){if("gtm.js"!==d)return!1;k=!0;h=bi(Number.MAX_SAFE_INTEGER)}
rj&&!ej[c]&&aj!==c&&(Xi(),aj=c,hj=cj="",lj[c]="&e="+(0===d.indexOf("gtm.")?encodeURIComponent(d):"*")+"&eid="+c,$i());var l=a.eventCallback,n=a.eventTimeout,q=l;var p={id:c,name:d,Zd:$h(h.isAllowed),ji:[],Lf:function(){od(6)},zf:Hj(c),cb:new mi(q,
n)};p.yf=Ij();Jj(c,p.cb);var r=Nc(p);k&&(r=Kj(r));var t=Fj(r,p);"gtm.js"!==d&&"gtm.sync"!==d||Ii(Xe.M);
switch(d){case "gtm.init":t&&od(20)}return Lj(r,t)};function Hj(a){return function(b){rj&&(Vb(b)||wj(a,"input",b))}}function Jj(a,b){wf(a,"event",1);wf(a,"ecommerce",1);wf(a,"gtm");wf(a,"eventModel");}
function Ij(){var a={};a.event=vf("event",1);a.ecommerce=vf("ecommerce",1);a.gtm=vf("gtm");a.eventModel=vf("eventModel");return a}function Kj(a){for(var b=[],c=0;c<a.length;c++)a[c]&&$e[String(Bc[c][Wb.ab])]&&(b[c]=!0);return b}function Lj(a,b){if(!b)return b;for(var c=0;c<a.length;c++)if(a[c]&&Bc[c]&&!af[String(Bc[c][Wb.ab])])return!0;return!1}function Nj(a,b){if(a){var c=""+a;0!==c.indexOf("http://")&&0!==c.indexOf("https://")&&(c="https://"+c);"/"===c[c.length-1]&&(c=c.substring(0,c.length-1));return pe(""+c+b).href}}function Oj(a,b){return Pj()?Nj(a,b):void 0}function Pj(){var a=!1;return a};var Qj=function(){this.eventModel={};this.targetConfig={};this.containerConfig={};this.remoteConfig={};this.globalConfig={};this.onSuccess=function(){};this.onFailure=function(){};this.setContainerTypeLoaded=function(){};this.getContainerTypeLoaded=function(){};this.eventId=void 0;this.isGtmEvent=!1},Rj=function(a){var b=new Qj;b.eventModel=a;return b},Sj=function(a,b){a.targetConfig=b;return a},Tj=function(a,b){a.containerConfig=b;return a},Uj=function(a,b){a.remoteConfig=b;return a},Vj=function(a,
b){a.globalConfig=b;return a},Wj=function(a,b){a.onSuccess=b;return a},Xj=function(a,b){a.setContainerTypeLoaded=b;return a},Yj=function(a,b){a.getContainerTypeLoaded=b;return a},Zj=function(a,b){a.onFailure=b;return a};
Qj.prototype.getWithConfig=function(a){if(void 0!==this.eventModel[a])return this.eventModel[a];if(void 0!==this.targetConfig[a])return this.targetConfig[a];if(void 0!==this.containerConfig[a])return this.containerConfig[a];if(void 0!==this.remoteConfig[a])return this.remoteConfig[a];if(void 0!==this.globalConfig[a])return this.globalConfig[a]};
var ak=function(a){function b(e){Fa(e,function(f){c[f]=null})}var c={};b(a.eventModel);b(a.targetConfig);b(a.containerConfig);b(a.globalConfig);var d=[];Fa(c,function(e){d.push(e)});return d},bk=function(a,b){function c(f){Ub(f)&&Fa(f,function(h,k){e=!0;d[h]=k})}var d={},e=!1;c(a.globalConfig[b]);c(a.remoteConfig[b]);c(a.containerConfig[b]);c(a.targetConfig[b]);c(a.eventModel[b]);return e?d:void 0};var ck;if(3===Xe.Ic.length)ck="g";else{var dk="G";dk="g";ck=dk}
var ek={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:ck,OPT:"o"},fk=function(a){var b=Xe.M.split("-"),c=b[0].toUpperCase(),d=ek[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",f;if(3===Xe.Ic.length){var h="w";h=Ch()?"s":"o";f="2"+h}else f="";return f+d+Xe.Ic+e};var gk=function(a,b){a.addEventListener&&a.addEventListener.call(a,"message",b,!1)};var hk=function(){return mb("iPhone")&&!mb("iPod")&&!mb("iPad")};mb("Opera");mb("Trident")||mb("MSIE");mb("Edge");!mb("Gecko")||-1!=jb.toLowerCase().indexOf("webkit")&&!mb("Edge")||mb("Trident")||mb("MSIE")||mb("Edge");-1!=jb.toLowerCase().indexOf("webkit")&&!mb("Edge")&&mb("Mobile");mb("Macintosh");mb("Windows");mb("Linux")||mb("CrOS");var ik=ma.navigator||null;ik&&(ik.appVersion||"").indexOf("X11");mb("Android");hk();mb("iPad");mb("iPod");hk()||mb("iPad")||mb("iPod");jb.toLowerCase().indexOf("kaios");var jk=function(a,b){for(var c=a,d=0;50>d;++d){var e;try{e=!(!c.frames||!c.frames[b])}catch(k){e=!1}if(e)return c;var f;a:{try{var h=c.parent;if(h&&h!=c){f=h;break a}}catch(k){}f=null}if(!(c=f))break}return null},kk=function(a){var b=m;b=void 0===b?window.document:b;if(!a||!b.head)return null;var c=document.createElement("meta");b.head.appendChild(c);c.httpEquiv="origin-trial";c.content=a;return c};var lk=function(){};var mk=function(a){void 0!==a.addtlConsent&&"string"!==typeof a.addtlConsent&&(a.addtlConsent=void 0);void 0!==a.gdprApplies&&"boolean"!==typeof a.gdprApplies&&(a.gdprApplies=void 0);return void 0!==a.tcString&&"string"!==typeof a.tcString||void 0!==a.listenerId&&"number"!==typeof a.listenerId?2:a.cmpStatus&&"error"!==a.cmpStatus?0:3},nk=function(a,b){this.s=a;this.o=null;this.F={};this.Y=0;this.T=void 0===b?500:b;this.B=null};la(nk,lk);
var pk=function(a){return"function"===typeof a.s.__tcfapi||null!=ok(a)};
nk.prototype.addEventListener=function(a){var b={},c=tb(function(){return a(b)}),d=0;-1!==this.T&&(d=setTimeout(function(){b.tcString="tcunavailable";b.internalErrorState=1;c()},this.T));var e=function(f,h){clearTimeout(d);f?(b=f,b.internalErrorState=mk(b),h&&0===b.internalErrorState||(b.tcString="tcunavailable",h||(b.internalErrorState=3))):(b.tcString="tcunavailable",b.internalErrorState=3);a(b)};try{qk(this,"addEventListener",e)}catch(f){b.tcString="tcunavailable",b.internalErrorState=3,d&&(clearTimeout(d),
d=0),c()}};nk.prototype.removeEventListener=function(a){a&&a.listenerId&&qk(this,"removeEventListener",null,a.listenerId)};
var sk=function(a,b,c){var d;d=void 0===d?"755":d;var e;a:{if(a.publisher&&a.publisher.restrictions){var f=a.publisher.restrictions[b];if(void 0!==f){e=f[void 0===d?"755":d];break a}}e=void 0}var h=e;if(0===h)return!1;var k=c;2===c?(k=0,2===h&&(k=1)):3===c&&(k=1,1===h&&(k=0));var l;if(0===k)if(a.purpose&&a.vendor){var n=rk(a.vendor.consents,void 0===d?"755":d);l=n&&"1"===b&&a.purposeOneTreatment&&("DE"===a.publisherCC||yd(qd)&&"CH"===a.publisherCC)?!0:n&&rk(a.purpose.consents,b)}else l=!0;else l=
1===k?a.purpose&&a.vendor?rk(a.purpose.legitimateInterests,b)&&rk(a.vendor.legitimateInterests,void 0===d?"755":d):!0:!0;return l},rk=function(a,b){return!(!a||!a[b])},qk=function(a,b,c,d){c||(c=function(){});if("function"===typeof a.s.__tcfapi){var e=a.s.__tcfapi;e(b,2,c,d)}else if(ok(a)){tk(a);var f=++a.Y;a.F[f]=c;if(a.o){var h={};a.o.postMessage((h.__tcfapiCall={command:b,version:2,callId:f,parameter:d},h),"*")}}else c({},!1)},ok=function(a){if(a.o)return a.o;a.o=jk(a.s,"__tcfapiLocator");return a.o},
tk=function(a){a.B||(a.B=function(b){try{var c;c=("string"===typeof b.data?JSON.parse(b.data):b.data).__tcfapiReturn;a.F[c.callId](c.returnValue,c.success)}catch(d){}},gk(a.s,a.B))};var uk=!0;uk=!1;var vk={1:0,3:0,4:0,7:3,9:3,10:3};function wk(a,b){if(""===a)return b;var c=Number(a);return isNaN(c)?b:c}var xk=wk("",550),yk=wk("",500);function zk(){var a=Ye.tcf||{};return Ye.tcf=a}
var Ak=function(a,b){this.B=a;this.o=b;this.s=Pa();},Bk=function(a){},Ck=function(a){},Ik=function(){var a=zk(),b=new nk(g,uk?3E3:-1),c=new Ak(b,a);if((Dk()?!0===g.gtag_enable_tcf_support:!1!==g.gtag_enable_tcf_support)&&!a.active&&("function"===typeof g.__tcfapi||pk(b))){a.active=!0;a.$b={};Ek();var d=null;uk?d=g.setTimeout(function(){Fk(a);Gk(a);d=null},yk):a.tcString="tcunavailable";try{b.addEventListener(function(e){d&&(clearTimeout(d),d=null);if(0!==e.internalErrorState)Fk(a),Gk(a),Bk(c);
else{var f;a.gdprApplies=e.gdprApplies;if(!1===e.gdprApplies)f=Hk(),b.removeEventListener(e);else if("tcloaded"===e.eventStatus||"useractioncomplete"===e.eventStatus||"cmpuishown"===e.eventStatus){var h={},k;for(k in vk)if(vk.hasOwnProperty(k))if("1"===k){var l,n=e,q=!0;q=void 0===q?!1:q;var p;var r=n;!1===r.gdprApplies?p=!0:(void 0===r.internalErrorState&&(r.internalErrorState=mk(r)),p="error"===r.cmpStatus||0!==r.internalErrorState||"loaded"===r.cmpStatus&&("tcloaded"===r.eventStatus||"useractioncomplete"===
r.eventStatus)?!0:!1);l=p?!1===n.gdprApplies||"tcunavailable"===n.tcString||void 0===n.gdprApplies&&!q||"string"!==typeof n.tcString||!n.tcString.length?!0:sk(n,"1",0):!1;h["1"]=l}else h[k]=sk(e,k,vk[k]);f=h}f&&(a.tcString=e.tcString||"tcempty",a.$b=f,Gk(a),Bk(c))}}),Ck(c)}catch(e){d&&(clearTimeout(d),d=null),Fk(a),Gk(a)}}};function Fk(a){a.type="e";a.tcString="tcunavailable";uk&&(a.$b=Hk())}function Ek(){var a={},b=(a.ad_storage="denied",a.wait_for_update=xk,a);Rd(b)}
var Dk=function(){var a=!1;a=!0;return a};function Hk(){var a={},b;for(b in vk)vk.hasOwnProperty(b)&&(a[b]=!0);return a}function Gk(a){var b={},c=(b.ad_storage=a.$b["1"]?"granted":"denied",b);Jk();Sd(c,0)}
var Kk=function(){var a=zk();if(a.active&&void 0!==a.loadTime)return Number(a.loadTime)},Jk=function(){var a=zk();return a.active?a.tcString||"":""},Lk=function(){var a=zk();return a.active&&void 0!==a.gdprApplies?a.gdprApplies?"1":"0":""},Mk=function(a){if(!vk.hasOwnProperty(String(a)))return!0;var b=zk();return b.active&&b.$b?!!b.$b[String(a)]:!0};var Nk=!1;Nk=!0;function Ok(a){var b=String(g.location).split(/[?#]/)[0],c=Xe.jg||g._CONSENT_MODE_SALT,d;if(a){var e;if(c){var f=b+a+c,h=1,k,l,n;if(f)for(h=0,l=f.length-1;0<=l;l--)n=f.charCodeAt(l),h=(h<<6&268435455)+n+(n<<14),k=h&266338304,h=0!=k?h^k>>21:h;e=String(h)}else e="0";d=e}else d="";return d}
function Pk(a){function b(u){var v;Ye.reported_gclid||(Ye.reported_gclid={});v=Ye.reported_gclid;var x;x=Nk&&h&&(!Jd()||I(G.D))?l+"."+(f.prefix||"_gcl")+(u?"gcu":"gcs"):l+(u?"gcu":"gcs");if(!v[x]){v[x]=!0;var z=[],w={},y=function(N,Q){Q&&(z.push(N+"="+encodeURIComponent(Q)),w[N]=!0)},A="https://www.google.com";if(Jd()){var C=I(G.D);y("gcs",Td());u&&y("gcu","1");Kd()&&y("gcd","G1"+Pd(Hd));Ye.dedupe_gclid||
(Ye.dedupe_gclid=""+Tf());y("rnd",Ye.dedupe_gclid);if((!l||n&&"aw.ds"!==n)&&I(G.D)){var F=Vg("_gcl_aw");y("gclaw",F.join("."))}y("url",String(g.location).split(/[?#]/)[0]);y("dclid",Qk(d,q));var D=!1;D=!0;C||!d&&!D||(A="https://pagead2.googlesyndication.com")}
y("gdpr_consent",Jk()),y("gdpr",Lk());"1"===Fg(!1)._up&&y("gtm_up","1");y("gclid",Qk(d,l));y("gclsrc",n);if(!(w.gclid||w.dclid||w.gclaw)&&(y("gbraid",Qk(d,p)),!w.gbraid&&Jd()&&I(G.D))){var H=Vg("_gcl_gb");y("gclgb",H.join("."))}y("gtm",fk(!e));Nk&&h&&I(G.D)&&(hg(f||{}),y("auid",dg[eg(f.prefix)]||""));
a.Cf&&y("did",a.Cf);var P=A+"/pagead/landing?"+z.join("&");Pb(P)}}var c=!!a.Od,d=!!a.oa,e=a.P,f=void 0===a.Nc?{}:a.Nc,h=void 0===a.Tc?!0:a.Tc,k=ah(),l=k.gclid||"",n=k.gclsrc,q=k.dclid||"",p=k.gbraid||"",r=!c&&((!l||n&&"aw.ds"!==n?!1:!0)||p),t=Jd();if(r||t)t?Vd(function(){b();I(G.D)||Ud(function(u){return b(!0,u.nh)},G.D)},[G.D]):b()}function Qk(a,b){var c=a&&!I(G.D);return b&&c?"0":b}var Rl=function(){var a=!0;Mk(7)&&Mk(9)&&Mk(10)||(a=!1);var b=!0;b=!1;b&&!Ql()&&(a=!1);return a},Ql=function(){var a=!0;Mk(3)&&Mk(4)||(a=!1);return a};
var Vl=function(a,b){var c=b.getWithConfig(G.Qa),d=b.getWithConfig(G.Pa),e=b.getWithConfig(c);if(void 0===e){var f=void 0;Sl.hasOwnProperty(c)?f=Sl[c]:Tl.hasOwnProperty(c)&&(f=Tl[c]);1===f&&(f=Ul(c));va(f)?xi()(function(){var h=xi().getByName(a).get(f);d(h)}):d(void 0)}else d(e);},Yl=function(a,b,c){if(Jd()){var d=!I(G.H),e=function(){var f=xi(),h=Wl(a,b,"",c),k=void 0,l=h.Ja._useUp;if(Xl(b,h.Ja)){f(function(){var n=f.getByName(b);n&&(k=n.get("clientId"));
f.remove(b)});f("create",a,h.Ja);d&&I(G.H)&&(d=!1,f(function(){var n=f.getByName(b);!n||n.get("clientId")==k&&l||(h.Ca["&gcu"]="1",n.set(h.Ff),n.send("pageview",h.Ca))}));}};Od(e,G.H);Od(e,G.D)}},em=function(a,b,c){var d="https://www.google-analytics.com/analytics.js",e=zi();if(ua(e)){var f="gtag_"+a.split("-").join("_"),h=function(w){var y=[].slice.call(arguments,0);y[0]=f+"."+y[0];
e.apply(window,y)},k=function(){var w=function(F,D){for(var H=0;D&&H<D.length;H++)h(F,D[H])},y=Zl(b,c);if(y){var A=y.action;if("impressions"===A)w("ec:addImpression",y.Gh);else if("promo_click"===A||"promo_view"===A){var C=y.ie;w("ec:addPromo",y.ie);C&&0<C.length&&"promo_click"===A&&h("ec:setAction",A)}else w("ec:addProduct",y.yb),h("ec:setAction",A,y.Ob)}},l=function(){if(Ch()){}else{var w=c.getWithConfig(G.Jg);w&&
(h("require",w,{dataLayer:"dataLayer"}),h("require","render"))}},n=Wl(a,f,b,c),q=function(w,y,A){A&&(y=""+y);n.Ca[w]=y};Xl(f,n.Ja)&&(e(function(){xi()&&xi().remove(f)}),$l[f]=!1);e("create",a,n.Ja);if(n.Ja._x_19){var p=Oj(n.Ja._x_19,"/analytics.js");p&&(d=p);n.Ja._x_20&&!$l[f]&&($l[f]=!0,e(Ji(f,n.Ja._x_20)))}(function(){var w=c.getWithConfig("custom_map");e(function(){if(Ub(w)){var y=n.Ca,A=xi().getByName(f),C;for(C in w)if(w.hasOwnProperty(C)&&/^(dimension|metric)\d+$/.test(C)&&void 0!=w[C]){var F=
A.get(Ul(w[C]));am(y,C,F)}}})})();(function(w){if(w){var y={};if(Ub(w))for(var A in bm)bm.hasOwnProperty(A)&&cm(bm[A],A,w[A],y);h("require","linkid",y)}})(n.linkAttribution);var r=n[G.za];if(r&&r[G.N]){var t=r[G.rb];Fi(f+".",r[G.N],void 0===t?!!r.use_anchor:"fragment"===t,!!r[G.qb])}h("set",n.Ff);b===G.Eb?(l(),h("send","pageview",n.Ca)):b===G.sa?(l(),Ph(a,c),c.getWithConfig(G.Ha)&&(lh(["aw","dc"]),Gi(f+".")),0!=n.sendPageView&&h("send","pageview",n.Ca),Yl(a,f,c)):b===G.Fa?Vl(f,c):"screen_view"===
b?h("send","screenview",n.Ca):"timing_complete"===b?(q("timingCategory",n.eventCategory,!0),q("timingVar",n.name,!0),q("timingValue",Ia(n.value)),void 0!==n.eventLabel&&q("timingLabel",n.eventLabel,!0),h("send","timing",n.Ca)):"exception"===b?h("send","exception",n.Ca):"optimize.callback"!==b&&(0<=ya([G.kc,"select_content",G.Ea,G.nb,G.ob,G.Ua,"set_checkout_option",G.ia,G.pb,"view_promotion","checkout_progress"],b)&&(h("require","ec","ec.js"),k()),q("eventCategory",n.eventCategory,!0),q("eventAction",
n.eventAction||b,!0),void 0!==n.eventLabel&&q("eventLabel",n.eventLabel,!0),void 0!==n.value&&q("eventValue",Ia(n.value)),h("send","event",n.Ca));var u=!1;var v=dm;u&&(v=c.getContainerTypeLoaded("UA"));if(!v){dm=!0;u&&c.setContainerTypeLoaded("UA",!0);si();var x=function(){u&&c.setContainerTypeLoaded("UA",!1);c.onFailure()},z=function(){xi().loaded||
x()};Ch()?B(z):Eb(d,z,x)}}else B(c.onFailure)},fm=function(a,b,c,d){Vd(function(){em(a,b,d)},[G.H,G.D])},gm=function(a){return I(a)},dm,$l={},Sl={client_id:1,client_storage:"storage",cookie_name:1,cookie_domain:1,cookie_expires:1,cookie_path:1,cookie_update:1,cookie_flags:1,sample_rate:1,site_speed_sample_rate:1,use_amp_client_id:1,store_gac:1,conversion_linker:"storeGac"},hm={anonymize_ip:1},Tl={app_id:1,app_installer_id:1,app_name:1,app_version:1,campaign:{name:"campaignName",source:"campaignSource",
medium:"campaignMedium",term:"campaignKeyword",content:"campaignContent",id:"campaignId"},currency:"currencyCode",description:"exDescription",fatal:"exFatal",language:1,non_interaction:1,page_hostname:"hostname",page_referrer:"referrer",page_path:"page",page_location:"location",page_title:"title",screen_name:1,transport_type:"transport",user_id:1},im={content_id:1,event_category:1,event_action:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1},jm=["item_category",
"item_category2","item_category3","item_category4","item_category5"],bm={cookie_name:1,cookie_expires:"duration",levels:1},km={anonymize_ip:1,fatal:1,non_interaction:1,use_amp_client_id:1,send_page_view:1,store_gac:1,conversion_linker:1},cm=function(a,b,c,d){if(void 0!==c)if(km[b]&&(c=Ja(c)),"anonymize_ip"!==b||c||(c=void 0),1===a)d[Ul(b)]=c;else if(va(a))d[a]=c;else for(var e in a)a.hasOwnProperty(e)&&void 0!==c[e]&&(d[a[e]]=c[e])},Ul=function(a){return a&&va(a)?a.replace(/(_[a-z])/g,function(b){return b[1].toUpperCase()}):
a},lm=function(a){var b="general";0<=ya([G.De,G.nb,G.Ge,G.Ua,"checkout_progress",G.ia,G.pb,G.ob,"set_checkout_option"],a)?b="ecommerce":0<=ya("generate_lead login search select_content share sign_up view_item view_item_list view_promotion view_search_results".split(" "),a)?b="engagement":"exception"===a&&(b="error");return b},am=function(a,b,c){a.hasOwnProperty(b)||(a[b]=c)},mm=function(a){if(xa(a)){for(var b=[],c=0;c<a.length;c++){var d=a[c];if(void 0!=d){var e=d.id,f=d.variant;void 0!=e&&void 0!=
f&&b.push(String(e)+"."+String(f))}}return 0<b.length?b.join("!"):void 0}},Wl=function(a,b,c,d){function e(H,P){void 0!==P&&(l[H]=P)}var f=function(H){return d.getWithConfig(H)},h={},k={},l={},n={},q=mm(f(G.Fg));q&&am(k,"exp",q);Jd()&&(n._cs=gm);var p=f("custom_map");if(Ub(p))for(var r in p)if(p.hasOwnProperty(r)&&/^(dimension|metric)\d+$/.test(r)&&void 0!=p[r]){var t=f(String(p[r]));void 0!==t&&am(k,r,t)}for(var u=ak(d),v=0;v<u.length;++v){var x=u[v],z="developer_id"!=x?f(x):bk(d,x);if(im.hasOwnProperty(x))cm(im[x],
x,z,h);else if(hm.hasOwnProperty(x))cm(hm[x],x,z,l);else if(Tl.hasOwnProperty(x))cm(Tl[x],x,z,k);else if(Sl.hasOwnProperty(x))cm(Sl[x],x,z,n);else if(/^(dimension|metric|content_group)\d+$/.test(x))cm(1,x,z,k);else if("developer_id"===x){var w=cb(z);w&&(k["&did"]=w)}else x===G.ja&&0>ya(u,G.oc)&&(n.cookieName=z+"_ga")}am(n,"cookieDomain","auto");am(l,"forceSSL",!0);am(h,"eventCategory",lm(c));0<=ya(["view_item","view_item_list","view_promotion","view_search_results"],c)&&am(k,"nonInteraction",!0);
"login"===c||"sign_up"===c||"share"===c?am(h,"eventLabel",f(G.Ig)):"search"===c||"view_search_results"===c?am(h,"eventLabel",f(G.Og)):"select_content"===c&&am(h,"eventLabel",f(G.zg));var y=h[G.za]||{},A=y[G.Ya];A||0!=A&&y[G.N]?n.allowLinker=!0:!1===A&&am(n,"useAmpClientId",!1);f(G.Ha)&&(n._useUp=!0);!1!==f(G.yg)&&!1!==f(G.Fb)&&Rl()||(l.allowAdFeatures=!1);if(!1===f(G.va)||!Ql()){var C="allowAdFeatures";C="allowAdPersonalizationSignals";
l[C]=!1}n.name=b;l["&gtm"]=fk(!0);k.hitCallback=d.onSuccess;Jd()&&(l["&gcs"]=Td(),I(G.H)||(n.storage="none"),I(G.D)||(l.allowAdFeatures=!1,n.storeGac=!1));var F=f(G.ka)||f(G.Hg)||rf("gtag.remote_config."+a+".url",2),D=f(G.Gg)||rf("gtag.remote_config."+a+".dualId",2);if(F){n._x_19=F;}D&&
(n._x_20=D);h.Ca=k;h.Ff=l;h.Ja=n;return h},Zl=function(a,b){function c(v){function x(w,y){for(var A=0;A<y.length;A++){var C=y[A];if(v[C]){z[w]=v[C];break}}}var z=E(v);x("listPosition",["list_position"]);x("creative",["creative_name"]);x("list",["list_name"]);x("position",["list_position","creative_slot"]);return z}function d(v){for(var x=[],z=0;v&&z<v.length;z++)v[z]&&x.push(c(v[z]));return x.length?x:void 0}function e(v){return{id:f(G.$a),affiliation:f(G.Cg),revenue:f(G.aa),tax:f(G.Oe),
shipping:f(G.pd),coupon:f(G.Dg),list:f(G.od)||v}}for(var f=function(v){return b.getWithConfig(v)},h=f(G.V),k,l=0;h&&l<h.length&&!(k=h[l][G.od]);l++);var n=f("custom_map");if(Ub(n))for(var q=0;h&&q<h.length;++q){var p=h[q],r;for(r in n)n.hasOwnProperty(r)&&/^(dimension|metric)\d+$/.test(r)&&void 0!=n[r]&&am(p,r,p[n[r]])}var t=null,u=f(G.Eg);a===G.ia||a===G.pb?t={action:a,Ob:e(),yb:d(h)}:a===G.nb?t={action:"add",yb:d(h)}:a===G.ob?t={action:"remove",yb:d(h)}:a===G.Ea?t={action:"detail",Ob:e(k),yb:d(h)}:
a===G.kc?t={action:"impressions",Gh:d(h)}:"view_promotion"===a?t={action:"promo_view",ie:d(u)}:"select_content"===a&&u&&0<u.length?t={action:"promo_click",ie:d(u)}:"select_content"===a?t={action:"click",Ob:{list:f(G.od)||k},yb:d(h)}:a===G.Ua||"checkout_progress"===a?t={action:"checkout",yb:d(h),Ob:{step:a===G.Ua?1:f(G.Ne),option:f(G.Me)}}:"set_checkout_option"===a&&(t={action:"checkout_option",Ob:{step:f(G.Ne),option:f(G.Me)}});t&&(t.Ci=f(G.Z));return t},nm={},Xl=function(a,b){var c=nm[a];nm[a]=E(b);
if(!c)return!1;for(var d in b)if(b.hasOwnProperty(d)&&b[d]!==c[d])return!0;for(var e in c)if(c.hasOwnProperty(e)&&c[e]!==b[e])return!0;return!1};var om=!1;function pm(){var a=Ye;return a.gcq=a.gcq||new qm}
var rm=function(a,b,c){pm().register(a,b,c)},sm=function(a,b,c,d){pm().push("event",[b,a],c,d)},tm=function(a,b){pm().push("config",[a],b)},um=function(a,b,c,d){pm().push("get",[a,b],c,d)},vm={},wm=function(){this.status=1;this.containerConfig={};this.targetConfig={};this.remoteConfig={};this.s={};this.B=null;this.o=!1},xm=function(a,b,c,d,e){this.type=a;this.B=b;this.P=c||"";this.o=d;this.s=e},qm=function(){this.s={};this.B={};this.o=[];this.F={AW:!1,UA:!1};this.enableDeferrableCommandAfterConfig=
om},ym=function(a,b){var c=zh(b);return a.s[c.containerId]=a.s[c.containerId]||new wm},zm=function(a,b,c){if(b){var d=zh(b);if(d&&1===ym(a,b).status){ym(a,b).status=2;var e={};rj&&(e.timeoutId=g.setTimeout(function(){od(38);$i()},3E3));a.push("require",[e],d.containerId);vm[d.containerId]=Pa();if(Ch()){}else{var h="/gtag/js?id="+encodeURIComponent(d.containerId)+"&l=dataLayer&cx=c",k=("http:"!=g.location.protocol?"https:":"http:")+("//www.googletagmanager.com"+h),l=Oj(c,h)||k;Eb(l)}}}},Am=function(a,b,c,d){if(d.P){var e=ym(a,d.P),f=e.B;if(f){var h=E(c),k=E(e.targetConfig[d.P]),l=E(e.containerConfig),n=E(e.remoteConfig),q=E(a.B),p=rf("gtm.uniqueEventId"),r=zh(d.P).prefix,t=Yj(Xj(Zj(Wj(Vj(Uj(Tj(Sj(Rj(h),k),l),n),q),function(){
vj(p,r,"2");}),function(){vj(p,r,"3");}),function(u,v){a.F[u]=v}),function(u){return a.F[u]});try{vj(p,r,"1");f(d.P,b,d.B,t)}catch(u){vj(p,r,"4");}}}};
qm.prototype.register=function(a,b,c){var d=ym(this,a);if(3!==d.status){d.B=b;d.status=3;if(c){E(d.remoteConfig,c);d.remoteConfig=c}var e=zh(a),f=vm[e.containerId];if(void 0!==f){var h=Ye[e.containerId].bootstrap,k=e.prefix.toUpperCase();Ye[e.containerId]._spx&&(k=k.toLowerCase());var l=rf("gtm.uniqueEventId"),n=k,q=Pa()-h;if(rj&&!ej[l]){l!==aj&&(Xi(),aj=l);var p=n+"."+Math.floor(h-
f)+"."+Math.floor(q);ij=ij?ij+","+p:"&cl="+p}delete vm[e.containerId]}this.flush()}};qm.prototype.push=function(a,b,c,d){var e=Math.floor(Pa()/1E3);zm(this,c,b[0][G.ka]||this.B[G.ka]);om&&c&&ym(this,c).o&&(d=!1);this.o.push(new xm(a,e,c,b,d));d||this.flush()};qm.prototype.insert=function(a,b,c){var d=Math.floor(Pa()/1E3);0<this.o.length?this.o.splice(1,0,new xm(a,d,c,b,!1)):this.o.push(new xm(a,d,c,b,!1))};
qm.prototype.flush=function(a){for(var b=this,c=[],d=!1,e={};this.o.length;){var f=this.o[0];if(f.s)om?!f.P||ym(this,f.P).o?(f.s=!1,this.o.push(f)):c.push(f):(f.s=!1,this.o.push(f)),this.o.shift();else{switch(f.type){case "require":if(3!==ym(this,f.P).status&&!a){om&&this.o.push.apply(this.o,c);return}rj&&g.clearTimeout(f.o[0].timeoutId);break;case "set":Fa(f.o[0],function(r,t){E(ab(r,t),b.B)});break;case "config":e.Da={};Fa(f.o[0],function(r){return function(t,u){E(ab(t,u),r.Da)}}(e));var h=!!e.Da[G.Ac];
delete e.Da[G.Ac];var k=ym(this,f.P),l=zh(f.P),n=l.containerId===l.id;h||(n?k.containerConfig={}:k.targetConfig[f.P]={});k.o&&h||Am(this,G.sa,e.Da,f);k.o=!0;delete e.Da[G.Mb];n?E(e.Da,k.containerConfig):E(e.Da,k.targetConfig[f.P]);om&&(d=!0);break;case "event":e.fc={};Fa(f.o[0],function(r){return function(t,u){E(ab(t,u),r.fc)}}(e));Am(this,f.o[1],e.fc,f);break;case "get":var q={},p=(q[G.Qa]=f.o[0],q[G.Pa]=f.o[1],q);Am(this,G.Fa,p,f)}this.o.shift();Bm(this,f)}e={Da:e.Da,fc:e.fc}}om&&(this.o.push.apply(this.o,
c),d&&this.flush())};var Bm=function(a,b){if("require"!==b.type)if(b.P)for(var c=a.getCommandListeners(b.P)[b.type]||[],d=0;d<c.length;d++)c[d]();else for(var e in a.s)if(a.s.hasOwnProperty(e)){var f=a.s[e];if(f&&f.s)for(var h=f.s[b.type]||[],k=0;k<h.length;k++)h[k]()}};qm.prototype.getRemoteConfig=function(a){return ym(this,a).remoteConfig};qm.prototype.getCommandListeners=function(a){return ym(this,a).s};var Cm=function(a,b,c){var d={event:b,"gtm.element":a,"gtm.elementClasses":Qb(a,"className"),"gtm.elementId":a["for"]||Kb(a,"id")||"","gtm.elementTarget":a.formTarget||Qb(a,"target")||""};c&&(d["gtm.triggers"]=c.join(","));d["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||Qb(a,"href")||a.src||a.code||a.codebase||"";return d},Dm=function(a){Ye.hasOwnProperty("autoEventsSettings")||(Ye.autoEventsSettings={});var b=Ye.autoEventsSettings;b.hasOwnProperty(a)||(b[a]=
{});return b[a]},Em=function(a,b,c){Dm(a)[b]=c},Fm=function(a,b,c,d){var e=Dm(a),f=Ua(e,b,d);e[b]=c(f)},Gm=function(a,b,c){var d=Dm(a);return Ua(d,b,c)};var Hm=!!g.MutationObserver,Im=void 0,Jm=function(a){if(!Im){var b=function(){var c=m.body;if(c)if(Hm)(new MutationObserver(function(){for(var e=0;e<Im.length;e++)B(Im[e])})).observe(c,{childList:!0,subtree:!0});else{var d=!1;Ib(c,"DOMNodeInserted",function(){d||(d=!0,B(function(){d=!1;for(var e=0;e<Im.length;e++)B(Im[e])}))})}};Im=[];m.body?b():B(b)}Im.push(a)};var Lm=!1,Mm=[];function Nm(){if(!Lm){Lm=!0;for(var a=0;a<Mm.length;a++)B(Mm[a])}}var Om=function(a){Lm?B(a):Mm.push(a)};Object.freeze({dl:1,id:1});var Pm="HA GF G UA AW DC".split(" "),Qm=!1,Rm={},Sm=!1;function Tm(a,b){var c={event:a};b&&(c.eventModel=E(b),b[G.sd]&&(c.eventCallback=b[G.sd]),b[G.sc]&&(c.eventTimeout=b[G.sc]));return c}function Um(a){a.hasOwnProperty("gtm.uniqueEventId")||Object.defineProperty(a,"gtm.uniqueEventId",{value:lf()});return a["gtm.uniqueEventId"]}
function Vm(){Qm=Qm||!Ye.gtagRegistered,Ye.gtagRegistered=!0,Qm&&(Ye.addTargetToGroup=function(a){Wm(a,"default")});return Qm}var Wm=function(a,b){b=b.toString().split(",");for(var c=0;c<b.length;c++)Rm[b[c]]=Rm[b[c]]||[],Rm[b[c]].push(a)},Xm=function(a){Fa(Rm,function(b,c){var d=ya(c,a);0<=d&&c.splice(d,1)})};
var Ym={config:function(a){var b,c;void 0===c&&(c=lf());if(2>a.length||!va(a[1]))return;var d={};if(2<a.length){if(void 0!=a[2]&&!Ub(a[2])||3<a.length)return;d=a[2]}var e=zh(a[1]);if(!e)return;Xm(e.id);Wm(e.id,d[G.wd]||"default");delete d[G.wd];Sm||od(43);if(Vm()&&-1!==ya(Pm,e.prefix)){"G"===e.prefix&&(d[G.Mb]=!0);tm(d,e.id);return}uf("gtag.targets."+
e.id,void 0);uf("gtag.targets."+e.id,E(d));var f={};f[G.Za]=e.id;b=Tm(G.sa,f);return b},consent:function(a){function b(){Vm()&&E(a[2],{subcommand:a[1]})}if(3===a.length){od(39);var c=lf(),d=a[1];"default"===d?(b(),Rd(a[2])):"update"===d&&(b(),Sd(a[2],c))}},event:function(a){var b=a[1];if(!(2>a.length)&&va(b)){var c;if(2<a.length){if(!Ub(a[2])&&
void 0!=a[2]||3<a.length)return;c=a[2]}var d=Tm(b,c),e=void 0;void 0===e&&lf();var f;var h=c&&c[G.Za];void 0===h&&(h=rf(G.Za,2),void 0===h&&(h="default"));if(va(h)||xa(h)){for(var k=h.toString().replace(/\s+/g,"").split(","),l=[],n=0;n<k.length;n++)0<=k[n].indexOf("-")?l.push(k[n]):l=l.concat(Rm[k[n]]||[]);f=Bh(l)}else f=
void 0;var q=f;if(!q)return;for(var p=Vm(),r=[],t=0;p&&t<q.length;t++){var u=q[t];if(-1!==ya(Pm,u.prefix)){var v=E(c);"G"===u.prefix&&(v[G.Mb]=!0);sm(b,v,u.id)}r.push(u.id)}d.eventModel=d.eventModel||{};0<q.length?d.eventModel[G.Za]=r.join():delete d.eventModel[G.Za];Sm||od(43);return d}},get:function(a){od(53);if(4!==a.length||!va(a[1])||!va(a[2])||!ua(a[3]))return;var b=zh(a[1]),c=String(a[2]),d=a[3];if(!b)return;Sm||od(43);if(!Vm()||-1===
ya(Pm,b.prefix))return;lf();var e={};di(E((e[G.Qa]=c,e[G.Pa]=d,e)));um(c,function(f){B(function(){return d(f)})},b.id);},js:function(a){if(2==a.length&&a[1].getTime){Sm=!0;Vm();var b={event:"gtm.js","gtm.start":a[1].getTime()};return b}},policy:function(){},set:function(a){var b;2==a.length&&Ub(a[1])?b=E(a[1]):3==a.length&&
va(a[1])&&(b={},Ub(a[2])||xa(a[2])?b[a[1]]=E(a[2]):b[a[1]]=a[2]);if(b){if(lf(),Vm()){E(b);var c=E(b);pm().push("set",[c])}b._clear=!0;return b}}},Zm={policy:!0};var $m=function(a,b){var c=a.hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}},dn=function(a){var b=an(),c=b&&b.hide;c&&c.end&&(c[a]=!0)};var vn=function(a){if(un(a))return a;this.o=a};vn.prototype.Eh=function(){return this.o};var un=function(a){return!a||"object"!==Sb(a)||Ub(a)?!1:"getUntrustedUpdateValue"in a};vn.prototype.getUntrustedUpdateValue=vn.prototype.Eh;var wn=[],xn=!1,yn=!1,zn=!1,An=function(a){return g["dataLayer"].push(a)},Bn=function(a){var b=Ye["dataLayer"],c=b?b.subscribers:1,d=0,e=a;return function(){++d===c&&(e(),e=null)}};
function Cn(a){var b=a._clear;Fa(a,function(d,e){"_clear"!==d&&(b&&uf(d,void 0),uf(d,e))});ff||(ff=a["gtm.start"]);var c=a["gtm.uniqueEventId"];if(!a.event)return!1;c||(c=lf(),a["gtm.uniqueEventId"]=c,uf("gtm.uniqueEventId",c));return Mj(a)}function Dn(){var a=wn[0];if(null==a||"object"!==typeof a)return!1;if(a.event)return!0;if(Ga(a)){var b=a[0];if("config"===b||"event"===b||"js"===b)return!0}return!1}
function En(){for(var a=!1;!zn&&0<wn.length;){var b=!1;b=!0;b=!1;b=!0;if(b&&!yn&&Dn()){var c={};wn.unshift((c.event=
"gtm.init",c));yn=!0}var d=!1;d=!0;d=!1;d=!0;if(d&&!xn&&Dn()){var e={};wn.unshift((e.event="gtm.init_consent",e));xn=!0}zn=!0;delete of.eventModel;qf();var f=wn.shift();if(null!=f){var h=un(f);
if(h){var k=f;f=un(k)?k.getUntrustedUpdateValue():void 0;for(var l=["gtm.allowlist","gtm.blocklist","gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],n=0;n<l.length;n++){var q=l[n],p=rf(q,1);if(xa(p)||Ub(p))p=E(p);pf[q]=p}}try{if(ua(f))try{f.call(sf)}catch(y){}else if(xa(f)){var r=f;if(va(r[0])){var t=r[0].split("."),u=t.pop(),v=r.slice(1),x=rf(t.join("."),2);if(void 0!==x&&null!==x)try{x[u].apply(x,v)}catch(y){}}}else{if(Ga(f)){a:{var z=f;if(z.length&&va(z[0])){var w=Ym[z[0]];if(w&&(!h||!Zm[z[0]])){f=
w(z);break a}}f=void 0}if(!f){zn=!1;continue}}a=Cn(f)||a}}finally{h&&qf(!0)}}zn=!1}return!a}
function Fn(){var b=En();try{$m(g["dataLayer"],Xe.M)}catch(c){}return b}
var Hn=function(){var a=yb("dataLayer",[]),b=yb("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};ki(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Om(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||0)+1;var c=a.push;a.push=function(){var e;if(0<Ye.SANDBOXED_JS_SEMAPHORE){e=[];for(var f=0;f<arguments.length;f++)e[f]=new vn(arguments[f])}else e=[].slice.call(arguments,0);var h=c.apply(a,e);wn.push.apply(wn,e);if(300<
this.length)for(od(4);300<this.length;)this.shift();var k="boolean"!==typeof h||h;return En()&&k};var d=a.slice(0);wn.push.apply(wn,d);if(Gn()){B(Fn)}},Gn=function(){var a=!0;return a};var In={};In.Ec=new String("undefined");
var Jn=function(a){this.o=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===In.Ec?b:a[d]);return c.join("")}};Jn.prototype.toString=function(){return this.o("undefined")};Jn.prototype.valueOf=Jn.prototype.toString;In.ah=Jn;In.Kd={};In.rh=function(a){return new Jn(a)};var Kn={};In.ci=function(a,b){var c=lf();Kn[c]=[a,b];return c};In.Bf=function(a){var b=a?0:1;return function(c){var d=Kn[c];if(d&&"function"===typeof d[b])d[b]();Kn[c]=void 0}};In.Jh=function(a){for(var b=!1,c=!1,d=2;d<a.length;d++)b=
b||8===a[d],c=c||16===a[d];return b&&c};In.Xh=function(a){if(a===In.Ec)return a;var b=lf();In.Kd[b]=a;return'google_tag_manager["'+Xe.M+'"].macro('+b+")"};In.Th=function(a,b,c){a instanceof In.ah&&(a=a.o(In.ci(b,c)),b=ta);return{Fh:a,onSuccess:b}};var Ln=["input","select","textarea"],Mn=["button","hidden","image","reset","submit"],Nn=function(a){var b=a.tagName.toLowerCase();return!za(Ln,function(c){return c===b})||"input"===b&&za(Mn,function(c){return c===a.type.toLowerCase()})?!1:!0},On=function(a){return a.form?a.form.tagName?a.form:m.getElementById(a.form):Ob(a,["form"],100)},Pn=function(a,b,c){if(!a.elements)return 0;for(var d=b.dataset[c],e=0,f=1;e<a.elements.length;e++){var h=a.elements[e];if(Nn(h)){if(h.dataset[c]===d)return f;f++}}return 0};var $n=g.clearTimeout,ao=g.setTimeout,J=function(a,b,c){if(Ch()){b&&B(b)}else return Eb(a,b,c)},bo=function(){return new Date},co=function(){return g.location.href},eo=function(a){return ne(pe(a),"fragment")},fo=function(a){return oe(pe(a))},go=function(a,b){return rf(a,b||2)},ho=function(a,b,c){var d;b?(a.eventCallback=b,c&&(a.eventTimeout=c),d=An(a)):d=An(a);return d},io=function(a,b){g[a]=b},L=function(a,b,c){b&&
(void 0===g[a]||c&&!g[a])&&(g[a]=b);return g[a]},jo=function(a,b,c){return Hf(a,b,void 0===c?!0:!!c)},ko=function(a,b,c){return 0===Qf(a,b,c)},lo=function(a,b){if(Ch()){b&&B(b)}else Gb(a,b)},mo=function(a){return!!Gm(a,"init",!1)},no=function(a){Em(a,"init",!0)},oo=function(a){var b=df+"?id="+encodeURIComponent(a)+"&l=dataLayer";J(Eh("https://","http://",b))},po=function(a,b,c){rj&&(Vb(a)||wj(c,b,a))};var qo=In.Th;function No(a,b){a=String(a);b=String(b);var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var Oo=new Ca;function Po(a,b,c){var d=c?"i":void 0;try{var e=String(b)+d,f=Oo.get(e);f||(f=new RegExp(b,d),Oo.set(e,f));return f.test(a)}catch(h){return!1}}
function Qo(a,b){function c(h){var k=pe(h),l=ne(k,"protocol"),n=ne(k,"host",!0),q=ne(k,"port"),p=ne(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==q||"https"==l&&"443"==q)l="web",q="default";return[l,n,q,p]}for(var d=c(String(a)),e=c(String(b)),f=0;f<d.length;f++)if(d[f]!==e[f])return!1;return!0}
function Ro(a){return So(a)?1:0}
function So(a){var b=a.arg0,c=a.arg1;if(a.any_of&&xa(c)){for(var d=0;d<c.length;d++){var e=E(a,{});E({arg1:c[d],any_of:void 0},e);if(Ro(e))return!0}return!1}switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var f;a:{if(b){var h=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var k=0;k<h.length;k++)if(b[h[k]]){f=b[h[k]](c);break a}}catch(n){}}f=!1}return f;case "_ew":return No(b,c);case "_eq":return String(b)==
String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var l;l=String(b).split(",");return 0<=ya(l,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":return Po(b,c,a.ignore_case);case "_sw":return 0==String(b).indexOf(String(c));case "_um":return Qo(b,c)}return!1};var To=encodeURI,R=encodeURIComponent,Uo=Hb;var Vo=function(a,b){if(!a)return!1;var c=ne(pe(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var Wo=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};function Dq(){return g.gaGlobal=g.gaGlobal||{}}var Eq=function(){var a=Dq();a.hid=a.hid||Ba();return a.hid},Fq=function(a,b){var c=Dq();if(void 0==c.vid||b&&!c.from_cookie)c.vid=a,c.from_cookie=b};var cr=function(){if(ua(g.__uspapi)){var a="";try{g.__uspapi("getUSPData",1,function(b,c){if(c&&b){var d=b.uspString;d&&/^[\da-zA-Z-]{1,20}$/.test(d)&&(a=d)}})}catch(b){}return a}};var xr=window,yr=document,zr=function(a){var b=xr._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===xr["ga-disable-"+a])return!0;try{var c=xr.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(f){}for(var d=Df("AMP_TOKEN",String(yr.cookie),!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return yr.getElementById("__gaOptOutExtension")?!0:!1};var Ar={};
function Dr(a){delete a.eventModel[G.Mb];Fr(a.eventModel)}var Fr=function(a){Fa(a,function(c){"_"===c.charAt(0)&&delete a[c]});var b=a[G.Ia]||{};Fa(b,function(c){"_"===c.charAt(0)&&delete b[c]})};var Ir=function(a,b,c){sm(b,c,a)},Jr=function(a,b,c){sm(b,c,a,!0)},Lr=function(a,b){};
function Kr(a,b){}var V={g:{}};

V.g.e=["google"],function(){(function(a){V.__e=a;V.__e.h="e";V.__e.m=!0;V.__e.priorityOverride=0})(function(a){var b=String(xf(a.vtp_gtmEventId,"event"));a.vtp_gtmCachedValues&&(b=String(a.vtp_gtmCachedValues.event));return b})}();

V.g.v=["google"],function(){(function(a){V.__v=a;V.__v.h="v";V.__v.m=!0;V.__v.priorityOverride=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=go(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1),d=void 0!==c?c:a.vtp_defaultValue;po(d,"v",a.vtp_gtmEventId);return d})}();
V.g.rep=["google"],function(){(function(a){V.__rep=a;V.__rep.h="rep";V.__rep.m=!0;V.__rep.priorityOverride=0})(function(a){var b;switch(zh(a.vtp_containerId).prefix){case "AW":b=ml;break;case "DC":b=Cl;break;case "GF":b=Hl;break;case "HA":b=Ml;break;case "UA":b=fm;break;default:B(a.vtp_gtmOnFailure);return}B(a.vtp_gtmOnSuccess);rm(a.vtp_containerId,b,a.vtp_remoteConfig||{})})}();



V.g.cid=["google"],function(){(function(a){V.__cid=a;V.__cid.h="cid";V.__cid.m=!0;V.__cid.priorityOverride=0})(function(){return Xe.M})}();





V.g.get=["google"],function(){(function(a){V.__get=a;V.__get.h="get";V.__get.m=!0;V.__get.priorityOverride=0})(function(a){var b=a.vtp_settings;(a.vtp_deferrable?Jr:Ir)(String(b.streamId),String(a.vtp_eventName),b.eventParameters||{});a.vtp_gtmOnSuccess()})}();









V.g.gtagua=["google"],function(){(function(a){V.__gtagua=a;V.__gtagua.h="gtagua";V.__gtagua.m=!0;V.__gtagua.priorityOverride=0})(function(a){B(a.vtp_gtmOnSuccess)})}();


var Vr={};Vr.macro=function(a){if(In.Kd.hasOwnProperty(a))return In.Kd[a]},Vr.onHtmlSuccess=In.Bf(!0),Vr.onHtmlFailure=In.Bf(!1);Vr.dataLayer=sf;Vr.callback=function(a){jf.hasOwnProperty(a)&&ua(jf[a])&&jf[a]();delete jf[a]};Vr.bootstrap=0;Vr._spx=!1;function Wr(){Ye[Xe.M]=Vr;Ya(kf,V.g);Fc=Fc||In;Gc=Oc}
function Xr(){var a=!1;a&&ti("INIT");xd.s().s();Ye=g.google_tag_manager=g.google_tag_manager||{};Ik();
Og.enable_gbraid_cookie_write=!0;if(Ye[Xe.M]){var b=Ye.zones;b&&b.unregisterChild(Xe.M);}else{for(var c=data.resource||{},d=c.macros||[],e=0;e<d.length;e++)yc.push(d[e]);for(var f=c.tags||[],h=0;h<f.length;h++)Bc.push(f[h]);for(var k=c.predicates||[],l=0;l<k.length;l++)Ac.push(k[l]);for(var n=c.rules||[],q=0;q<n.length;q++){for(var p=n[q],r={},t=
0;t<p.length;t++)r[p[t][0]]=Array.prototype.slice.call(p[t],1);zc.push(r)}Dc=V;Ec=Ro;Wr();Hn();fi=!1;gi=0;if("interactive"==m.readyState&&!m.createEventObject||"complete"==m.readyState)ii();else{Ib(m,"DOMContentLoaded",ii);Ib(m,"readystatechange",ii);if(m.createEventObject&&m.documentElement.doScroll){var u=!0;try{u=!g.frameElement}catch(y){}u&&ji()}Ib(g,"load",ii)}Lm=!1;"complete"===m.readyState?Nm():Ib(g,"load",Nm);rj&&g.setInterval(nj,864E5);gf=(new Date).getTime();Vr.bootstrap=
gf;if(a){var w=ui("INIT");}}}
(function(a){if(!g["__TAGGY_INSTALLED"]){var b=!1;if(m.referrer){var c=pe(m.referrer);b="cct.google"===me(c,"host")}if(!b){var d=Hf("googTaggyReferrer");b=d.length&&d[0].length}b&&(g["__TAGGY_INSTALLED"]=!0,Eb("https://cct.google/taggy/agent.js"))}var f=function(){var n=g["google.tagmanager.debugui2.queue"];n||(n=[],g["google.tagmanager.debugui2.queue"]=n,Eb("https://www.googletagmanager.com/debug/bootstrap"));var q={messageType:"CONTAINER_STARTING",data:{scriptSource:xb,containerProduct:"GTM",debug:!1}};q.data.resume=function(){a()};q.data.containerProduct=
"OGT";Xe.ig&&(q.data.initialPublish=!0);n.push(q)},h="x"===ne(g.location,"query",!1,void 0,"gtm_debug");if(!h&&m.referrer){var k=pe(m.referrer);h="tagassistant.google.com"===me(k,"host")}if(!h){var l=Hf("__TAG_ASSISTANT");h=l.length&&l[0].length}g.__TAG_ASSISTANT_API&&(h=!0);h&&xb?f():a()})(Xr);

})()
