%YAML:1.0

# path
sequence_dir: ../datasets/MH_01_easy/mav0/
imu_path: ../datasets/MH_01_easy/mav0/imu0/data.txt
camera_path: ../datasets/MH_01_easy/mav0/cam0/data.txt

# Sensor extrinsics wrt. the body-frame.
T_BS: "0.0148655429818 -0.999880929698 0.00414029679422 -0.0216401454975 0.999557249008 0.0149672133247 0.025715529948 -0.064676986768 -0.0257744366974 0.00375618835797 0.999660727178 0.00981073058949 0.0 0.0 0.0 1.0"

# Camera specific definitions.
# intrinsics
Camera.fx: 458.654
Camera.fy: 457.296
Camera.cx: 367.215
Camera.cy: 248.375

# distortion_coefficients
Camera.k1: -0.28340811
Camera.k2: 0.07395907
Camera.p1: 0.00019359
Camera.p2: 1.76187114e-05

sigma_img: 0.1

# inertial sensor noise model parameters (static)
gyroscope_noise_density: 1.6968e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
gyroscope_random_walk: 1.9393e-05       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
accelerometer_noise_density: 2.0000e-3  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
accelerometer_random_walk: 3.0000e-3    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
g: 9.81

#--------------------------------------------------------------------------------------------
# goodFeaturesToTrack Params
#--------------------------------------------------------------------------------------------

Shi-Tomasi.maxCorners: 200
Shi-Tomasi.qualityLevel: 0.01
Shi-Tomasi.minDistance: 20
Shi-Tomasi.blockSize: 10
Shi-Tomasi.useHarrisDetector: false
Shi-Tomasi.k: 0.04
Shi-Tomasi.maxLifeTime: 15 




#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image, only use when reset
ORBextractor.nFeaturesInit: 1000

# ORB Extractor: Number of features per image 
ORBextractor.nFeatures: 600

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 4

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFASTs		
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7



