// Generated by gencpp from file msckf_vio/GPSMeasurement.msg
// DO NOT EDIT!


#ifndef MSCKF_VIO_MESSAGE_GPSMEASUREMENT_H
#define MSCKF_VIO_MESSAGE_GPSMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msckf_vio
{
template <class ContainerAllocator>
struct GPSMeasurement_
{
  typedef GPSMeasurement_<ContainerAllocator> Type;

  GPSMeasurement_()
    : header()
    , px(0.0)
    , py(0.0)
    , pz(0.0)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)  {
    }
  GPSMeasurement_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , px(0.0)
    , py(0.0)
    , pz(0.0)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _px_type;
  _px_type px;

   typedef double _py_type;
  _py_type py;

   typedef double _pz_type;
  _pz_type pz;

   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _vz_type;
  _vz_type vz;





  typedef boost::shared_ptr< ::msckf_vio::GPSMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msckf_vio::GPSMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct GPSMeasurement_

typedef ::msckf_vio::GPSMeasurement_<std::allocator<void> > GPSMeasurement;

typedef boost::shared_ptr< ::msckf_vio::GPSMeasurement > GPSMeasurementPtr;
typedef boost::shared_ptr< ::msckf_vio::GPSMeasurement const> GPSMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msckf_vio::GPSMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msckf_vio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'msckf_vio': ['/home/zhouyuxuan/catkin_ws_testfield/src/msckf_vio_GPS/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msckf_vio::GPSMeasurement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msckf_vio::GPSMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msckf_vio::GPSMeasurement_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ca14ca7a467f72d03fec070f1f4c94e";
  }

  static const char* value(const ::msckf_vio::GPSMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ca14ca7a467f72dULL;
  static const uint64_t static_value2 = 0x03fec070f1f4c94eULL;
};

template<class ContainerAllocator>
struct DataType< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msckf_vio/GPSMeasurement";
  }

  static const char* value(const ::msckf_vio::GPSMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
float64 px\n\
float64 py\n\
float64 pz\n\
float64 vx\n\
float64 vy\n\
float64 vz\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::msckf_vio::GPSMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.px);
      stream.next(m.py);
      stream.next(m.pz);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPSMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msckf_vio::GPSMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msckf_vio::GPSMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "px: ";
    Printer<double>::stream(s, indent + "  ", v.px);
    s << indent << "py: ";
    Printer<double>::stream(s, indent + "  ", v.py);
    s << indent << "pz: ";
    Printer<double>::stream(s, indent + "  ", v.pz);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSCKF_VIO_MESSAGE_GPSMEASUREMENT_H
