
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"1",
  
  "macros":[{"function":"__e"},{"function":"__cid"}],
  "tags":[{"function":"__rep","once_per_event":true,"vtp_containerId":["macro",1],"tag_id":1}],
  "predicates":[{"function":"_eq","arg0":["macro",0],"arg1":"gtm.js"}],
  "rules":[[["if",0],["add",0]]]
},
"runtime":[]




};


/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ea="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=fa,ma=function(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.wj=b.prototype},na=this||self,oa=function(a){return a};var pa=function(){},ra=function(a){return"function"==typeof a},sa=function(a){return"string"==typeof a},ta=function(a){return"number"==typeof a&&!isNaN(a)},ua=Array.isArray,va=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},wa=function(a,b){if(a&&ua(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},xa=function(a,b){if(!ta(a)||!ta(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-
a+1)+a)},za=function(a,b){for(var c=new ya,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},Aa=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},Da=function(a){return!!a&&("[object Arguments]"==Object.prototype.toString.call(a)||Object.prototype.hasOwnProperty.call(a,"callee"))},Ea=function(a){return Math.round(Number(a))||0},Fa=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Ia=function(a){var b=[];if(ua(a))for(var c=
0;c<a.length;c++)b.push(String(a[c]));return b},La=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},Oa=function(){return new Date(Date.now())},h=function(){return Oa().getTime()},ya=function(){this.prefix="gtm.";this.values={}};ya.prototype.set=function(a,b){this.values[this.prefix+a]=b};ya.prototype.get=function(a){return this.values[this.prefix+a]};
var Pa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Qa=function(a){var b=a;return function(){if(b){var c=b;b=void 0;try{c()}catch(d){}}}},Ra=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Sa=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},Ta=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Ua=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},Va=/^\w{1,9}$/,
Wa=function(a,b){a=a||{};b=b||",";var c=[];Aa(a,function(d,e){Va.test(d)&&e&&c.push(d)});return c.join(b)};var Xa,Ya=function(){if(void 0===Xa){var a=null,b=na.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:oa,createScript:oa,createScriptURL:oa})}catch(c){na.console&&na.console.error(c.message)}Xa=a}else Xa=a}return Xa};var $a=function(a,b){this.m=b===Za?a:""};$a.prototype.toString=function(){return this.m+""};var Za={},ab=function(a){var b=Ya(),c=b?b.createScriptURL(a):a;return new $a(c,Za)};var bb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var cb;a:{var gb=na.navigator;if(gb){var hb=gb.userAgent;if(hb){cb=hb;break a}}cb=""}function ib(a){return-1!=cb.indexOf(a)};var jb={},kb=function(a,b,c){this.m=c===jb?a:""};kb.prototype.toString=function(){return this.m.toString()};var mb=function(a){return a instanceof kb&&a.constructor===kb?a.m:"type_error:SafeHtml"},nb=function(a){var b=Ya(),c=b?b.createHTML(a):a;return new kb(c,null,jb)},ob=new kb(na.trustedTypes&&na.trustedTypes.emptyHTML||"",0,jb);/*

 SPDX-License-Identifier: Apache-2.0
*/
function pb(a,b){a.src=b instanceof $a&&b.constructor===$a?b.m:"type_error:TrustedResourceUrl";var c,d,e=(a.ownerDocument&&a.ownerDocument.defaultView||window).document,f=null===(d=e.querySelector)||void 0===d?void 0:d.call(e,"script[nonce]");(c=f?f.nonce||f.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};var qb=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d},rb=function(a){var b=a;return function(){if(b){var c=b;b=null;c()}}};var sb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);var c=a.firstChild.firstChild;a.innerHTML=mb(ob);return!c.parentElement});var m=window,B=document,tb=navigator,ub=B.currentScript&&B.currentScript.src,vb=function(a,b){var c=m[a];m[a]=void 0===c?b:c;return m[a]},wb=function(a){var b=B.getElementsByTagName("script")[0]||B.body||B.head;b.parentNode.insertBefore(a,b)},xb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},yb={async:1,nonce:1,onerror:1,onload:1,src:1,type:1},zb=function(a,b,c,d){var e=B.createElement("script");
d&&Aa(d,function(f,g){f=f.toLowerCase();yb.hasOwnProperty(f)||e.setAttribute(f,g)});e.type="text/javascript";e.async=!0;pb(e,ab(a));xb(e,b);c&&(e.onerror=c);wb(e);return e},Ab=function(){if(ub){var a=ub.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},Bb=function(a,b){var c=B.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=B.body&&B.body.lastChild||B.body||B.head;d.parentNode.insertBefore(c,
d);xb(c,b);void 0!==a&&(c.src=a);return c},Cb=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},Db=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},Eb=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},G=function(a){m.setTimeout(a,0)},Fb=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:
null},Gb=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Hb=function(a){var b=B.createElement("div"),c=nb("A<div>"+a+"</div>"),d=b;if(sb())for(;d.lastChild;)d.removeChild(d.lastChild);d.innerHTML=mb(c);b=b.lastChild;for(var e=[];b.firstChild;)e.push(b.removeChild(b.firstChild));return e},Jb=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var f=a,g=0;f&&g<=c;g++){if(d[String(f.tagName).toLowerCase()])return f;
f=f.parentElement}return null},Kb=function(a){var b;try{b=tb.sendBeacon&&tb.sendBeacon(a)}catch(c){}b||Cb(a)},Lb=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c},Mb=function(a){var b=B.featurePolicy;return b&&ra(b.features)?-1!==b.features().indexOf(a):!1},Nb=function(){return tb.userLanguage||tb.language};/*
 jQuery (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ob=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Pb=function(a){if(null==a)return String(a);var b=Ob.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Qb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Rb=function(a){if(!a||"object"!=Pb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Qb(a,"constructor")&&!Qb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Qb(a,b)},H=function(a,b){var c=b||("array"==Pb(a)?[]:{}),d;for(d in a)if(Qb(a,d)){var e=a[d];"array"==Pb(e)?("array"!=Pb(c[d])&&(c[d]=[]),c[d]=H(e,c[d])):Rb(e)?(Rb(c[d])||(c[d]={}),c[d]=H(e,c[d])):c[d]=e}return c};var Sb=function(a){if(void 0===a||ua(a)||Rb(a))return!0;switch(typeof a){case "boolean":case "number":case "string":case "function":return!0}return!1};var Tb=function(){var a=function(b){return{toString:function(){return b}}};return{Ng:a("consent"),Og:a("consent_always_fire"),Re:a("convert_case_to"),Se:a("convert_false_to"),Te:a("convert_null_to"),Ue:a("convert_true_to"),Ve:a("convert_undefined_to"),gj:a("debug_mode_metadata"),jj:a("event_data_overrides"),lb:a("function"),Ch:a("instance_name"),Eh:a("live_only"),Fh:a("malware_disabled"),Gh:a("metadata"),kj:a("original_activity_id"),lj:a("original_vendor_template_id"),Kh:a("once_per_event"),Bf:a("once_per_load"),
nj:a("priority_override"),oj:a("respected_consent_types"),Ff:a("setup_tags"),Hf:a("tag_id"),If:a("teardown_tags")}}();var zc;
var Ac=[],Bc=[],Cc=[],Dc=[],Ec=[],Fc={},Gc,Hc,Ic,Jc=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=Fc[c],e={},f;for(f in a)if(a.hasOwnProperty(f))if(0===f.indexOf("vtp_"))d&&b&&b.Tf&&b.Tf(a[f]),e[void 0!==d?f:f.substr(4)]=a[f];else if(f===Tb.Og.toString()&&a[f]){}
d&&b&&b.Sf&&(e.vtp_gtmCachedValues=b.Sf);return void 0!==d?d(e):zc(c,e,b)},Lc=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Kc(a[e],b,c));return d},Kc=function(a,b,c){if(ua(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Kc(a[e],b,c));return d;case "macro":var f=a[1];if(c[f])return;var g=Ac[f];if(!g||b.Be(g))return;c[f]=!0;try{var k=Lc(g,b,c);k.vtp_gtmEventId=b.id;
d=Jc(k,b);Ic&&(d=Ic.Yh(d,k))}catch(z){b.jg&&b.jg(z,Number(f)),d=!1}c[f]=!1;return d;case "map":d={};for(var l=1;l<a.length;l+=2)d[Kc(a[l],b,c)]=Kc(a[l+1],b,c);return d;case "template":d=[];for(var n=!1,p=1;p<a.length;p++){var q=Kc(a[p],b,c);Hc&&(n=n||q===Hc.Wc);d.push(q)}return Hc&&n?Hc.bi(d):d.join("");case "escape":d=Kc(a[1],b,c);if(Hc&&ua(a[1])&&"macro"===a[1][0]&&Hc.yi(a))return Hc.Ni(d);d=String(d);for(var u=2;u<a.length;u++)Ub[a[u]]&&(d=Ub[a[u]](d));return d;case "tag":var t=a[1];if(!Dc[t])throw Error("Unable to resolve tag reference "+
t+".");return d={$f:a[2],index:t};case "zb":var r={arg0:a[2],arg1:a[3],ignore_case:a[5]};r["function"]=a[1];var v=Pc(r,b,c),x=!!a[4];return x||2!==v?x!==(1===v):null;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Pc=function(a,b,c){try{return Gc(Lc(a,b,c))}catch(d){JSON.stringify(a)}return 2};var Sc=function(a){function b(u){for(var t=0;t<u.length;t++)d[u[t]]=!0}for(var c=[],d=[],e=Qc(a),f=0;f<Bc.length;f++){var g=Bc[f],k=Rc(g,e);if(k){for(var l=g.add||[],n=0;n<l.length;n++)c[l[n]]=!0;b(g.block||[])}else null===k&&b(g.block||[]);}for(var p=[],q=0;q<Dc.length;q++)c[q]&&!d[q]&&(p[q]=!0);return p},Rc=function(a,b){for(var c=a["if"]||[],d=0;d<c.length;d++){var e=b(c[d]);if(0===e)return!1;if(2===e)return null}for(var f=
a.unless||[],g=0;g<f.length;g++){var k=b(f[g]);if(2===k)return null;if(1===k)return!1}return!0},Qc=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=Pc(Cc[c],a));return b[c]}};var Tc={Yh:function(a,b){b[Tb.Re]&&"string"===typeof a&&(a=1==b[Tb.Re]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(Tb.Te)&&null===a&&(a=b[Tb.Te]);b.hasOwnProperty(Tb.Ve)&&void 0===a&&(a=b[Tb.Ve]);b.hasOwnProperty(Tb.Ue)&&!0===a&&(a=b[Tb.Ue]);b.hasOwnProperty(Tb.Se)&&!1===a&&(a=b[Tb.Se]);return a}};
var M={bc:"_ee",bd:"_syn_or_mod",pj:"_uei",Wd:"_eu",mj:"_pci",Cb:"event_callback",Mc:"event_timeout",ya:"gtag.config",Ha:"gtag.get",ra:"purchase",Ab:"refund",eb:"begin_checkout",yb:"add_to_cart",zb:"remove_from_cart",Xg:"view_cart",Xe:"add_to_wishlist",sa:"view_item",fb:"view_promotion",Hc:"select_promotion",zd:"select_item",Sa:"view_item_list",We:"add_payment_info",Wg:"add_shipping_info",Ja:"value_key",Ta:"value_callback",za:"allow_ad_personalization_signals",Xb:"restricted_data_processing",Sb:"allow_google_signals",
Ca:"cookie_expires",Ub:"cookie_update",Zb:"session_duration",Qc:"session_engaged_time",Ka:"user_properties",na:"transport_url",R:"ads_data_redaction",va:"user_data",Vb:"first_party_collection",C:"ad_storage",H:"analytics_storage",Pe:"region",Qe:"wait_for_update",Ba:"conversion_linker",Aa:"conversion_cookie_prefix",ca:"value",ba:"currency",xf:"trip_type",V:"items",qf:"passengers",Cd:"allow_custom_scripts",$b:"session_id",vf:"quantity",Wa:"transaction_id",jb:"language",Kc:"country",Ic:"allow_enhanced_conversions",
Hd:"aw_merchant_id",Fd:"aw_feed_country",Gd:"aw_feed_language",Ed:"discount",aa:"developer_id",Rc:"delivery_postal_code",Nd:"estimated_delivery_date",Ld:"shipping",Sd:"new_customer",Id:"customer_lifetime_value",Md:"enhanced_conversions",Rb:"page_view",ma:"linker",M:"domains",Fb:"decorate_forms",lf:"enhanced_conversions_automatic_settings",gh:"auto_detection_enabled",nf:"ga_temp_client_id",Ad:"user_engagement",Rg:"app_remove",Sg:"app_store_refund",Tg:"app_store_subscription_cancel",Ug:"app_store_subscription_convert",
Vg:"app_store_subscription_renew",Yg:"first_open",Zg:"first_visit",$g:"in_app_purchase",ah:"session_start",bh:"user_data_login",dh:"user_data_logout",eh:"allow_display_features",Tb:"campaign",Ze:"campaign_content",$e:"campaign_id",af:"campaign_medium",bf:"campaign_name",cf:"campaign_source",df:"campaign_term",Bb:"client_id",ka:"cookie_domain",Jc:"cookie_name",hb:"cookie_path",Ia:"cookie_flags",ef:"custom_map",Pd:"groups",ij:"non_interaction",Gb:"page_location",pf:"page_path",Va:"page_referrer",Td:"page_title",
Yb:"send_page_view",kb:"send_to",Ud:"session_engaged",Oc:"_logged_in_state",Vd:"session_number",yh:"tracking_id",Xa:"url_passthrough",Eb:"accept_incoming",Wb:"url_position",tf:"phone_conversion_number",rf:"phone_conversion_callback",sf:"phone_conversion_css_class",uf:"phone_conversion_options",uh:"phone_conversion_ids",th:"phone_conversion_country_code",Ye:"aw_remarketing",Dd:"aw_remarketing_only",Bd:"gclid",fh:"auid",lh:"affiliation",kf:"tax",Kd:"list_name",jf:"checkout_step",hf:"checkout_option",
mh:"coupon",nh:"promotions",Hb:"user_id",vh:"retoken",la:"cookie_prefix",ff:"disable_merchant_reported_purchases",kh:"dc_natural_search",jh:"dc_custom_params",rh:"method",xh:"search_term",ih:"content_type",sh:"optimize_id",oh:"experiments",Ua:"google_signals",Nc:"google_tld",Sc:"update",Od:"firebase_id",Db:"ga_restrict_domain",Lc:"event_settings",Jd:"dynamic_event_settings",ac:"user_data_settings",wh:"screen_name",qh:"_x_19",ib:"_ecid",ph:"_x_20",Rd:"internal_traffic_results",wf:"traffic_type",Pc:"referral_exclusion_definition",
Qd:"ignore_referrer",hh:"content_group"};var wd={};M.zf=Object.freeze((wd[M.We]=1,wd[M.Wg]=1,wd[M.yb]=1,wd[M.zb]=1,wd[M.Xg]=1,wd[M.eb]=1,wd[M.zd]=1,wd[M.Sa]=1,wd[M.Hc]=1,wd[M.fb]=1,wd[M.ra]=1,wd[M.Ab]=1,wd[M.sa]=1,wd[M.Xe]=1,wd));M.Yd=Object.freeze([M.za,M.Sb,M.Ub]);M.Ih=Object.freeze([].concat(M.Yd));M.Zd=Object.freeze([M.Ca,M.Mc,M.Zb,M.Qc]);M.Jh=Object.freeze([].concat(M.Zd));
var yd={},zd=function(a,b){yd[a]=yd[a]||[];yd[a][b]=!0},Ad=function(a){for(var b=[],c=yd[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};var Bd=function(a){zd("GTM",a)};var Cd=function(a){this.m=a;this.defaultValue=!1};var Dd=new Cd(1933),Ed=new Cd(1956);var Gd=function(){var a=Fd,b="ze";if(a.ze&&a.hasOwnProperty(b))return a.ze;var c=new a;a.ze=c;a.hasOwnProperty(b);return c};var Fd=function(){var a={};this.m=function(b,c){return null!=a[b]?a[b]:c};this.o=function(){a[Dd.m]=!0}},Hd=function(a){return Gd().m(a.m,a.defaultValue)};var Id=[];function Jd(){var a=vb("google_tag_data",{});a.ics||(a.ics={entries:{},set:Kd,update:Rd,addListener:Sd,notifyListeners:Td,active:!1,usedDefault:!1});return a.ics}
function Kd(a,b,c,d,e,f){var g=Jd();g.active=!0;g.usedDefault=!0;if(void 0!=b){var k=g.entries,l=k[a]||{},n=l.region,p=c&&sa(c)?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(""===d||p===e||(p===d?n!==e:!p&&!n)){var q=!!(f&&0<f&&void 0===l.update),u={region:p,initial:"granted"===b,update:l.update,quiet:q};if(""!==d||!1!==l.initial)k[a]=u;q&&m.setTimeout(function(){k[a]===u&&u.quiet&&(u.quiet=!1,Ud(a),Td(),zd("TAGGING",2))},f)}}}
function Rd(a,b){var c=Jd();c.active=!0;if(void 0!=b){var d=Vd(a),e=c.entries,f=e[a]=e[a]||{};f.update="granted"===b;var g=Vd(a);f.quiet?(f.quiet=!1,Ud(a)):g!==d&&Ud(a)}}function Sd(a,b){Id.push({pe:a,ki:b})}function Ud(a){for(var b=0;b<Id.length;++b){var c=Id[b];ua(c.pe)&&-1!==c.pe.indexOf(a)&&(c.og=!0)}}function Td(a){for(var b=0;b<Id.length;++b){var c=Id[b];if(c.og){c.og=!1;try{c.ki({consentEventId:a})}catch(d){}}}}
var Vd=function(a){var b=Jd().entries[a]||{};return void 0!==b.update?b.update:b.initial},Wd=function(a){return(Jd().entries[a]||{}).initial},Xd=function(a){return!(Jd().entries[a]||{}).quiet},Yd=function(){return Hd(Dd)?Jd().active:!1},Zd=function(){return Jd().usedDefault},$d=function(a,b){Jd().addListener(a,b)},ae=function(a){Jd().notifyListeners(a)},be=function(a,b){function c(){for(var e=0;e<b.length;e++)if(!Xd(b[e]))return!0;return!1}if(c()){var d=!1;$d(b,function(e){d||c()||(d=!0,a(e))})}else a({})},
ce=function(a,b){function c(){for(var f=[],g=0;g<d.length;g++){var k=d[g];!1===Vd(k)||e[k]||(f.push(k),e[k]=!0)}return f}var d=sa(b)?[b]:b,e={};c().length!==d.length&&$d(d,function(f){var g=c();0<g.length&&(f.pe=g,a(f))})};function de(a){for(var b=[],c=0;c<ee.length;c++){var d=a(ee[c]);b[c]=!0===d?"1":!1===d?"0":"-"}return b.join("")}
var ee=[M.C,M.H],fe=function(a){var b=a[M.Pe];b&&Bd(40);var c=a[M.Qe];c&&Bd(41);for(var d=ua(b)?b:[b],e={Ob:0};e.Ob<d.length;e={Ob:e.Ob},++e.Ob)Aa(a,function(f){return function(g,k){if(g!==M.Pe&&g!==M.Qe){var l=d[f.Ob];Jd().set(g,k,l,"SG","",c)}}}(e))},ge=0,he=function(a,b){Aa(a,function(e,f){Jd().update(e,f)});ae(b);var c=h(),d=c-ge;ge&&0<=d&&1E3>d&&Bd(66);ge=c},ie=function(a){var b=Vd(a);return void 0!=b?b:!0},je=function(){return"G1"+de(Vd)},ke=function(){return"G1"+
de(Wd)},le=function(a,b){ce(a,b)},me=function(a,b){be(a,b)};var oe=function(a){return ne?B.querySelectorAll(a):null},pe=function(a,b){if(!ne)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!B.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},qe=!1;if(B.querySelectorAll)try{var re=B.querySelectorAll(":root");re&&1==re.length&&re[0]==B.documentElement&&(qe=!0)}catch(a){}var ne=qe;var Le=function(){this.eventModel={};this.targetConfig={};this.containerConfig={};this.globalConfig={};this.remoteConfig={};this.onSuccess=function(){};this.onFailure=function(){};this.setContainerTypeLoaded=function(){};this.getContainerTypeLoaded=function(){};this.eventId=void 0;this.isGtmEvent=!1},Me=function(a){var b=new Le;b.eventModel=a;return b},Ne=function(a,b){a.targetConfig=b;return a},Ve=function(a,b){a.containerConfig=b;return a},We=function(a,b){a.globalConfig=b;return a},Xe=function(a,
b){a.remoteConfig=b;return a},Ye=function(a,b){a.onSuccess=b;return a},Ze=function(a,b){a.setContainerTypeLoaded=b;return a},$e=function(a,b){a.getContainerTypeLoaded=b;return a},af=function(a,b){a.onFailure=b;return a};
Le.prototype.getWithConfig=function(a){if(void 0!==this.eventModel[a])return this.eventModel[a];if(void 0!==this.targetConfig[a])return this.targetConfig[a];if(void 0!==this.containerConfig[a])return this.containerConfig[a];if(void 0!==this.globalConfig[a])return this.globalConfig[a];if(void 0!==this.remoteConfig[a])return this.remoteConfig[a]};
var bf=function(a){function b(d){for(var e=Object.keys(d),f=0;f<e.length;++f)c[e[f]]=1}var c={};b(a.eventModel);b(a.targetConfig);b(a.containerConfig);b(a.globalConfig);return Object.keys(c)},cf=function(a,b,c){function d(g){Rb(g)&&Aa(g,function(k,l){f=!0;e[k]=l})}var e={},f=!1;c&&1!==c||(d(a.remoteConfig[b]),d(a.globalConfig[b]),d(a.containerConfig[b]),d(a.targetConfig[b]));c&&2!==c||d(a.eventModel[b]);return f?e:void 0},df=function(a){var b=[M.Tb,M.Ze,M.$e,M.af,M.bf,M.cf,M.df],c={},d=!1,e=function(f){for(var g=
0;g<b.length;g++)void 0!==f[b[g]]&&(c[b[g]]=f[b[g]],d=!0);return d};if(e(a.eventModel)||e(a.targetConfig)||e(a.containerConfig)||e(a.globalConfig))return c;e(a.remoteConfig);return c};var ef={},P=null,ff=Math.random();ef.I="UA-476124-1";ef.$c="ak0";ef.Qg="ChEI8MLJiwYQ5NDawJD7q7fBARIkAIsVh5wiKjT48zVX5Go3pOVP6hps04tnBXYQ9O1E5Q23lEC0GgJ0sg\x3d\x3d";var gf={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},hf={__paused:!0,__tg:!0},jf;for(jf in gf)gf.hasOwnProperty(jf)&&(hf[jf]=!0);ef.xd="www.googletagmanager.com";
var kf=ef.xd+"/gtm.js";kf=ef.xd+"/gtag/js";var lf=kf,mf=Fa(""),nf=null,of=null,pf="https://www.googletagmanager.com/a?id="+ef.I+"&cv=1",qf={},rf={},sf=function(){var a=P.sequence||1;P.sequence=a+1;return a};ef.Pg="";var tf="";
ef.ad=tf;var uf={},vf=new ya,wf={},xf={},Af={name:"dataLayer",set:function(a,b){H(Ua(a,b),wf);yf()},get:function(a){return zf(a,2)},reset:function(){vf=new ya;wf={};yf()}},zf=function(a,b){return 2!=b?vf.get(a):Bf(a)},Bf=function(a){var b,c=a.split(".");b=b||[];for(var d=wf,e=0;e<c.length;e++){if(null===d)return!1;if(void 0===d)break;d=d[c[e]];if(-1!==va(b,d))return}return d},Cf=function(a,b){xf.hasOwnProperty(a)||(vf.set(a,b),H(Ua(a,b),wf),yf())},yf=function(a){Aa(xf,function(b,c){vf.set(b,c);H(Ua(b,
void 0),wf);H(Ua(b,c),wf);a&&delete xf[b]})},Ef=function(a,b,c){uf[a]=uf[a]||{};uf[a][b]=Df(b,c)},Df=function(a,b){var c,d=1!==(void 0===b?2:b)?Bf(a):vf.get(a);"array"===Pb(d)||"object"===Pb(d)?c=H(d):c=d;return c},Ff=function(a,b){if(uf[a])return uf[a][b]},Gf=function(a,b){uf[a]&&delete uf[a][b]};var Hf,If=!1,Jf=function(a){if(!If){If=!0;Hf=Hf||{}}return Hf[a]};var Kf=function(a){if(B.hidden)return!0;var b=a.getBoundingClientRect();if(b.top==b.bottom||b.left==b.right||!m.getComputedStyle)return!0;var c=m.getComputedStyle(a,null);if("hidden"===c.visibility)return!0;for(var d=a,e=c;d;){if("none"===e.display)return!0;var f=e.opacity,g=e.filter;if(g){var k=g.indexOf("opacity(");0<=k&&(g=g.substring(k+8,g.indexOf(")",k)),"%"==g.charAt(g.length-1)&&(g=g.substring(0,g.length-1)),f=Math.min(g,f))}if(void 0!==f&&0>=f)return!0;(d=d.parentElement)&&(e=m.getComputedStyle(d,
null))}return!1};var Tf=/:[0-9]+$/,Uf=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(decodeURIComponent(f[0]).replace(/\+/g," ")===b){var g=f.slice(1).join("=");return c?g:decodeURIComponent(g).replace(/\+/g," ")}}},Xf=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=Vf(a.protocol)||Vf(m.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:m.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||m.location.hostname).replace(Tf,"").toLowerCase());return Wf(a,b,c,d,e)},Wf=function(a,b,c,d,e){var f,g=Vf(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":f=Yf(a);break;case "protocol":f=g;break;case "host":f=a.hostname.replace(Tf,"").toLowerCase();if(c){var k=/^www\d*\./.exec(f);k&&k[0]&&(f=f.substr(k[0].length))}break;case "port":f=String(Number(a.port)||("http"==g?80:"https"==g?443:""));break;case "path":a.pathname||a.hostname||zd("TAGGING",
1);f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=va(d||[],l[l.length-1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");e&&(f=Uf(f,e,void 0));break;case "extension":var n=a.pathname.split(".");f=1<n.length?n[n.length-1]:"";f=f.split("/")[0];break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Vf=function(a){return a?a.replace(":","").toLowerCase():""},Yf=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");
b=0>c?a.href:a.href.substr(0,c)}return b},Zf=function(a){var b=B.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||zd("TAGGING",1),c="/"+c);var d=b.hostname.replace(Tf,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}},$f=function(a){function b(n){var p=n.split("=")[0];return 0>d.indexOf(p)?n:p+"=0"}function c(n){return n.split("&").map(b).filter(function(p){return void 0!=p}).join("&")}var d="gclid dclid gbraid wbraid gclaw gcldc gclha gclgf gclgb _gl".split(" "),
e=Zf(a),f=a.split(/[?#]/)[0],g=e.search,k=e.hash;"?"===g[0]&&(g=g.substring(1));"#"===k[0]&&(k=k.substring(1));g=c(g);k=c(k);""!==g&&(g="?"+g);""!==k&&(k="#"+k);var l=""+f+g+k;"/"===l[l.length-1]&&(l=l.substring(0,l.length-1));return l};var ag={};var tg={},ug=function(a,b){if(m._gtmexpgrp&&m._gtmexpgrp.hasOwnProperty(a))return m._gtmexpgrp[a];void 0===tg[a]&&(tg[a]=Math.floor(Math.random()*b));return tg[a]};var vg=function(a){var b=1,c,d,e;if(a)for(b=0,d=a.length-1;0<=d;d--)e=a.charCodeAt(d),b=(b<<6&268435455)+e+(e<<14),c=b&266338304,b=0!=c?b^c>>21:b;return b};var wg=function(a,b,c){for(var d=[],e=b.split(";"),f=0;f<e.length;f++){var g=e[f].split("="),k=g[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=g.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d};function xg(a){return"null"!==a.origin};var Ag=function(a,b,c,d){return yg(d)?wg(a,String(b||zg()),c):[]},Ig=function(a,b,c,d,e){if(yg(e)){var f=Bg(a,d,e);if(1===f.length)return f[0].id;if(0!==f.length){f=Cg(f,function(g){return g.hd},b);if(1===f.length)return f[0].id;f=Cg(f,function(g){return g.wc},c);return f[0]?f[0].id:void 0}}};function Jg(a,b,c,d){var e=zg(),f=window;xg(f)&&(f.document.cookie=a);var g=zg();return e!=g||void 0!=c&&0<=Ag(b,g,!1,d).indexOf(c)}
var Ng=function(a,b,c){function d(t,r,v){if(null==v)return delete g[r],t;g[r]=v;return t+"; "+r+"="+v}function e(t,r){if(null==r)return delete g[r],t;g[r]=!0;return t+"; "+r}if(!yg(c.Fa))return 2;var f;void 0==b?f=a+"=deleted; expires="+(new Date(0)).toUTCString():(c.encode&&(b=encodeURIComponent(b)),b=Kg(b),f=a+"="+b);var g={};f=d(f,"path",c.path);var k;c.expires instanceof Date?k=c.expires.toUTCString():null!=c.expires&&(k=""+c.expires);f=d(f,"expires",k);f=d(f,"max-age",c.sj);f=d(f,"samesite",
c.uj);c.vj&&(f=e(f,"secure"));var l=c.domain;if(l&&"auto"===l.toLowerCase()){for(var n=Lg(),p=0;p<n.length;++p){var q="none"!==n[p]?n[p]:void 0,u=d(f,"domain",q);u=e(u,c.flags);if(!Mg(q,c.path)&&Jg(u,a,b,c.Fa))return 0}return 1}l&&"none"!==l.toLowerCase()&&(f=d(f,"domain",l));f=e(f,c.flags);return Mg(l,c.path)?1:Jg(f,a,b,c.Fa)?0:1},Og=function(a,b,c){null==c.path&&(c.path="/");c.domain||(c.domain="auto");return Ng(a,b,c)};
function Cg(a,b,c){for(var d=[],e=[],f,g=0;g<a.length;g++){var k=a[g],l=b(k);l===c?d.push(k):void 0===f||l<f?(e=[k],f=l):l===f&&e.push(k)}return 0<d.length?d:e}function Bg(a,b,c){for(var d=[],e=Ag(a,void 0,void 0,c),f=0;f<e.length;f++){var g=e[f].split("."),k=g.shift();if(!b||-1!==b.indexOf(k)){var l=g.shift();l&&(l=l.split("-"),d.push({id:g.join("."),hd:1*l[0]||1,wc:1*l[1]||1}))}}return d}
var Kg=function(a){a&&1200<a.length&&(a=a.substring(0,1200));return a},Pg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Qg=/(^|\.)doubleclick\.net$/i,Mg=function(a,b){return Qg.test(window.document.location.hostname)||"/"===b&&Pg.test(a)},zg=function(){return xg(window)?window.document.cookie:""},Lg=function(){var a=[],b=window.document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));
var e=window.document.location.hostname;Qg.test(e)||Pg.test(e)||a.push("none");return a},yg=function(a){if(!Hd(Dd)||!a||!Yd())return!0;if(!Xd(a))return!1;var b=Vd(a);return null==b?!0:!!b};var Rg=function(a){var b=Math.round(2147483647*Math.random()),c=b;a&&(c=b^vg(a)&2147483647);return[c,Math.round(h()/1E3)].join(".")},Ug=function(a,b,c,d,e){var f=Sg(b);return Ig(a,f,Tg(c),d,e)},Vg=function(a,b,c,d){var e=""+Sg(c),f=Tg(d);1<f&&(e+="-"+f);return[b,e,a].join(".")},Sg=function(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},Tg=function(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};function Wg(a,b,c){var d,e=Number(null!=a.ab?a.ab:void 0);0!==e&&(d=new Date((b||h())+1E3*(e||7776E3)));return{path:a.path,domain:a.domain,flags:a.flags,encode:!!c,expires:d}};var Xg=["1"],Yg={},ah=function(a,b){b=void 0===b?!0:b;var c=Zg(a.prefix);if(!Yg[c]&&!$g(c,a.path,a.domain)&&b){var d=Zg(a.prefix),e=Rg(),f=Vg(e,"1",a.domain,a.path),g=Wg(a);g.Fa="ad_storage";if(0===Og(d,f,g)){var k=vb("google_tag_data",{});k._gcl_au?zd("GTM",57):k._gcl_au=e}$g(c,a.path,a.domain)}};
function $g(a,b,c){var d=Ug(a,b,c,Xg,"ad_storage");if(!d)return!1;var e=d.split(".");5===e.length?(Yg[a]=e.slice(0,2).join("."),e.slice(2,4).join(".")):3===e.length?e.slice(0,2).join("."):Yg[a]=d;return!0}function Zg(a){return(a||"_gcl")+"_au"};var bh=function(a){for(var b=[],c=B.cookie.split(";"),d=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({Me:f[1],value:f[2],timestamp:Number(f[2].split(".")[1])||0})}b.sort(function(g,k){return k.timestamp-g.timestamp});return b};
function ch(a,b){var c=bh(a),d={};if(!c||!c.length)return d;for(var e=0;e<c.length;e++){var f=c[e].value.split(".");if(!("1"!==f[0]||b&&3>f.length||!b&&3!==f.length)&&Number(f[1])){d[c[e].Me]||(d[c[e].Me]=[]);var g={version:f[0],timestamp:1E3*Number(f[1]),oa:f[2]};b&&3<f.length&&(g.labels=f.slice(3));d[c[e].Me].push(g)}}return d};function dh(){for(var a=eh,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function fh(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}var eh,gh;function hh(a){eh=eh||fh();gh=gh||dh();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,f=a.charCodeAt(c),g=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=f>>2,n=(f&3)<<4|g>>4,p=(g&15)<<2|k>>6,q=k&63;e||(q=64,d||(p=64));b.push(eh[l],eh[n],eh[p],eh[q])}return b.join("")}
function ih(a){function b(l){for(;d<a.length;){var n=a.charAt(d++),p=gh[n];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(n))throw Error("Unknown base64 encoding at char: "+n);}return l}eh=eh||fh();gh=gh||dh();for(var c="",d=0;;){var e=b(-1),f=b(0),g=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|f>>4);64!=g&&(c+=String.fromCharCode(f<<4&240|g>>2),64!=k&&(c+=String.fromCharCode(g<<6&192|k)))}};var jh,kh=function(a){var b;if(!(b=jh)){for(var c=Array(256),d=0;256>d;d++){for(var e=d,f=0;8>f;f++)e=e&1?e>>>1^3988292384:e>>>1;c[d]=e}b=c}jh=b;for(var g=4294967295,k=0;k<a.length;k++)g=g>>>8^jh[(g^a.charCodeAt(k))&255];return(g^-1)>>>0};var oh=function(){var a=lh,b=mh,c=nh(),d=function(g){a(g.target||g.srcElement||{})},e=function(g){b(g.target||g.srcElement||{})};if(!c.init){Db(B,"mousedown",d);Db(B,"keyup",d);Db(B,"submit",e);var f=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);f.call(this)};c.init=!0}},ph=function(a,b,c,d,e){var f={callback:a,domains:b,fragment:2===c,placement:c,forms:d,sameHost:e};nh().decorators.push(f)},qh=function(a,b,c){for(var d=nh().decorators,e={},f=0;f<d.length;++f){var g=
d[f],k;if(k=!c||g.forms)a:{var l=g.domains,n=a,p=!!g.sameHost;if(l&&(p||n!==B.location.hostname))for(var q=0;q<l.length;q++)if(l[q]instanceof RegExp){if(l[q].test(n)){k=!0;break a}}else if(0<=n.indexOf(l[q])||p&&0<=l[q].indexOf(n)){k=!0;break a}k=!1}if(k){var u=g.placement;void 0==u&&(u=g.fragment?2:1);u===b&&Ra(e,g.callback())}}return e};function nh(){var a=vb("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var rh=/(.*?)\*(.*?)\*(.*)/,sh=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,th=/^(?:www\.|m\.|amp\.)+/,uh=/([^?#]+)(\?[^#]*)?(#.*)?/;function vh(a){return new RegExp("(.*?)(^|&)"+a+"=([^&]*)&?(.*)")}var yh=function(a,b){var c=[],d;for(d in a)if(a.hasOwnProperty(d)){var e=a[d];void 0!==e&&e===e&&null!==e&&"[object Object]"!==e.toString()&&(c.push(d),c.push(hh(String(e))))}var f=c.join("*");if(void 0!==b){var g="xp_"+b,k=wh[b](f);f=f+"*"+[g,hh(String(k))].join("*")}return["1",xh(f),f].join("*")};
function xh(a,b){var c=[m.navigator.userAgent,(new Date).getTimezoneOffset(),Nb(),Math.floor(h()/60/1E3)-(void 0===b?0:b),a].join("*");return kh(c).toString(36)}var zh={},wh=(zh[1]=Ah,zh[2]=Bh,zh);function Ah(a,b){var c=[(new Date).getTimezoneOffset(),Nb(),Math.floor(h()/60/1E3)-(void 0===b?0:b),a].join("*");return kh(c).toString(36)}
function Bh(a,b){if(tb.userAgentData){var c=[(new Date).getTimezoneOffset(),Nb(),Math.floor(h()/60/1E3)-(void 0===b?0:b),tb.userAgentData.brands,tb.userAgentData.mobile,tb.userAgentData.platform,a].join("*");return kh(c).toString(36)}}function Ch(){return function(a){var b=Zf(m.location.href),c=b.search.replace("?",""),d=Uf(c,"_gl",!0)||"";a.query=Dh(d)||{};var e=Xf(b,"fragment").match(vh("_gl"));a.fragment=Dh(e&&e[3]||"")||{}}}
var Eh=function(a){var b=Ch(),c=nh();c.data||(c.data={query:{},fragment:{}},b(c.data));var d={},e=c.data;e&&(Ra(d,e.query),a&&Ra(d,e.fragment));return d},Dh=function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var f=rh.exec(d);if(f){c=f;break a}d=decodeURIComponent(d)}c=void 0}var g=c;if(g&&"1"===g[1]){var k=g[3],l;a:{for(var n=g[2],p=0;p<b;++p)if(n===xh(k,p)){l=!0;break a}l=!1}if(l){for(var q={},u=k?k.split("*"):[],t=0;t<u.length;t+=2)q[u[t]]=ih(u[t+1]);return q}}}}catch(r){}};
function Fh(a,b,c,d){function e(p){var q=p,u=vh(a).exec(q),t=q;if(u){var r=u[2],v=u[4];t=u[1];v&&(t=t+r+v)}p=t;var x=p.charAt(p.length-1);p&&"&"!==x&&(p+="&");return p+n}d=void 0===d?!1:d;var f=uh.exec(c);if(!f)return"";var g=f[1],k=f[2]||"",l=f[3]||"",n=a+"="+b;d?l="#"+e(l.substring(1)):k="?"+e(k.substring(1));return""+g+k+l}
function Gh(a,b){var c="FORM"===(a.tagName||"").toUpperCase(),d=qh(b,1,c),e=qh(b,2,c),f=qh(b,3,c);if(Sa(d)){var g=yh(d,void 0);c?Hh("_gl",g,a):Ih("_gl",g,a,!1)}if(!c&&Sa(e)){var k=yh(e);Ih("_gl",k,a,!0)}for(var l in f)if(f.hasOwnProperty(l))a:{var n=l,p=f[l],q=a;if(q.tagName){if("a"===q.tagName.toLowerCase()){Ih(n,p,q,void 0);break a}if("form"===q.tagName.toLowerCase()){Hh(n,p,q);break a}}"string"==typeof q&&Fh(n,p,q,void 0)}}
function Ih(a,b,c,d){if(c.href){var e=Fh(a,b,c.href,void 0===d?!1:d);bb.test(e)&&(c.href=e)}}
function Hh(a,b,c){if(c&&c.action){var d=(c.method||"").toLowerCase();if("get"===d){for(var e=c.childNodes||[],f=!1,g=0;g<e.length;g++){var k=e[g];if(k.name===a){k.setAttribute("value",b);f=!0;break}}if(!f){var l=B.createElement("input");l.setAttribute("type","hidden");l.setAttribute("name",a);l.setAttribute("value",b);c.appendChild(l)}}else if("post"===d){var n=Fh(a,b,c.action);bb.test(n)&&(c.action=n)}}}
function lh(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var f=e.protocol;"http:"!==f&&"https:"!==f||Gh(e,e.hostname)}}catch(g){}}function mh(a){try{if(a.action){var b=Xf(Zf(a.action),"host");Gh(a,b)}}catch(c){}}
var Jh=function(a,b,c,d){oh();ph(a,b,"fragment"===c?2:1,!!d,!1)},Kh=function(a,b){oh();ph(a,[Wf(m.location,"host",!0)],b,!0,!0)},Lh=function(){var a=B.location.hostname,b=sh.exec(B.referrer);if(!b)return!1;var c=b[2],d=b[1],e="";if(c){var f=c.split("/"),g=f[1];e="s"===g?decodeURIComponent(f[2]):decodeURIComponent(g)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}var k=a.replace(th,""),l=e.replace(th,""),n;if(!(n=k===l)){var p="."+l;n=k.substring(k.length-p.length,
k.length)===p}return n},Mh=function(a,b){return!1===a?!1:a||b||Lh()};var Nh={};var Oh=/^\w+$/,Ph=/^[\w-]+$/,Qh={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp",gb:"_gb"},Rh=function(){if(!Hd(Dd)||!Yd())return!0;var a=Vd("ad_storage");return null==a?!0:!!a},Sh=function(a,b){Xd("ad_storage")?Rh()?a():ce(a,"ad_storage"):b?zd("TAGGING",3):be(function(){Sh(a,!0)},["ad_storage"])},Uh=function(a){return Th(a).map(function(b){return b.oa})},Th=function(a){var b=[];if(!xg(m)||!B.cookie)return b;var c=Ag(a,B.cookie,void 0,"ad_storage");if(!c||0==c.length)return b;for(var d={},e=0;e<c.length;d=
{Dc:d.Dc},e++){var f=Vh(c[e]);if(null!=f){var g=f,k=g.version;d.Dc=g.oa;var l=g.timestamp,n=g.labels,p=wa(b,function(q){return function(u){return u.oa===q.Dc}}(d));p?(p.timestamp=Math.max(p.timestamp,l),p.labels=Wh(p.labels,n||[])):b.push({version:k,oa:d.Dc,timestamp:l,labels:n})}}b.sort(function(q,u){return u.timestamp-q.timestamp});return Xh(b)};function Wh(a,b){for(var c={},d=[],e=0;e<a.length;e++)c[a[e]]=!0,d.push(a[e]);for(var f=0;f<b.length;f++)c[b[f]]||d.push(b[f]);return d}
function Yh(a){return a&&"string"==typeof a&&a.match(Oh)?a:"_gcl"}
var $h=function(){var a=Zf(m.location.href),b=Xf(a,"query",!1,void 0,"gclid"),c=Xf(a,"query",!1,void 0,"gclsrc"),d=Xf(a,"query",!1,void 0,"wbraid"),e=Xf(a,"query",!1,void 0,"dclid");if(!b||!c||!d){var f=a.hash.replace("#","");b=b||Uf(f,"gclid",void 0);c=c||Uf(f,"gclsrc",void 0);d=d||Uf(f,"wbraid",void 0)}return Zh(b,c,e,d)},Zh=function(a,b,c,d){var e={},f=function(g,k){e[k]||(e[k]=[]);e[k].push(g)};e.gclid=a;e.gclsrc=b;e.dclid=c;void 0!==d&&Ph.test(d)&&(e.gbraid=d,f(d,"gb"));if(void 0!==a&&a.match(Ph))switch(b){case void 0:f(a,
"aw");break;case "aw.ds":f(a,"aw");f(a,"dc");break;case "ds":f(a,"dc");break;case "3p.ds":f(a,"dc");break;case "gf":f(a,"gf");break;case "ha":f(a,"ha")}c&&f(c,"dc");return e},bi=function(a){var b=$h();Sh(function(){ai(b,!1,a)})};
function ai(a,b,c,d,e){function f(x,z){var w=ci(x,g);w&&(Og(w,z,k),l=!0)}c=c||{};e=e||[];var g=Yh(c.prefix);d=d||h();var k=Wg(c,d,!0);k.Fa="ad_storage";var l=!1,n=Math.round(d/1E3),p=function(x){var z=["GCL",n,x];0<e.length&&z.push(e.join("."));return z.join(".")};a.aw&&f("aw",p(a.aw[0]));a.dc&&f("dc",p(a.dc[0]));a.gf&&f("gf",p(a.gf[0]));a.ha&&f("ha",p(a.ha[0]));a.gp&&f("gp",p(a.gp[0]));if((void 0==Nh.enable_gbraid_cookie_write?0:Nh.enable_gbraid_cookie_write)&&!l&&a.gb){var q=a.gb[0],u=ci("gb",g),
t=!1;if(!b)for(var r=Th(u),v=0;v<r.length;v++)r[v].oa===q&&r[v].labels&&0<r[v].labels.length&&(t=!0);t||f("gb",p(q))}}
var ei=function(a,b){var c=Eh(!0);Sh(function(){for(var d=Yh(b.prefix),e=0;e<a.length;++e){var f=a[e];if(void 0!==Qh[f]){var g=ci(f,d),k=c[g];if(k){var l=Math.min(di(k),h()),n;b:{var p=l;if(xg(m))for(var q=Ag(g,B.cookie,void 0,"ad_storage"),u=0;u<q.length;++u)if(di(q[u])>p){n=!0;break b}n=!1}if(!n){var t=Wg(b,l,!0);t.Fa="ad_storage";Og(g,k,t)}}}}ai(Zh(c.gclid,c.gclsrc),!1,b)})},ci=function(a,b){var c=Qh[a];if(void 0!==c)return b+c},di=function(a){return 0!==fi(a.split(".")).length?1E3*(Number(a.split(".")[1])||
0):0};function Vh(a){var b=fi(a.split("."));return 0===b.length?null:{version:b[0],oa:b[2],timestamp:1E3*(Number(b[1])||0),labels:b.slice(3)}}function fi(a){return 3>a.length||"GCL"!==a[0]&&"1"!==a[0]||!/^\d+$/.test(a[1])||!Ph.test(a[2])?[]:a}
var gi=function(a,b,c,d,e){if(ua(b)&&xg(m)){var f=Yh(e),g=function(){for(var k={},l=0;l<a.length;++l){var n=ci(a[l],f);if(n){var p=Ag(n,B.cookie,void 0,"ad_storage");p.length&&(k[n]=p.sort()[p.length-1])}}return k};Sh(function(){Jh(g,b,c,d)})}},Xh=function(a){return a.filter(function(b){return Ph.test(b.oa)})},hi=function(a,b){if(xg(m)){for(var c=Yh(b.prefix),d={},e=0;e<a.length;e++)Qh[a[e]]&&(d[a[e]]=Qh[a[e]]);Sh(function(){Aa(d,function(f,g){var k=Ag(c+g,B.cookie,void 0,"ad_storage");k.sort(function(t,
r){return di(r)-di(t)});if(k.length){var l=k[0],n=di(l),p=0!==fi(l.split(".")).length?l.split(".").slice(3):[],q={},u;u=0!==fi(l.split(".")).length?l.split(".")[2]:void 0;q[f]=[u];ai(q,!0,b,n,p)}})})}};function ii(a,b){for(var c=0;c<b.length;++c)if(a[b[c]])return!0;return!1}
var ji=function(a){function b(e,f,g){g&&(e[f]=g)}if(Yd()){var c=$h();if(ii(c,a)){var d={};b(d,"gclid",c.gclid);b(d,"dclid",c.dclid);b(d,"gclsrc",c.gclsrc);b(d,"wbraid",c.gbraid);Kh(function(){return d},3);Kh(function(){var e={};return e._up="1",e},1)}}};function ki(a,b){var c=Yh(b),d=ci(a,c);if(!d)return 0;for(var e=Th(d),f=0,g=0;g<e.length;g++)f=Math.max(f,e[g].timestamp);return f}
function li(a){var b=0,c;for(c in a)for(var d=a[c],e=0;e<d.length;e++)b=Math.max(b,Number(d[e].timestamp));return b};var Fi=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Gi={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Hi={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Ii="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var Ji=function(){var a=!1;a=!0;return a},Li=function(a){var b=zf("gtm.allowlist")||zf("gtm.whitelist");b&&Bd(9);Ji()&&(b="google gtagfl lcl zone oid op".split(" "));var c=b&&Ta(Ia(b),Gi),d=zf("gtm.blocklist")||
zf("gtm.blacklist");d||(d=zf("tagTypeBlacklist"))&&Bd(3);d?Bd(8):d=[];Ki()&&(d=Ia(d),d.push("nonGooglePixels","nonGoogleScripts","sandboxedScripts"));0<=va(Ia(d),"google")&&Bd(2);var e=d&&Ta(Ia(d),Hi),f={};return function(g){var k=g&&g[Tb.lb];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==f[k])return f[k];var l=rf[k]||[],n=a(k,l);if(b){var p;if(p=
n)a:{if(0>va(c,k))if(l&&0<l.length)for(var q=0;q<l.length;q++){if(0>va(c,l[q])){Bd(11);p=!1;break a}}else{p=!1;break a}p=!0}n=p}var u=!1;if(d){var t=0<=va(e,k);if(t)u=t;else{var r=za(e,l||[]);r&&Bd(10);u=r}}var v=!n||u;v||!(0<=va(l,"sandboxedScripts"))||c&&-1!==va(c,"sandboxedScripts")||(v=za(e,Ii));return f[k]=v}},Ki=function(){return Fi.test(m.location&&m.location.hostname)};var Mi=!1,Ni=0,Oi=[];function Pi(a){if(!Mi){var b=B.createEventObject,c="complete"==B.readyState,d="interactive"==B.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Mi=!0;for(var e=0;e<Oi.length;e++)G(Oi[e])}Oi.push=function(){for(var f=0;f<arguments.length;f++)G(arguments[f]);return 0}}}function Qi(){if(!Mi&&140>Ni){Ni++;try{B.documentElement.doScroll("left"),Pi()}catch(a){m.setTimeout(Qi,50)}}}var Ri=function(a){Mi?a():Oi.push(a)};var Ti=function(a,b){this.m=!1;this.D=[];this.N={tags:[]};this.Z=!1;this.o=this.B=0;Si(this,a,b)},Ui=function(a,b,c,d){if(hf.hasOwnProperty(b)||"__zone"===b)return-1;var e={};Rb(d)&&(e=H(d,e));e.id=c;e.status="timeout";return a.N.tags.push(e)-1},Vi=function(a,b,c,d){var e=a.N.tags[b];e&&(e.status=c,e.executionTime=d)},Wi=function(a){if(!a.m){for(var b=a.D,c=0;c<b.length;c++)b[c]();a.m=!0;a.D.length=0}},Si=function(a,b,c){ra(b)&&Xi(a,b);c&&m.setTimeout(function(){return Wi(a)},Number(c))},Xi=function(a,
b){var c=Qa(function(){return G(function(){b(ef.I,a.N)})});a.m?c():a.D.push(c)},Yi=function(a){a.B++;return Qa(function(){a.o++;a.Z&&a.o>=a.B&&Wi(a)})};var Zi=function(){function a(d){return!ta(d)||0>d?0:d}if(!P._li&&m.performance&&m.performance.timing){var b=m.performance.timing.navigationStart,c=ta(Af.get("gtm.start"))?Af.get("gtm.start"):0;P._li={cst:a(c-b),cbt:a(of-b)}}},$i=function(a){m.performance&&m.performance.mark(ef.I+"_"+a+"_start")},aj=function(a){if(m.performance){var b=ef.I+"_"+a+"_start",c=ef.I+"_"+a+"_duration";m.performance.measure(c,b);var d=m.performance.getEntriesByName(c)[0];m.performance.clearMarks(b);m.performance.clearMeasures(c);
var e=P._p||{};void 0===e[a]&&(e[a]=d.duration,P._p=e);return d.duration}},bj=function(){if(m.performance&&m.performance.now){var a=P._p||{};a.PAGEVIEW=m.performance.now();P._p=a}};var cj={},dj=function(){return m.GoogleAnalyticsObject&&m[m.GoogleAnalyticsObject]},ej=!1;
var fj=function(a){m.GoogleAnalyticsObject||(m.GoogleAnalyticsObject=a||"ga");var b=m.GoogleAnalyticsObject;if(m[b])m.hasOwnProperty(b)||Bd(12);else{var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(Oa());m[b]=c}Zi();return m[b]},gj=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=dj();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)},hj=function(a){if(!Yd())return;var b=dj();b(a+"require","linker");b(a+"linker:passthrough",
!0);};function ij(){return m.GoogleAnalyticsObject||"ga"}
var jj=function(a){},kj=function(a,b){return function(){var c=dj(),d=c&&c.getByName&&c.getByName(a);if(d){var e=d.get("sendHitTask");d.set("sendHitTask",function(f){var g=f.get("hitPayload"),k=f.get("hitCallback"),l=0>g.indexOf("&tid="+b);l&&(f.set("hitPayload",g.replace(/&tid=UA-[0-9]+-[0-9]+/,"&tid="+b),!0),f.set("hitCallback",void 0,!0));e(f);l&&(f.set("hitPayload",
g,!0),f.set("hitCallback",k,!0),f.set("_x_19",void 0,!0),e(f))})}}};
var rj=function(a){},vj=function(a){},wj=
function(){return"&tc="+Dc.filter(function(a){return a}).length},zj=function(){2022<=xj().length&&yj()},Aj=function(a){return 0===a.indexOf("gtm.")?encodeURIComponent(a):"*"},Cj=function(){Bj||(Bj=m.setTimeout(yj,500))},yj=function(){Bj&&(m.clearTimeout(Bj),Bj=void 0);void 0===Dj||Ej[Dj]&&!Fj&&!Gj||(Hj[Dj]||Ij.zi()||0>=Jj--?(Bd(1),Hj[Dj]=!0):(Ij.Ui(),Cb(xj(!0)),Ej[Dj]=!0,Kj=Lj=Mj=Gj=Fj=""))},xj=function(a){var b=Dj;if(void 0===b)return"";var c=Ad("GTM"),d=Ad("TAGGING");return[Nj,Ej[b]?"":"&es=1",
Oj[b],rj(b),c?"&u="+c:"",d?"&ut="+d:"",wj(),Fj,Gj,Mj,Lj,vj(a),Kj,"&z=0"].join("")},Qj=function(){Nj=Pj()},Pj=function(){return[pf,"&v=3&t=t","&pid="+xa(),"&rv="+ef.$c].join("")},uj=["L","S","Y"],qj=["S","E"],Rj={sampleRate:"0.005000",Ig:"",Hg:Number("5")},Sj=0<=B.location.search.indexOf("?gtm_latency=")||0<=B.location.search.indexOf("&gtm_latency="),Tj;if(!(Tj=Sj)){var Uj=Math.random(),Vj=Rj.sampleRate;Tj=Uj<Vj}var Wj=Tj,Xj={label:ef.I+" Container",children:[{label:"Initialization",children:[]}]},Nj=Pj(),Ej={},Fj="",Gj="",Kj="",Lj="",tj={},sj=!1,pj={},Yj={},Mj="",Dj=void 0,Oj={},Hj={},Bj=void 0,Zj=5;0<Rj.Hg&&(Zj=Rj.Hg);var Ij=function(a,b){for(var c=0,d=[],e=0;e<a;++e)d.push(0);return{zi:function(){return c<a?!1:h()-d[c%a]<b},Ui:function(){var f=c++%a;d[f]=h()}}}(Zj,1E3),Jj=1E3,bk=function(a,b){if(Wj&&!Hj[a]&&Dj!==
a){yj();Dj=a;Kj=Fj="";Oj[a]="&e="+Aj(b)+"&eid="+a;Cj();}},ck=function(a,b,c,d){if(Wj&&b){var e,f=String(b[Tb.lb]||"").replace(/_/g,"");0===f.indexOf("cvt")&&(f="cvt");e=f;var g=c+e;if(!Hj[a]){a!==Dj&&(yj(),Dj=a);Fj=Fj?Fj+"."+g:"&tr="+g;var k=b["function"];if(!k)throw Error("Error: No function name given for function call.");var l=(Fc[k]?"1":"2")+e;Kj=Kj?Kj+"."+l:"&ti="+l;Cj();zj()}}};var jk=function(a,b,c){if(Wj&&!Hj[a]){a!==Dj&&(yj(),Dj=a);var d=c+b;Gj=Gj?Gj+"."+d:"&epr="+d;Cj();zj()}},kk=function(a,b,c){};var lk={active:!0,isAllowed:function(){return!0}},mk=function(a){var b=P.zones;return b?b.checkState(ef.I,a):lk},nk=function(a){var b=P.zones;!b&&a&&(b=P.zones=a());return b};function ok(){}function pk(){};function qk(a,b,c,d){var e=Dc[a],f=rk(a,b,c,d);if(!f)return null;var g=Kc(e[Tb.Ff],c,[]);if(g&&g.length){var k=g[0];f=qk(k.index,{onSuccess:f,onFailure:1===k.$f?b.terminate:f,terminate:b.terminate},c,d)}return f}
function rk(a,b,c,d){function e(){if(f[Tb.Fh])k();else{var x=Lc(f,c,[]);var z=x[Tb.Ng];if(null!=z)for(var w=0;w<z.length;w++)if(!ie(z[w])){k();return}var y=Ui(c.mb,String(f[Tb.lb]),Number(f[Tb.Hf]),x[Tb.Gh]),A=!1;x.vtp_gtmOnSuccess=function(){if(!A){A=!0;var D=h()-F;ck(c.id,Dc[a],"5",D);Vi(c.mb,y,"success",
D);g()}};x.vtp_gtmOnFailure=function(){if(!A){A=!0;var D=h()-F;ck(c.id,Dc[a],"6",D);Vi(c.mb,y,"failure",D);k()}};x.vtp_gtmTagId=f.tag_id;x.vtp_gtmEventId=c.id;ck(c.id,f,"1");var C=function(){var D=h()-F;ck(c.id,f,"7",D);Vi(c.mb,y,"exception",D);A||(A=!0,k())};var F=h();try{Jc(x,c)}catch(D){C(D)}}}var f=Dc[a],g=b.onSuccess,k=b.onFailure,l=b.terminate;if(c.Be(f))return null;var n=Kc(f[Tb.If],c,[]);if(n&&n.length){var p=n[0],q=qk(p.index,{onSuccess:g,onFailure:k,terminate:l},c,d);if(!q)return null;g=q;k=2===p.$f?l:q}if(f[Tb.Bf]||f[Tb.Kh]){var u=f[Tb.Bf]?Ec:
c.bj,t=g,r=k;if(!u[a]){e=Qa(e);var v=sk(a,u,e);g=v.onSuccess;k=v.onFailure}return function(){u[a](t,r)}}return e}function sk(a,b,c){var d=[],e=[];b[a]=tk(d,e,c);return{onSuccess:function(){b[a]=uk;for(var f=0;f<d.length;f++)d[f]()},onFailure:function(){b[a]=vk;for(var f=0;f<e.length;f++)e[f]()}}}function tk(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function uk(a){a()}function vk(a,b){b()};var yk=function(a,b){for(var c=[],d=0;d<Dc.length;d++)if(a[d]){var e=Dc[d];var f=Yi(b.mb);try{var g=qk(d,{onSuccess:f,onFailure:f,terminate:f},b,d);if(g){var k=c,l=k.push,n=d,p=e["function"];if(!p)throw"Error: No function name given for function call.";var q=Fc[p];l.call(k,{Ag:n,pg:q?q.priorityOverride||0:0,execute:g})}else wk(d,b),f()}catch(r){f()}}var u=b.mb;u.Z=!0;u.o>=u.B&&Wi(u);c.sort(xk);for(var t=0;t<c.length;t++)c[t].execute();
return 0<c.length};function xk(a,b){var c,d=b.pg,e=a.pg;c=d>e?1:d<e?-1:0;var f;if(0!==c)f=c;else{var g=a.Ag,k=b.Ag;f=g>k?1:g<k?-1:0}return f}function wk(a,b){if(!Wj)return;var c=function(d){var e=b.Be(Dc[d])?"3":"4",f=Kc(Dc[d][Tb.Ff],b,[]);f&&f.length&&c(f[0].index);ck(b.id,Dc[d],e);var g=Kc(Dc[d][Tb.If],b,[]);g&&g.length&&c(g[0].index)};c(a);}
var zk=!1,Fk=function(a){var b=h(),c=a["gtm.uniqueEventId"],d=a.event;if("gtm.js"===d){if(zk)return!1;zk=!0;}var g=mk(c),k=!1;if(!g.active){if("gtm.js"!==d)return!1;k=!0;g=mk(Number.MAX_SAFE_INTEGER)}
bk(c,d);var l=a.eventCallback,n=a.eventTimeout,p=l;var q={id:c,name:d,Be:Li(g.isAllowed),bj:[],jg:function(){Bd(6)},Tf:Ak(c),mb:new Ti(p,n)};q.Sf=Bk();
Ck(c,q.mb);var u=Sc(q);k&&(u=Dk(u));var t=yk(u,q);"gtm.js"!==d&&"gtm.sync"!==d||jj(ef.I);return Ek(u,t)};function Ak(a){return function(b){Wj&&(Sb(b)||kk(a,"input",b))}}
function Ck(a,b){Ef(a,"event",1);Ef(a,"ecommerce",1);Ef(a,"gtm");Ef(a,"eventModel");}function Bk(){var a={};a.event=Df("event",1);a.ecommerce=Df("ecommerce",1);a.gtm=Df("gtm");a.eventModel=Df("eventModel");return a}function Dk(a){for(var b=[],c=0;c<a.length;c++)a[c]&&gf[String(Dc[c][Tb.lb])]&&(b[c]=!0);return b}
function Ek(a,b){if(!b)return b;for(var c=0;c<a.length;c++)if(a[c]&&Dc[c]&&!hf[String(Dc[c][Tb.lb])])return!0;return!1}function Gk(a,b){if(a){var c=""+a;0!==c.indexOf("http://")&&0!==c.indexOf("https://")&&(c="https://"+c);"/"===c[c.length-1]&&(c=c.substring(0,c.length-1));return Zf(""+c+b).href}}function Hk(a,b){return Ik()?Gk(a,b):void 0}function Ik(){var a=!1;return a}
function Jk(){return!!ef.ad&&"SGTM_TOKEN"!==ef.ad.replaceAll("@@","")};var Kk=function(){var a=!1;return a};var Lk;if(3===ef.$c.length)Lk="g";else{var Mk="G";Mk="g";Lk=Mk}
var Nk={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:Lk,OPT:"o"},Ok=function(a){var b=ef.I.split("-"),c=b[0].toUpperCase(),d=Nk[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",f;if(3===ef.$c.length){var g="w";g=Kk()?"s":"o";f="2"+g}else f="";return f+d+ef.$c+e};function Pk(a,b){if(""===a)return b;var c=Number(a);return isNaN(c)?b:c};var Qk=function(a,b){a.addEventListener&&a.addEventListener.call(a,"message",b,!1)};function Rk(){return ib("iPhone")&&!ib("iPod")&&!ib("iPad")};ib("Opera");ib("Trident")||ib("MSIE");ib("Edge");!ib("Gecko")||-1!=cb.toLowerCase().indexOf("webkit")&&!ib("Edge")||ib("Trident")||ib("MSIE")||ib("Edge");-1!=cb.toLowerCase().indexOf("webkit")&&!ib("Edge")&&ib("Mobile");ib("Macintosh");ib("Windows");ib("Linux")||ib("CrOS");var Sk=na.navigator||null;Sk&&(Sk.appVersion||"").indexOf("X11");ib("Android");Rk();ib("iPad");ib("iPod");Rk()||ib("iPad")||ib("iPod");cb.toLowerCase().indexOf("kaios");var Tk=function(a,b){for(var c=a,d=0;50>d;++d){var e;try{e=!(!c.frames||!c.frames[b])}catch(k){e=!1}if(e)return c;var f;a:{try{var g=c.parent;if(g&&g!=c){f=g;break a}}catch(k){}f=null}if(!(c=f))break}return null},Uk=function(a){var b=B;b=void 0===b?window.document:b;if(!a||!b.head)return null;var c,d,e;e=void 0===e?document:e;d="META";"application/xhtml+xml"===(null==e?void 0:e.contentType)&&(d=d.toLowerCase());c=e.createElement(d);b.head.appendChild(c);c.httpEquiv="origin-trial";c.content=a;return c};var Vk=function(){};var Wk=function(a){void 0!==a.addtlConsent&&"string"!==typeof a.addtlConsent&&(a.addtlConsent=void 0);void 0!==a.gdprApplies&&"boolean"!==typeof a.gdprApplies&&(a.gdprApplies=void 0);return void 0!==a.tcString&&"string"!==typeof a.tcString||void 0!==a.listenerId&&"number"!==typeof a.listenerId?2:a.cmpStatus&&"error"!==a.cmpStatus?0:3},Xk=function(a,b){this.o=a;this.m=null;this.D={};this.Z=0;this.N=void 0===b?500:b;this.B=null};ma(Xk,Vk);
var Zk=function(a){return"function"===typeof a.o.__tcfapi||null!=Yk(a)};
Xk.prototype.addEventListener=function(a){var b={},c=rb(function(){return a(b)}),d=0;-1!==this.N&&(d=setTimeout(function(){b.tcString="tcunavailable";b.internalErrorState=1;c()},this.N));var e=function(f,g){clearTimeout(d);f?(b=f,b.internalErrorState=Wk(b),g&&0===b.internalErrorState||(b.tcString="tcunavailable",g||(b.internalErrorState=3))):(b.tcString="tcunavailable",b.internalErrorState=3);a(b)};try{$k(this,"addEventListener",e)}catch(f){b.tcString="tcunavailable",b.internalErrorState=3,d&&(clearTimeout(d),
d=0),c()}};Xk.prototype.removeEventListener=function(a){a&&a.listenerId&&$k(this,"removeEventListener",null,a.listenerId)};
var bl=function(a,b,c){var d;d=void 0===d?"755":d;var e;a:{if(a.publisher&&a.publisher.restrictions){var f=a.publisher.restrictions[b];if(void 0!==f){e=f[void 0===d?"755":d];break a}}e=void 0}var g=e;if(0===g)return!1;var k=c;2===c?(k=0,2===g&&(k=1)):3===c&&(k=1,1===g&&(k=0));var l;if(0===k)if(a.purpose&&a.vendor){var n=al(a.vendor.consents,void 0===d?"755":d);l=n&&"1"===b&&a.purposeOneTreatment&&((Hd(Ed)?0:"DE"===a.publisherCC)||"CH"===a.publisherCC)?!0:n&&al(a.purpose.consents,b)}else l=!0;else l=
1===k?a.purpose&&a.vendor?al(a.purpose.legitimateInterests,b)&&al(a.vendor.legitimateInterests,void 0===d?"755":d):!0:!0;return l},al=function(a,b){return!(!a||!a[b])},$k=function(a,b,c,d){c||(c=function(){});if("function"===typeof a.o.__tcfapi){var e=a.o.__tcfapi;e(b,2,c,d)}else if(Yk(a)){cl(a);var f=++a.Z;a.D[f]=c;if(a.m){var g={};a.m.postMessage((g.__tcfapiCall={command:b,version:2,callId:f,parameter:d},g),"*")}}else c({},!1)},Yk=function(a){if(a.m)return a.m;a.m=Tk(a.o,"__tcfapiLocator");return a.m},
cl=function(a){a.B||(a.B=function(b){try{var c;c=("string"===typeof b.data?JSON.parse(b.data):b.data).__tcfapiReturn;a.D[c.callId](c.returnValue,c.success)}catch(d){}},Qk(a.o,a.B))};var dl=!0;dl=!1;var el={1:0,3:0,4:0,7:3,9:3,10:3},fl=Pk("",550),gl=Pk("",500);function hl(){var a=P.tcf||{};return P.tcf=a}
var il=function(a,b){this.B=a;this.m=b;this.o=h();},jl=function(a){},kl=function(a){},ql=function(){var a=hl(),b=new Xk(m,dl?3E3:-1),c=new il(b,a);if((ll()?!0===m.gtag_enable_tcf_support:!1!==m.gtag_enable_tcf_support)&&!a.active&&("function"===typeof m.__tcfapi||Zk(b))){a.active=!0;a.yc={};ml();var d=null;dl?d=m.setTimeout(function(){nl(a);ol(a);d=null},gl):a.tcString="tcunavailable";try{b.addEventListener(function(e){d&&(clearTimeout(d),d=null);if(0!==e.internalErrorState)nl(a),ol(a),jl(c);
else{var f;a.gdprApplies=e.gdprApplies;if(!1===e.gdprApplies)f=pl(),b.removeEventListener(e);else if("tcloaded"===e.eventStatus||"useractioncomplete"===e.eventStatus||"cmpuishown"===e.eventStatus){var g={},k;for(k in el)if(el.hasOwnProperty(k))if("1"===k){var l,n=e,p=!0;p=void 0===p?!1:p;var q;var u=n;!1===u.gdprApplies?q=!0:(void 0===u.internalErrorState&&(u.internalErrorState=Wk(u)),q="error"===u.cmpStatus||0!==u.internalErrorState||"loaded"===u.cmpStatus&&("tcloaded"===u.eventStatus||"useractioncomplete"===
u.eventStatus)?!0:!1);l=q?!1===n.gdprApplies||"tcunavailable"===n.tcString||void 0===n.gdprApplies&&!p||"string"!==typeof n.tcString||!n.tcString.length?!0:bl(n,"1",0):!1;g["1"]=l}else g[k]=bl(e,k,el[k]);f=g}f&&(a.tcString=e.tcString||"tcempty",a.yc=f,ol(a),jl(c))}}),kl(c)}catch(e){d&&(clearTimeout(d),d=null),nl(a),ol(a)}}};function nl(a){a.type="e";a.tcString="tcunavailable";dl&&(a.yc=pl())}function ml(){var a={},b=(a.ad_storage="denied",a.wait_for_update=fl,a);fe(b)}
var ll=function(){var a=!1;a=!0;return a};function pl(){var a={},b;for(b in el)el.hasOwnProperty(b)&&(a[b]=!0);return a}function ol(a){var b={},c=(b.ad_storage=a.yc["1"]?"granted":"denied",b);rl();he(c,0)}
var sl=function(){var a=hl();if(a.active&&void 0!==a.loadTime)return Number(a.loadTime)},rl=function(){var a=hl();return a.active?a.tcString||"":""},tl=function(){var a=hl();return a.active&&void 0!==a.gdprApplies?a.gdprApplies?"1":"0":""},ul=function(a){if(!el.hasOwnProperty(String(a)))return!0;var b=hl();return b.active&&b.yc?!!b.yc[String(a)]:!0};var Cl=!1;var Dl=function(){this.m={}},El=function(a,b,c){null!=c&&(a.m[b]=c)},Fl=function(a){return Object.keys(a.m).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a.m[b])}).join("&")},Hl=function(a,b,c,d,e){};
var Jl=/[A-Z]+/,Kl=/\s/,Ll=function(a){if(sa(a)){a=La(a);var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(Jl.test(c)){var d=!1;d=!0;for(var e=a.substring(b+1).split("/"),f=0;f<e.length;f++)if(!e[f]||Kl.test(e[f])&&("AW"!==c||1!==f||!d))return;return{id:a,prefix:c,containerId:c+"-"+e[0],K:e}}}}},Nl=function(a){for(var b={},c=0;c<a.length;++c){var d=
Ll(a[c]);d&&(b[d.id]=d)}Ml(b);var e=[];Aa(b,function(f,g){e.push(g)});return e};function Ml(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.K[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var Pl=function(a,b,c,d){return(2===Ol()||d||"http:"!=m.location.protocol?a:b)+c},Ol=function(){var a=Ab(),b;if(1===a)a:{var c=lf;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,f=1,g=B.getElementsByTagName("script"),k=0;k<g.length&&100>k;k++){var l=g[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===f&&0===l.indexOf(d)&&(f=2)}}b=f}else b=a;return b};
var Rl=function(a,b,c){if(m[a.functionName])return b.Fe&&G(b.Fe),m[a.functionName];var d=Ql();m[a.functionName]=d;if(a.dd)for(var e=0;e<a.dd.length;e++)m[a.dd[e]]=m[a.dd[e]]||Ql();a.od&&void 0===m[a.od]&&(m[a.od]=c);zb(Pl("https://","http://",a.Ke),b.Fe,b.Ki);return d},Ql=function(){var a=function(){a.q=a.q||[];a.q.push(arguments)};return a},Sl={functionName:"_googWcmImpl",od:"_googWcmAk",Ke:"www.gstatic.com/wcm/loader.js"},Tl={functionName:"_gaPhoneImpl",od:"ga_wpid",Ke:"www.gstatic.com/gaphone/loader.js"},
Ul={Mg:"",Lh:"5"},Vl={functionName:"_googCallTrackingImpl",dd:[Tl.functionName,Sl.functionName],Ke:"www.gstatic.com/call-tracking/call-tracking_"+(Ul.Mg||Ul.Lh)+".js"},Wl={},Xl=function(a,b,c,d){Bd(22);if(c){d=d||{};var e=Rl(Sl,d,a),f={ak:a,cl:b};void 0===d.Na&&(f.autoreplace=c);e(2,d.Na,f,c,0,Oa(),d.options)}},Yl=function(a,b,c,d){Bd(21);if(b&&c){d=d||{};for(var e={countryNameCode:c,destinationNumber:b,retrievalTime:Oa()},f=0;f<a.length;f++){var g=a[f];Wl[g.id]||
(g&&"AW"===g.prefix&&!e.adData&&2<=g.K.length?(e.adData={ak:g.K[0],cl:g.K[1]},Wl[g.id]=!0):g&&"UA"===g.prefix&&!e.gaData&&(e.gaData={gaWpid:g.containerId},Wl[g.id]=!0))}(e.gaData||e.adData)&&Rl(Vl,d)(d.Na,e,d.options)}},Zl=function(){var a=!1;return a},$l=function(a,b){if(a)if(Kk()){}else{if(sa(a)){var c=
Ll(a);if(!c)return;a=c}var d=void 0,e=!1,f=b.getWithConfig(M.uh);if(f&&ua(f)){d=[];for(var g=0;g<f.length;g++){var k=Ll(f[g]);k&&(d.push(k),(a.id===k.id||a.id===a.containerId&&a.containerId===k.containerId)&&(e=!0))}}if(!d||e){var l=b.getWithConfig(M.tf),n;if(l){ua(l)?n=l:n=[l];var p=b.getWithConfig(M.rf),q=b.getWithConfig(M.sf),u=b.getWithConfig(M.uf),t=b.getWithConfig(M.th),r=p||q,v=1;"UA"!==a.prefix||d||(v=5);for(var x=0;x<n.length;x++)if(x<v)if(d)Yl(d,n[x],t,{Na:r,options:u});else if("AW"===a.prefix&&
a.K[1])Zl()?Yl([a],n[x],t||"US",{Na:r,options:u}):Xl(a.K[0],a.K[1],n[x],{Na:r,options:u});else if("UA"===a.prefix)if(Zl())Yl([a],n[x],t||"US",{Na:r});else{var z=a.containerId,w=n[x],y={Na:r};Bd(23);if(w){y=y||{};var A=Rl(Tl,y,z),C={};void 0!==y.Na?C.receiver=y.Na:C.replace=w;C.ga_wpid=z;C.destination=w;A(2,Oa(),C)}}}}}};var fn=function(){var a=!0;ul(7)&&ul(9)&&ul(10)||(a=!1);var b=!0;b=!1;b&&!en()&&(a=!1);return a},en=function(){var a=!0;ul(3)&&ul(4)||(a=!1);return a};
var kn=function(a,b){var c=b.getWithConfig(M.Ja),d=b.getWithConfig(M.Ta),e=b.getWithConfig(c);if(void 0===e){var f=void 0;gn.hasOwnProperty(c)?f=gn[c]:hn.hasOwnProperty(c)&&(f=hn[c]);1===f&&(f=jn(c));sa(f)?dj()(function(){var g=dj().getByName(a).get(f);d(g)}):d(void 0)}else d(e);},ln=function(a,b){var c=a[M.Wb];gj(b+".",a[M.M]||"",void 0===c?!!a.use_anchor:"fragment"===c,!!a[M.Fb])},pn=function(a,b,c){if(Yd()&&(!c.isGtmEvent||!mn[a])){var d=
!ie(M.H),e=function(){var f,g,k=dj(),l=nn(b,"",c),n,p=l.fa._useUp;if(c.isGtmEvent||on(b,l.fa)){var q=!0;if(c.isGtmEvent){f="gtm"+sf();g=l.fa;l.gtmTrackerName&&(g.name=f);q=!1;q=!0;}q&&k(function(){var t=k.getByName(b);t&&(n=t.get("clientId"));c.isGtmEvent||k.remove(b)});k("create",a,c.isGtmEvent?g:l.fa);d&&ie(M.H)&&(d=!1,k(function(){var t=dj().getByName(c.isGtmEvent?f:b);!t||t.get("clientId")==n&&p||(c.isGtmEvent?l.kc["&gcu"]="1":l.ia["&gcu"]="1",t.set(l.kc),c.isGtmEvent?t.send("pageview"):t.send("pageview",l.ia))}));c.isGtmEvent&&k(function(){k.remove(f)})}};ce(e,M.H);ce(e,M.C);c.isGtmEvent&&
(mn[a]=!0)}},yn=function(a,b,c){function d(){var O=c.getWithConfig("custom_map");k(function(){if(!c.isGtmEvent&&Rb(O)){var K=r.ia,L=l().getByName(n),N;for(N in O)if(O.hasOwnProperty(N)&&/^(dimension|metric)\d+$/.test(N)&&void 0!=O[N]){var J=L.get(jn(O[N]));qn(K,N,J)}}})}function e(){if(r.displayfeatures){var O="_dc_gtm_"+f.replace(/[^A-Za-z0-9-]/g,"");p("require","displayfeatures",void 0,{cookieName:O})}}var f=a,g="https://www.google-analytics.com/analytics.js",k=c.isGtmEvent?fj(c.getWithConfig("gaFunctionName")):
fj();if(ra(k)){var l=dj,n;c.isGtmEvent?n=c.getWithConfig("name")||c.getWithConfig("gtmTrackerName"):n="gtag_"+f.split("-").join("_");var p=function(O){var K=[].slice.call(arguments,0);K[0]=n?n+"."+K[0]:""+K[0];k.apply(window,K)},q=function(O){var K=function(T,X){for(var S=0;X&&S<X.length;S++)p(T,X[S])},L=c.isGtmEvent,N=L?rn(r):sn(b,c);if(N){var J={};Jk()&&O&&(J._x_19=O);p("require","ec","ec.js",J);L&&N.qe&&p("set","&cu",N.qe);var I=N.action;if(L||"impressions"===I)if(K("ec:addImpression",N.gg),!L)return;
if("promo_click"===I||"promo_view"===I||L&&N.xc){var V=N.xc;K("ec:addPromo",V);if(V&&0<V.length&&"promo_click"===I){L?p("ec:setAction",I,N.Ya):p("ec:setAction",I);return}if(!L)return}"promo_view"!==I&&"impressions"!==I&&(K("ec:addProduct",N.rb),p("ec:setAction",I,N.Ya))}},u=function(O){if(O){var K={};if(Rb(O))for(var L in tn)tn.hasOwnProperty(L)&&un(tn[L],L,O[L],K);p("require","linkid",K)}},t=function(){if(Kk()){}else{var O=
c.getWithConfig(M.sh);O&&(p("require",O,{dataLayer:"dataLayer"}),p("require","render"))}},r=nn(n,b,c),v=function(O,K,L){L&&(K=""+K);r.ia[O]=K};!c.isGtmEvent&&on(n,r.fa)&&(k(function(){l()&&l().remove(n)}),vn[n]=!1);k("create",f,r.fa);if(r.fa._x_19&&!c.isGtmEvent){var x=Hk(r.fa._x_19,"/analytics.js");x&&(g=x)}if(c.isGtmEvent?r.kc._x_19:r.fa._x_19){var z=c.isGtmEvent?r.kc._x_20:r.fa._x_20;z&&!vn[n]&&(vn[n]=!0,k(kj(n,z)))}c.isGtmEvent?r.enableRecaptcha&&p("require","recaptcha","recaptcha.js"):(d(),
u(r.linkAttribution));var w=r[M.ma];w&&w[M.M]&&ln(w,n);p("set",r.kc);c.isGtmEvent&&r.enableLinkId&&p("require","linkid","linkid.js");c.isGtmEvent&&Yd()&&pn(f,n,c);var y=r.fa._x_19?r.fa._x_19:void 0;if(b===M.Rb)if(c.isGtmEvent){e();if(r.remarketingLists){var A="_dc_gtm_"+f.replace(/[^A-Za-z0-9-]/g,"");p("require","adfeatures",{cookieName:A})}q(y);p("send","pageview");r.fa._useUp&&hj(n+".")}else t(),p("send","pageview",r.ia);else b===M.ya?(t(),$l(f,c),c.getWithConfig(M.Xa)&&(ji(["aw","dc"]),hj(n+".")),
0!=r.sendPageView&&p("send","pageview",r.ia),pn(f,n,c)):b===M.Ha?kn(n,c):"screen_view"===b?p("send","screenview",r.ia):"timing_complete"===b?(r.ia.hitType="timing",v("timingCategory",r.eventCategory,!0),c.isGtmEvent?v("timingVar",r.timingVar,!0):v("timingVar",r.name,!0),v("timingValue",Ea(r.value)),void 0!==r.eventLabel&&v("timingLabel",r.eventLabel,!0),p("send",r.ia)):"exception"===b?p("send","exception",r.ia):"optimize.callback"===b||""===b&&c.isGtmEvent||("track_social"===b&&c.isGtmEvent?(r.ia.hitType=
"social",v("socialNetwork",r.socialNetwork,!0),v("socialAction",r.socialAction,!0),v("socialTarget",r.socialTarget,!0)):((c.isGtmEvent||wn[b])&&q(y),c.isGtmEvent&&e(),r.ia.hitType="event",v("eventCategory",r.eventCategory,!0),v("eventAction",r.eventAction||b,!0),void 0!==r.eventLabel&&v("eventLabel",r.eventLabel,!0),void 0!==r.value&&v("eventValue",Ea(r.value))),p("send",r.ia));var C=!1;
var F=xn;C&&(F=c.getContainerTypeLoaded("UA"));if(!F&&!c.isGtmEvent){xn=!0;C&&c.setContainerTypeLoaded("UA",!0);Zi();var D=function(){C&&c.setContainerTypeLoaded("UA",!1);c.onFailure()},E=function(){l().loaded||D()};Kk()?G(E):zb(g,E,D)}}else G(c.onFailure)},zn=function(a,b,c,d){me(function(){yn(a,b,d)},[M.H,M.C])},Bn=function(a,b){function c(f){function g(p,q){for(var u=0;u<q.length;u++){var t=q[u];if(f[t]){l[p]=f[t];break}}}function k(){if(f.category)l.category=f.category;else{for(var p="",q=0;q<
An.length;q++)void 0!==f[An[q]]&&(p&&(p+="/"),p+=f[An[q]]);p&&(l.category=p)}}var l=H(f),n=!1;if(n||b)g("id",["id","item_id","promotion_id"]),g("name",["name","item_name","promotion_name"]),g("brand",["brand","item_brand"]),g("variant",["variant","item_variant"]),g("list",["list_name","item_list_name"]),g("position",["list_position","creative_slot","index"]),
k();g("listPosition",["list_position"]);g("creative",["creative_name"]);g("list",["list_name"]);g("position",["list_position","creative_slot"]);return l}b=void 0===b?!1:b;for(var d=[],e=0;a&&e<a.length;e++)a[e]&&Rb(a[e])&&d.push(c(a[e]));return d.length?d:void 0},Cn=function(a){return ie(a)},Dn=!1;var En=!1;
var xn,vn={},mn={},gn=Object.freeze({client_id:1,client_storage:"storage",conversion_linker:"storeGac",cookie_domain:1,cookie_expires:1,cookie_flags:1,cookie_name:1,cookie_path:1,cookie_update:1,sample_rate:1,site_speed_sample_rate:1,store_gac:1,use_amp_client_id:1}),Fn=Object.freeze({_cd2l:1,_cs:1,_useUp:1,allowAnchor:1,allowLinker:1,alwaysSendReferrer:1,clientId:1,cookieDomain:1,cookieExpires:1,cookieFlags:1,cookieName:1,cookiePath:1,cookieUpdate:1,legacyCookieDomain:1,legacyHistoryImport:1,name:1,
sampleRate:1,siteSpeedSampleRate:1,storage:1,storeGac:1,useAmpClientId:1}),Gn={anonymize_ip:1},hn=Object.freeze({campaign:{content:"campaignContent",id:"campaignId",medium:"campaignMedium",name:"campaignName",source:"campaignSource",term:"campaignKeyword"},app_id:1,app_installer_id:1,app_name:1,app_version:1,currency:"currencyCode",description:"exDescription",fatal:"exFatal",language:1,non_interaction:1,page_hostname:"hostname",page_location:"location",page_path:"page",page_referrer:"referrer",page_title:"title",
screen_name:1,transport_type:"transport",user_id:1}),Hn=Object.freeze({content_id:1,event_action:1,event_category:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1}),In=Object.freeze({displayfeatures:1,enableLinkId:1,enableRecaptcha:1,eventAction:1,eventCategory:1,eventLabel:1,gaFunctionName:1,gtmEcommerceData:1,gtmTrackerName:1,linker:1,remarketingLists:1,socialAction:1,socialNetwork:1,socialTarget:1,timingVar:1,value:1}),An=Object.freeze(["item_category","item_category2",
"item_category3","item_category4","item_category5"]),tn=Object.freeze({cookie_expires:"duration",cookie_name:1,levels:1}),Jn=Object.freeze({anonymize_ip:1,conversion_linker:1,fatal:1,non_interaction:1,send_page_view:1,store_gac:1,use_amp_client_id:1}),un=function(a,b,c,d){if(void 0!==c)if(Jn[b]&&(c=Fa(c)),"anonymize_ip"!==b||c||(c=void 0),1===a)d[jn(b)]=c;else if(sa(a))d[a]=c;else for(var e in a)a.hasOwnProperty(e)&&void 0!==c[e]&&(d[a[e]]=c[e])},jn=function(a){return a&&sa(a)?a.replace(/(_[a-z])/g,
function(b){return b[1].toUpperCase()}):a},Kn={},wn=Object.freeze((Kn.checkout_progress=1,Kn.select_content=1,Kn.set_checkout_option=1,Kn[M.yb]=1,Kn[M.zb]=1,Kn[M.eb]=1,Kn[M.Sa]=1,Kn[M.fb]=1,Kn[M.ra]=1,Kn[M.Ab]=1,Kn[M.sa]=1,Kn)),Ln={},Mn=Object.freeze((Ln.checkout_progress=1,Ln.set_checkout_option=1,Ln[M.We]=1,Ln[M.yb]=1,Ln[M.zb]=1,Ln[M.eb]=1,Ln[M.ra]=1,Ln[M.Ab]=1,Ln[M.Xe]=1,Ln)),Nn={},On=Object.freeze((Nn.generate_lead=1,Nn.login=1,Nn.search=1,Nn.select_content=1,Nn.share=1,Nn.sign_up=1,Nn.view_search_results=
1,Nn[M.Sa]=1,Nn[M.fb]=1,Nn[M.sa]=1,Nn)),Pn=function(a){var b="general";Mn[a]?b="ecommerce":On[a]?b="engagement":"exception"===a&&(b="error");return b},Qn={},Rn=Object.freeze((Qn.view_search_results=1,Qn[M.Sa]=1,Qn[M.fb]=1,Qn[M.sa]=1,Qn)),qn=function(a,b,c){a.hasOwnProperty(b)||(a[b]=c)},Sn=function(a){if(ua(a)){for(var b=[],c=0;c<a.length;c++){var d=a[c];if(void 0!=d){var e=d.id,f=d.variant;void 0!=e&&void 0!=f&&b.push(String(e)+"."+String(f))}}return 0<b.length?b.join("!"):void 0}},nn=function(a,
b,c){function d(L,N){void 0!==N&&(k[L]=N)}var e=function(L){return c.getWithConfig(L)},f={},g={},k={},l={},n=Sn(e(M.oh));!c.isGtmEvent&&n&&qn(g,"exp",n);k["&gtm"]=Ok(!0);Yd()&&(l._cs=Cn);var p=e("custom_map");if(!c.isGtmEvent&&Rb(p))for(var q in p)if(p.hasOwnProperty(q)&&/^(dimension|metric)\d+$/.test(q)&&void 0!=p[q]){var u=e(String(p[q]));void 0!==u&&qn(g,q,u)}for(var t=bf(c),r=0;r<t.length;++r){var v=t[r];if(c.isGtmEvent){var x=e(v);In.hasOwnProperty(v)?f[v]=x:Fn.hasOwnProperty(v)?l[v]=x:"currencyCode"!=
v&&(k[v]=x)}else{var z=void 0;z=v!==M.aa?e(v):cf(c,v);if(Hn.hasOwnProperty(v))un(Hn[v],v,z,f);else if(Gn.hasOwnProperty(v))un(Gn[v],v,z,k);else if(hn.hasOwnProperty(v))un(hn[v],v,z,g);else if(gn.hasOwnProperty(v))un(gn[v],v,z,l);else if(/^(dimension|metric|content_group)\d+$/.test(v))un(1,v,z,g);else if(v===M.aa){if(!Dn){var w=Wa(z);w&&(g["&did"]=w)}if(En){var y=Wa(cf(c,v,1),".");y&&(g["&gdid"]=y);var A=Wa(cf(c,v,2),".");A&&(g["&edid"]=A)}}else v===M.la&&0>va(t,M.Jc)&&(l.cookieName=z+"_ga")}}!1!==
e(M.eh)&&!1!==e(M.Sb)&&fn()||(k.allowAdFeatures=!1);if(!1===e(M.za)||!en()){var C=c.isGtmEvent?"allowAdPersonalizationSignals":"allowAdFeatures";C="allowAdPersonalizationSignals";k[C]=!1}!c.isGtmEvent&&e(M.Xa)&&(l._useUp=!0);if(c.isGtmEvent){l.name=l.name||f.gtmTrackerName;var F=k.hitCallback;k.hitCallback=function(){ra(F)&&F();c.onSuccess()}}else{qn(l,"cookieDomain","auto");qn(k,"forceSSL",!0);qn(f,
"eventCategory",Pn(b));Rn[b]&&qn(g,"nonInteraction",!0);"login"===b||"sign_up"===b||"share"===b?qn(f,"eventLabel",e(M.rh)):"search"===b||"view_search_results"===b?qn(f,"eventLabel",e(M.xh)):"select_content"===b&&qn(f,"eventLabel",e(M.ih));var D=f[M.ma]||{},E=D[M.Eb];E||0!=E&&D[M.M]?l.allowLinker=!0:!1===E&&qn(l,"useAmpClientId",!1);g.hitCallback=c.onSuccess;l.name=a}
Yd()&&(k["&gcs"]=je(),ie(M.H)||(l.storage="none"),ie(M.C)||(k.allowAdFeatures=!1,l.storeGac=!1));var O=e(M.na)||e(M.qh),K=e(M.ph);if(O){c.isGtmEvent||(l._x_19=O);l._cd2l=!0;}K&&
!c.isGtmEvent&&(l._x_20=K);f.ia=g;f.kc=k;f.fa=l;return f},rn=function(a){var b=a.gtmEcommerceData;if(!b)return null;var c={};b.currencyCode&&(c.qe=b.currencyCode);if(b.impressions){c.action="impressions";var d=b.impressions;c.gg="impressions"===b.translateIfKeyEquals?Bn(d,!0):d}if(b.promoView){c.action="promo_view";var e=b.promoView.promotions;c.xc="promoView"===b.translateIfKeyEquals?Bn(e,!0):e}if(b.promoClick){c.action="promo_click";var f=b.promoClick.promotions;c.xc="promoClick"===b.translateIfKeyEquals?
Bn(f,!0):f;c.Ya=b.promoClick.actionField;return c}for(var g in b)if(b.hasOwnProperty(g)&&"translateIfKeyEquals"!==g&&"impressions"!==g&&"promoView"!==g&&"promoClick"!==g&&"currencyCode"!==g){c.action=g;var k=b[g].products;c.rb="products"===b.translateIfKeyEquals?Bn(k,!0):k;c.Ya=b[g].actionField;break}return Object.keys(c).length?c:null},sn=function(a,b){function c(t){return{id:d(M.Wa),affiliation:d(M.lh),revenue:d(M.ca),tax:d(M.kf),shipping:d(M.Ld),coupon:d(M.mh),list:d(M.Kd)||t}}for(var d=function(t){return b.getWithConfig(t)},
e=d(M.V),f,g=0;e&&g<e.length&&!(f=e[g][M.Kd]);g++);var k=d("custom_map");if(Rb(k))for(var l=0;e&&l<e.length;++l){var n=e[l],p;for(p in k)k.hasOwnProperty(p)&&/^(dimension|metric)\d+$/.test(p)&&void 0!=k[p]&&qn(n,p,n[k[p]])}var q=null,u=d(M.nh);a===M.ra||a===M.Ab?q={action:a,Ya:c(),rb:Bn(e)}:a===M.yb?q={action:"add",rb:Bn(e)}:a===M.zb?q={action:"remove",rb:Bn(e)}:a===M.sa?q={action:"detail",Ya:c(f),rb:Bn(e)}:a===M.Sa?q={action:"impressions",gg:Bn(e)}:"view_promotion"===a?q={action:"promo_view",xc:Bn(u)}:
"select_content"===a&&u&&0<u.length?q={action:"promo_click",xc:Bn(u)}:"select_content"===a?q={action:"click",Ya:{list:d(M.Kd)||f},rb:Bn(e)}:a===M.eb||"checkout_progress"===a?q={action:"checkout",rb:Bn(e),Ya:{step:a===M.eb?1:d(M.jf),option:d(M.hf)}}:"set_checkout_option"===a&&(q={action:"checkout_option",Ya:{step:d(M.jf),option:d(M.hf)}});q&&(q.qe=d(M.ba));return q},Tn={},on=function(a,b){var c=Tn[a];Tn[a]=H(b);if(!c)return!1;for(var d in b)if(b.hasOwnProperty(d)&&b[d]!==c[d])return!0;for(var e in c)if(c.hasOwnProperty(e)&&
c[e]!==b[e])return!0;return!1};var Un=!1;Un=!0;function Vn(){var a=P;return a.gcq=a.gcq||new Wn}
var Xn=function(a,b,c){Vn().register(a,b,c)},Yn=function(a,b,c,d){Vn().push("event",[b,a],c,d)},Zn=function(a,b){Vn().push("config",[a],b)},$n=function(a,b,c,d){Vn().push("get",[a,b],c,d)},ao={},bo=function(){this.status=1;this.containerConfig={};this.targetConfig={};this.remoteConfig={};this.o={};this.B=null;this.m=!1},co=function(a,b,c,d,e){this.type=a;this.B=b;this.P=c||"";this.m=d;this.o=e},Wn=function(){this.o={};this.B={};this.m=[];this.D={AW:!1,UA:!1}},eo=function(a,b){var c=Ll(b);return a.o[c.containerId]=
a.o[c.containerId]||new bo},fo=function(a,b,c){if(b){var d=Ll(b);if(d&&1===eo(a,b).status){eo(a,b).status=2;var e={};Wj&&(e.timeoutId=m.setTimeout(function(){Bd(38);Cj()},3E3));a.push("require",[e],d.containerId);ao[d.containerId]=h();if(Kk()){}else{var g=
"/gtag/js?id="+encodeURIComponent(d.containerId)+"&l=dataLayer&cx=c";Jk()&&(g+="&sign="+ef.ad);var k=("http:"!=m.location.protocol?"https:":"http:")+("//www.googletagmanager.com"+g),l=Hk(c,g)||k;zb(l)}}}},go=function(a,b,c,d){if(d.P){var e=eo(a,d.P),f=e.B;if(f){var g=H(c),k=H(e.targetConfig[d.P]),l=H(e.containerConfig),n=H(e.remoteConfig),p=H(a.B),q=zf("gtm.uniqueEventId"),u=Ll(d.P).prefix,t=Qa(function(){var v=g[M.Cb];v&&G(v)}),r=$e(Ze(af(Ye(We(Xe(Ve(Ne(Me(g),k),l),n),p),function(){
jk(q,u,"2");Un&&t()}),function(){jk(q,u,"3");Un&&t()}),function(v,x){a.D[v]=x}),function(v){return a.D[v]});try{jk(q,u,"1");f(d.P,b,d.B,r)}catch(v){jk(q,u,"4");}}}};
Wn.prototype.register=function(a,b,c){var d=eo(this,a);if(3!==d.status){d.B=b;d.status=3;c&&(H(d.remoteConfig,c),d.remoteConfig=c);var e=Ll(a),f=ao[e.containerId];if(void 0!==f){var g=P[e.containerId].bootstrap,k=e.prefix.toUpperCase();P[e.containerId]._spx&&(k=k.toLowerCase());var l=zf("gtm.uniqueEventId"),n=k,p=h()-g;if(Wj&&!Hj[l]){l!==Dj&&(yj(),Dj=l);var q=n+"."+Math.floor(g-f)+"."+Math.floor(p);Lj=Lj?Lj+","+q:"&cl="+q}delete ao[e.containerId]}this.flush()}};
Wn.prototype.push=function(a,b,c,d){var e=Math.floor(h()/1E3);fo(this,c,b[0][M.na]||this.B[M.na]);c&&eo(this,c).m&&(d=!1);this.m.push(new co(a,e,c,b,d));d||this.flush()};Wn.prototype.insert=function(a,b,c){var d=Math.floor(h()/1E3);0<this.m.length?this.m.splice(1,0,new co(a,d,c,b,!1)):this.m.push(new co(a,d,c,b,!1))};
Wn.prototype.flush=function(a){for(var b=this,c=[],d=!1,e={};this.m.length;){var f=this.m[0];if(f.o)!f.P||eo(this,f.P).m?(f.o=!1,this.m.push(f)):c.push(f),this.m.shift();else{switch(f.type){case "require":if(3!==eo(this,f.P).status&&!a){this.m.push.apply(this.m,c);return}Wj&&m.clearTimeout(f.m[0].timeoutId);break;case "set":Aa(f.m[0],function(u,t){H(Ua(u,t),b.B)});break;case "config":e.Ga={};Aa(f.m[0],function(u){return function(t,r){H(Ua(t,r),u.Ga)}}(e));var g=!!e.Ga[M.Sc];delete e.Ga[M.Sc];var k=
eo(this,f.P),l=Ll(f.P),n=l.containerId===l.id;g||(n?k.containerConfig={}:k.targetConfig[f.P]={});k.m&&g||go(this,M.ya,e.Ga,f);k.m=!0;delete e.Ga[M.bc];n?H(e.Ga,k.containerConfig):H(e.Ga,k.targetConfig[f.P]);d=!0;break;case "event":e.Cc={};Aa(f.m[0],function(u){return function(t,r){H(Ua(t,r),u.Cc)}}(e));go(this,f.m[1],e.Cc,f);break;case "get":var p={},q=(p[M.Ja]=f.m[0],p[M.Ta]=f.m[1],p);go(this,M.Ha,q,f)}this.m.shift();ho(this,f)}e={Ga:e.Ga,Cc:e.Cc}}this.m.push.apply(this.m,c);d&&this.flush()};
var ho=function(a,b){if("require"!==b.type)if(b.P)for(var c=a.getCommandListeners(b.P)[b.type]||[],d=0;d<c.length;d++)c[d]();else for(var e in a.o)if(a.o.hasOwnProperty(e)){var f=a.o[e];if(f&&f.o)for(var g=f.o[b.type]||[],k=0;k<g.length;k++)g[k]()}};Wn.prototype.getRemoteConfig=function(a){return eo(this,a).remoteConfig};Wn.prototype.getCommandListeners=function(a){return eo(this,a).o};var io=function(a,b,c){var d={event:b,"gtm.element":a,"gtm.elementClasses":Lb(a,"className"),"gtm.elementId":a["for"]||Fb(a,"id")||"","gtm.elementTarget":a.formTarget||Lb(a,"target")||""};c&&(d["gtm.triggers"]=c.join(","));d["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||Lb(a,"href")||a.src||a.code||a.codebase||"";return d},jo=function(a){P.hasOwnProperty("autoEventsSettings")||(P.autoEventsSettings={});var b=P.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});
return b[a]},ko=function(a,b,c){jo(a)[b]=c},lo=function(a,b,c,d){var e=jo(a),f=Pa(e,b,d);e[b]=c(f)},mo=function(a,b,c){var d=jo(a);return Pa(d,b,c)};var wo=!1,xo=[];function yo(){if(!wo){wo=!0;for(var a=0;a<xo.length;a++)G(xo[a])}}var zo=function(a){wo?G(a):xo.push(a)};function Ao(a,b){a=String(a);b=String(b);var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var Bo=new ya;function Co(a,b,c){var d=c?"i":void 0;try{var e=String(b)+d,f=Bo.get(e);f||(f=new RegExp(b,d),Bo.set(e,f));return f.test(a)}catch(g){return!1}}
function Do(a,b){function c(g){var k=Zf(g),l=Xf(k,"protocol"),n=Xf(k,"host",!0),p=Xf(k,"port"),q=Xf(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==p||"https"==l&&"443"==p)l="web",p="default";return[l,n,p,q]}for(var d=c(String(a)),e=c(String(b)),f=0;f<d.length;f++)if(d[f]!==e[f])return!1;return!0}
function Eo(a){return Fo(a)?1:0}
function Fo(a){var b=a.arg0,c=a.arg1;if(a.any_of&&ua(c)){for(var d=0;d<c.length;d++){var e=H(a,{});H({arg1:c[d],any_of:void 0},e);if(Eo(e))return!0}return!1}switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var f;a:{if(b){var g=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var k=0;k<g.length;k++)if(b[g[k]]){f=b[g[k]](c);break a}}catch(n){}}f=!1}return f;case "_ew":return Ao(b,c);case "_eq":return String(b)==
String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var l;l=String(b).split(",");return 0<=va(l,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":return Co(b,c,a.ignore_case);case "_sw":return 0==String(b).indexOf(String(c));case "_um":return Do(b,c)}return!1};Object.freeze({dl:1,id:1});var Go={},Ho=function(a,b){b=b.toString().split(",");for(var c=0;c<b.length;c++){var d=Go[b[c]]||[];Go[b[c]]=d;0>va(d,a)&&d.push(a)}},Io=function(a){Aa(Go,function(b,c){var d=va(c,a);0<=d&&c.splice(d,1)})};var Jo="HA GF G UA AW DC".split(" "),Ko=!1;Ko=!0;var Lo=!1,Mo=!1;function No(a,b){var c={event:a};b&&(c.eventModel=H(b),b[M.Cb]&&(c.eventCallback=b[M.Cb]),b[M.Mc]&&(c.eventTimeout=b[M.Mc]));return c}function Oo(a){a.hasOwnProperty("gtm.uniqueEventId")||Object.defineProperty(a,"gtm.uniqueEventId",{value:sf()});return a["gtm.uniqueEventId"]}
function Po(){if(!Lo&&!P.gtagRegistered){Lo=P.gtagRegistered=!0;P.addTargetToGroup=function(c){Ho(c,"default")};}return Lo}
var Qo={config:function(a){var b,c=Oo(a);if(2>a.length||!sa(a[1]))return;var d={};if(2<a.length){if(void 0!=a[2]&&!Rb(a[2])||3<a.length)return;d=a[2]}var e=Ll(a[1]);if(!e)return;Io(e.id);Ho(e.id,d[M.Pd]||"default");delete d[M.Pd];Mo||Bd(43);if(Po()&&-1!==va(Jo,e.prefix)){"G"===e.prefix&&(d[M.bc]=!0);Ko&&delete d[M.Cb];Zn(d,e.id);return}Cf("gtag.targets."+e.id,void 0);Cf("gtag.targets."+e.id,H(d));var f={};f[M.kb]=e.id;b=No(M.ya,f);b["gtm.uniqueEventId"]=c;
return b},consent:function(a){function b(){Po()&&H(a[2],{subcommand:a[1]})}if(3===a.length){Bd(39);var c=sf(),d=a[1];"default"===d?(b(),fe(a[2])):"update"===d&&(b(),he(a[2],c))}},event:function(a){var b=a[1];if(!(2>a.length)&&sa(b)){var c;if(2<a.length){if(!Rb(a[2])&&void 0!=a[2]||3<a.length)return;c=a[2]}var d=No(b,c),e=Oo(a);d["gtm.uniqueEventId"]=e;var f;var g=c&&c[M.kb];void 0===g&&(g=zf(M.kb,2),void 0===g&&(g="default"));if(sa(g)||ua(g)){for(var k=g.toString().replace(/\s+/g,
"").split(","),l=[],n=0;n<k.length;n++)if(0<=k[n].indexOf("-"))l.push(k[n]);else{var p=Go[k[n]];p&&p.length&&(l=l.concat(p))}f=Nl(l)}else f=void 0;var q=f;if(!q)return;for(var u=Po(),t=[],r=0;u&&r<q.length;r++){var v=q[r];if(-1!==va(Jo,v.prefix)){var x=H(c);"G"===v.prefix&&(x[M.bc]=!0);Ko&&delete x[M.Cb];Yn(b,x,v.id)}t.push(v.id)}d.eventModel=d.eventModel||{};0<q.length?d.eventModel[M.kb]=t.join():delete d.eventModel[M.kb];Mo||Bd(43);return d}},get:function(a){
Bd(53);if(4!==a.length||!sa(a[1])||!sa(a[2])||!ra(a[3]))return;var b=Ll(a[1]),c=String(a[2]),d=a[3];if(!b)return;Mo||Bd(43);if(!Po()||-1===va(Jo,b.prefix))return;sf();var e={};ok(H((e[M.Ja]=c,e[M.Ta]=d,e)));$n(c,function(f){G(function(){return d(f)})},b.id);},js:function(a){if(2==a.length&&a[1].getTime){Mo=!0;Po();var b={};return b.event="gtm.js",b["gtm.start"]=a[1].getTime(),b["gtm.uniqueEventId"]=Oo(a),b}},policy:function(){},set:function(a){var b;2==a.length&&Rb(a[1])?
b=H(a[1]):3==a.length&&sa(a[1])&&(b={},Rb(a[2])||ua(a[2])?b[a[1]]=H(a[2]):b[a[1]]=a[2]);if(b){if(sf(),Po()){H(b);var c=H(b);Vn().push("set",[c])}b._clear=!0;return b}}},Ro={policy:!0};var So=function(a,b){var c=a.hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}},Uo=function(a){var b=To(),c=b&&b.hide;c&&c.end&&(c[a]=!0)};var kp=function(a){if(jp(a))return a;this.m=a};kp.prototype.ri=function(){return this.m};var jp=function(a){return!a||"object"!==Pb(a)||Rb(a)?!1:"getUntrustedUpdateValue"in a};kp.prototype.getUntrustedUpdateValue=kp.prototype.ri;var lp=[],mp=!1,np=!1,op=function(a){return m["dataLayer"].push(a)},pp=function(a,b){var c=P["dataLayer"],d=c?c.subscribers:1,e=0,f=!1,g=void 0;b&&(g=m.setTimeout(function(){f||(f=!0,a());g=void 0},b));return function(){++e===d&&(g&&(m.clearTimeout(g),g=void 0),f||(a(),f=!0))}};
function qp(a){var b=a._clear;Aa(a,function(d,e){"_clear"!==d&&(b&&Cf(d,void 0),Cf(d,e))});nf||(nf=a["gtm.start"]);var c=a["gtm.uniqueEventId"];if(!a.event)return!1;c||(c=sf(),a["gtm.uniqueEventId"]=c,Cf("gtm.uniqueEventId",c));return Fk(a)}function rp(){var a=lp[0];if(null==a||"object"!==typeof a)return!1;if(a.event)return!0;if(Da(a)){var b=a[0];if("config"===b||"event"===b||"js"===b)return!0}return!1}
function sp(){for(var a=!1;!np&&0<lp.length;){if(!mp&&rp()){var b={},c=(b.event="gtm.init_consent",b),d={},e=(d.event="gtm.init",d),f=lp[0]["gtm.uniqueEventId"];f&&(c["gtm.uniqueEventId"]=f-2,e["gtm.uniqueEventId"]=f-1);lp.unshift(c,e);mp=!0}np=!0;delete wf.eventModel;yf();var g=lp.shift();if(null!=g){var k=jp(g);if(k){var l=g;g=jp(l)?l.getUntrustedUpdateValue():void 0;for(var n=["gtm.allowlist",
"gtm.blocklist","gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],p=0;p<n.length;p++){var q=n[p],u=zf(q,1);if(ua(u)||Rb(u))u=H(u);xf[q]=u}}try{if(ra(g))try{g.call(Af)}catch(A){}else if(ua(g)){var t=g;if(sa(t[0])){var r=t[0].split("."),v=r.pop(),x=t.slice(1),z=zf(r.join("."),2);if(void 0!==z&&null!==z)try{z[v].apply(z,x)}catch(A){}}}else{if(Da(g)){a:{var w=g;if(w.length&&sa(w[0])){var y=Qo[w[0]];if(y&&(!k||!Ro[w[0]])){g=y(w);break a}}g=void 0}if(!g){np=!1;continue}}a=qp(g)||a}}finally{k&&yf(!0)}}np=
!1}return!a}function tp(){var b=sp();try{So(m["dataLayer"],ef.I)}catch(c){}return b}
var vp=function(){var a=vb("dataLayer",[]),b=vb("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};Ri(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});zo(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||0)+1;var c=a.push;a.push=function(){var e;if(0<P.SANDBOXED_JS_SEMAPHORE){e=[];for(var f=0;f<arguments.length;f++)e[f]=new kp(arguments[f])}else e=[].slice.call(arguments,0);var g=c.apply(a,e);lp.push.apply(lp,e);if(300<
this.length)for(Bd(4);300<this.length;)this.shift();var k="boolean"!==typeof g||g;return sp()&&k};var d=a.slice(0);lp.push.apply(lp,d);if(up()){G(tp)}},up=function(){var a=!0;return a};var wp={};wp.Wc=new String("undefined");var Jp=m.clearTimeout,Kp=m.setTimeout,R=function(a,b,c,d){if(Kk()){b&&G(b)}else return zb(a,b,c,d)},Lp=function(){return new Date},Mp=function(){return m.location.href},Np=function(a){return Xf(Zf(a),"fragment")},Op=function(a){return Yf(Zf(a))},Pp=function(a,b){return zf(a,b||2)},Qp=function(a,b,c){var d;b?(a.eventCallback=b,c&&(a.eventTimeout=c),d=op(a)):d=op(a);return d},Rp=function(a,b){m[a]=b},U=function(a,b,
c){b&&(void 0===m[a]||c&&!m[a])&&(m[a]=b);return m[a]},Sp=function(a,b,c){return Ag(a,b,void 0===c?!0:!!c)},Tp=function(a,b,c){return 0===Og(a,b,c)},Up=function(a,b){if(Kk()){b&&G(b)}else Bb(a,b)},Vp=function(a){return!!mo(a,"init",!1)},Wp=function(a){ko(a,"init",!0)},Xp=function(a){var b=lf,c="?id="+encodeURIComponent(a)+"&l=dataLayer";Jk()&&(c+="&sign="+ef.ad,ub&&(b=ub.replace(/^(?:https?:\/\/)?/i,"").split(/[?#]/)[0]));
var d=Pl("https://","http://",b+c);R(d)},Yp=function(a,b,c){Wj&&(Sb(a)||kk(c,b,a))};var vq=encodeURI,Y=encodeURIComponent,wq=Cb;var xq=function(a,b){if(!a)return!1;var c=Xf(Zf(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var yq=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};function gs(){return m.gaGlobal=m.gaGlobal||{}}var hs=function(){var a=gs();a.hid=a.hid||xa();return a.hid},is=function(a,b){var c=gs();if(void 0==c.vid||b&&!c.from_cookie)c.vid=a,c.from_cookie=b};var Js=function(){if(ra(m.__uspapi)){var a="";try{m.__uspapi("getUSPData",1,function(b,c){if(c&&b){var d=b.uspString;d&&RegExp("^[\\da-zA-Z-]{1,20}$").test(d)&&(a=d)}})}catch(b){}return a}};var it=window,jt=document,kt=function(a){var b=it._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===it["ga-disable-"+a])return!0;try{var c=it.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(f){}for(var d=wg("AMP_TOKEN",String(jt.cookie),!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return jt.getElementById("__gaOptOutExtension")?!0:!1};var lt={};function ot(a){delete a.eventModel[M.bc];qt(a.eventModel)}var qt=function(a){Aa(a,function(c){"_"===c.charAt(0)&&delete a[c]});var b=a[M.Ka]||{};Aa(b,function(c){"_"===c.charAt(0)&&delete b[c]})};var tt=function(a,b,c){Yn(b,c,a)},ut=function(a,b,c){Yn(b,c,a,!0)},yt=function(a,b){};
function vt(a,b){}var Z={g:{}};





Z.g.e=["google"],function(){(function(a){Z.__e=a;Z.__e.h="e";Z.__e.isVendorTemplate=!0;Z.__e.priorityOverride=0})(function(a){var b=String(Ff(a.vtp_gtmEventId,"event"));a.vtp_gtmCachedValues&&(b=String(a.vtp_gtmCachedValues.event));return b})}();
Z.g.v=["google"],function(){(function(a){Z.__v=a;Z.__v.h="v";Z.__v.isVendorTemplate=!0;Z.__v.priorityOverride=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=Pp(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1),d=void 0!==c?c:a.vtp_defaultValue;Yp(d,"v",a.vtp_gtmEventId);return d})}();
Z.g.rep=["google"],function(){(function(a){Z.__rep=a;Z.__rep.h="rep";Z.__rep.isVendorTemplate=!0;Z.__rep.priorityOverride=0})(function(a){var b;switch(Ll(a.vtp_containerId).prefix){case "AW":b=Bm;break;case "DC":b=Rm;break;case "GF":b=Wm;break;case "HA":b=an;break;case "UA":b=zn;break;default:G(a.vtp_gtmOnFailure);return}G(a.vtp_gtmOnSuccess);Xn(a.vtp_containerId,b,a.vtp_remoteConfig||{})})}();

Z.g.cid=["google"],function(){(function(a){Z.__cid=a;Z.__cid.h="cid";Z.__cid.isVendorTemplate=!0;Z.__cid.priorityOverride=0})(function(){return ef.I})}();







Z.g.get=["google"],function(){(function(a){Z.__get=a;Z.__get.h="get";Z.__get.isVendorTemplate=!0;Z.__get.priorityOverride=0})(function(a){var b=a.vtp_settings;(a.vtp_deferrable?ut:tt)(String(b.streamId),String(a.vtp_eventName),b.eventParameters||{});a.vtp_gtmOnSuccess()})}();





Z.g.gtagua=["google"],function(){(function(a){Z.__gtagua=a;Z.__gtagua.h="gtagua";Z.__gtagua.isVendorTemplate=!0;Z.__gtagua.priorityOverride=0})(function(a){G(a.vtp_gtmOnSuccess)})}();


var zt={};zt.dataLayer=Af;zt.callback=function(a){qf.hasOwnProperty(a)&&ra(qf[a])&&qf[a]();delete qf[a]};zt.bootstrap=0;zt._spx=!1;
function At(){P[ef.I]=zt;Ra(rf,Z.g);Ic=Tc}
function Bt(){var a=!1;a&&$i("INIT");Gd().o();P=m.google_tag_manager=m.google_tag_manager||{};ql();
Nh.enable_gbraid_cookie_write=!0;var b=!!P[ef.I];if(b){var c=P.zones;c&&c.unregisterChild(ef.I);}else{for(var d=data.resource||{},e=d.macros||[],f=0;f<e.length;f++)Ac.push(e[f]);
for(var g=d.tags||[],k=0;k<g.length;k++)Dc.push(g[k]);for(var l=d.predicates||[],n=0;n<l.length;n++)Cc.push(l[n]);for(var p=d.rules||[],q=0;q<p.length;q++){for(var u=p[q],t={},r=0;r<u.length;r++)t[u[r][0]]=Array.prototype.slice.call(u[r],1);Bc.push(t)}Fc=Z;Gc=Eo;At();vp();Mi=!1;Ni=0;if("interactive"==B.readyState&&!B.createEventObject||"complete"==B.readyState)Pi();else{Db(B,"DOMContentLoaded",Pi);Db(B,"readystatechange",Pi);if(B.createEventObject&&B.documentElement.doScroll){var v=!0;try{v=!m.frameElement}catch(A){}v&&
Qi()}Db(m,"load",Pi)}wo=!1;"complete"===B.readyState?yo():Db(m,"load",yo);Wj&&m.setInterval(Qj,864E5);
of=(new Date).getTime();zt.bootstrap=of;if(a){var y=aj("INIT");}}}
(function(a){function b(t){if(null==t||0===t.length)return!1;var r=Number(t),v=h();return r<v+3E5&&r>v-9E5}if(!m["__TAGGY_INSTALLED"]){var c=!1;if(B.referrer){var d=Zf(B.referrer);c="cct.google"===Wf(d,"host")}if(!c){var e=Ag("googTaggyReferrer");c=e.length&&e[0].length}c&&(m["__TAGGY_INSTALLED"]=!0,zb("https://cct.google/taggy/agent.js"))}var g=function(t){var r="GTM",v="GTM";r="OGT",v="GTAG";var x=m["google.tagmanager.debugui2.queue"];x||(x=[],m["google.tagmanager.debugui2.queue"]=x,zb("https://"+ef.xd+"/debug/bootstrap?id="+ef.I+"&src="+v+
"&cond="+t+"&gtm="+Ok()));var z={messageType:"CONTAINER_STARTING",data:{scriptSource:ub,containerProduct:r,debug:!1,id:ef.I}};z.data.resume=function(){a()};ef.Pg&&(z.data.initialPublish=!0);x.push(z)},k=void 0,l=Xf(m.location,"query",!1,void 0,"gtm_debug"),n=!0;n=!1;n&&"x"===l&&(k=1);!k&&b(l)&&(k=2);if(!k&&B.referrer){var p=Zf(B.referrer);"tagassistant.google.com"===
Wf(p,"host")&&(k=3)}if(!k){var q=Ag("__TAG_ASSISTANT");q.length&&q[0].length&&(k=4)}if(!k&&B.documentElement.hasAttribute("data-tag-assistant-present")){k=5;var u=B.documentElement.getAttribute("data-tag-assistant-present");k=b(u)?5:void 0;}k&&ub?g(k):a()})(Bt);

})()
