(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var k=this||self;function aa(){}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function ca(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}} 
function n(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?n=ba:n=ca;return n.apply(null,arguments)}function da(a,b){function c(){}c.prototype=b.prototype;a.G=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.I=function(d,e,h){for(var g=Array(arguments.length-2),f=2;f<arguments.length;f++)g[f-2]=arguments[f];return b.prototype[e].apply(d,g)}};const p=Symbol(void 0);function q(a){if(!Array.isArray(a))return a;Object.isFrozen(a)||(p?a[p]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function r(a,b){Array.prototype.forEach.call(a,b,void 0)};function t(a){t[" "](a);return a}t[" "]=aa;var ia={},u=null;var ja="function"===typeof Uint8Array;function ka(a){return null!==a&&"object"===typeof a&&a.constructor===Object}function la(a,b){if(null!=a)return Array.isArray(a)||ka(a)?ma(a,b):b(a)}function ma(a,b){if(Array.isArray(a)){var c=Array(a.length);for(let e=0;e<a.length;e++)c[e]=la(a[e],b);if(a){var d;p?d=a[p]:d=a.g;a=null==d?0:d}else a=0;a&1&&q(c);return c}d={};for(c in a)d[c]=la(a[c],b);return d} 
function na(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(ja&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!u){u={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var h=c.concat(d[e].split(""));ia[e]=h;for(var g=0;g<h.length;g++){var f=h[g];void 0===u[f]&&(u[f]=g)}}}b=ia[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=h=0;h<a.length-2;h+=3){var l=a[h],m=a[h+1]; 
f=a[h+2];g=b[l>>2];l=b[(l&3)<<4|m>>4];m=b[(m&15)<<2|f>>6];f=b[f&63];c[e++]=g+l+m+f}g=0;f=d;switch(a.length-h){case 2:g=a[h+1],f=b[(g&15)<<2]||d;case 1:a=a[h],c[e]=b[a>>2]+b[(a&3)<<4|g>>4]+f+d}a=c.join("")}return a;default:return a}};let oa;function x(a,b,c){var d=oa;oa=null;a||(a=d);d=this.constructor.K;a||(a=d?[d]:[]);this.j=(d?0:-1)-(this.constructor.J||0);this.g=null;this.h=a;a:{d=this.h.length;a=d-1;if(d&&(d=this.h[a],ka(d))){this.l=a-this.j;this.i=d;break a}void 0!==b&&-1<b?(this.l=Math.max(b,a+1-this.j),this.i=null):this.l=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.l?(a+=this.j,(d=this.h[a])?q(d):this.h[a]=y):(pa(this),(d=this.i[a])?q(d):this.i[a]=y)}const y=Object.freeze(q([])); 
function pa(a){let b=a.l+a.j;a.h[b]||(a.i=a.h[b]={})}function A(a,b,c=!1){return-1===b?null:c||b>=a.l?a.i?a.i[b]:void 0:a.h[b+a.j]}function B(a,b,c){a=A(a,b);return null==a?c:a}function C(a,b){a=A(a,b);a=null==a?a:!!a;return null==a?!1:a}function qa(a){var b=ra;a.g||(a.g={});if(!a.g[1]){let c=A(a,1,!1);c&&(a.g[1]=new b(c))}return a.g[1]} 
function sa(a){var b=ta;a.g||(a.g={});var c=a.g[1];if(!c){var d=A(a,1,!1);null==d&&(d=y);d===y&&(c=d=q([]),1>=a.l?(pa(a),a.i[1]=c):a.h[1+a.j]=c);c=[];for(let e=0;e<d.length;e++)c[e]=new b(d[e]);a.g[1]=c}return c}x.prototype.toJSON=function(){const a=D(this);return ma(a,na)};function D(a){if(a.g)for(let b in a.g){const c=a.g[b];if(Array.isArray(c))for(let d=0;d<c.length;d++)c[d]&&D(c[d]);else c&&D(c)}return a.h}x.prototype.toString=function(){return D(this).toString()};var ra=class extends x{constructor(a){super(a,-1,ua)}},ta=class extends x{constructor(a){super(a)}},ua=[1];var va=class extends x{constructor(a){super(a)}};var G=class{constructor(a,b){this.g=b===F?a:""}};G.prototype.i=!0;G.prototype.h=function(){return this.g.toString()};G.prototype.toString=function(){return this.g.toString()};function wa(a){return a instanceof G&&a.constructor===G?a.g:"type_error:SafeUrl"}var xa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,F={};/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var ya=class{};class za extends ya{constructor(a){super();this.g=a}toString(){return this.g}}var Aa=new za("about:invalid#zTSz");class Ba{constructor(a){this.F=a}}function H(a){return new Ba(b=>b.substr(0,a.length+1).toLowerCase()===a+":")}const Ca=new Ba(a=>/^[^:]*([/?#]|$)/.test(a));var Da=H("http"),Ea=H("https"),Fa=H("ftp"),Ga=H("mailto");const Ha=[H("data"),Da,Ea,Ga,Fa,Ca];function Ia(a=Ha){for(let b=0;b<a.length;++b){const c=a[b];if(c instanceof Ba&&c.F("#"))return new za("#")}}function Ja(a=Ha){return Ia(a)||Aa};function Ka(a){if(a instanceof ya)if(a instanceof za)a=a.g;else throw Error("");else a=wa(a);return a};function La(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}};var Ma={capture:!0},Na={passive:!0},Oa=La(function(){let a=!1;try{const b=Object.defineProperty({},"passive",{get:function(){a=!0}});k.addEventListener("test",null,b)}catch(b){}return a});function I(a,b,c,d){if(a.addEventListener){var e=a.addEventListener;d=d?d.passive&&Oa()?d:d.capture||!1:!1;e.call(a,b,c,d)}};function Pa(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)Pa(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))};function Qa(){var a=J;try{var b;if(b=!!a&&null!=a.location.href)a:{try{t(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}}let K=[];const Ra=()=>{const a=K;K=[];for(const b of a)try{b()}catch(c){}};var Sa=a=>{var b=L;"complete"===b.readyState||"interactive"===b.readyState?(K.push(a),1==K.length&&(window.Promise?Promise.resolve().then(Ra):window.setImmediate?setImmediate(Ra):setTimeout(Ra,0))):b.addEventListener("DOMContentLoaded",a)};function Ta(a=null){return a&&"23"===a.getAttribute("data-jc")?a:document.querySelector('[data-jc="23"]')} 
function Ua(){if(!(.01<Math.random())){var a=Ta(document.currentScript);a=`https://${"pagead2.googlesyndication.com"}/pagead/gen_204?id=jca&jc=${23}&version=${a&&a.getAttribute("data-jc-version")||"unknown"}&sample=${.01}`;var b=window,c;if(c=b.navigator)c=b.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;if(c&&b.navigator.sendBeacon)b.navigator.sendBeacon(a);else{b.google_image_requests||(b.google_image_requests=[]);var d;c=b.document;c=void 0===c?document:c;var e="IMG";"application/xhtml+xml"=== 
(null==(d=c)?void 0:d.contentType)&&(e=e.toLowerCase());d=c.createElement(e);d.src=a;b.google_image_requests.push(d)}}};var L=document,M=window;const Va=[Da,Ea,Ga,Fa,Ca,H("market"),H("itms"),H("intent"),H("itms-appss")]; 
var Xa=()=>{var a=`${Wa()?"http:":"https:"}//${"pagead2.googlesyndication.com"}/pagead/gen_204`;return b=>{b={id:"unsafeurl",ctx:625,url:b};var c=[];for(d in b)Pa(d,b[d],c);var d=c.join("&");if(d){b=a.indexOf("#");0>b&&(b=a.length);c=a.indexOf("?");if(0>c||c>b){c=b;var e=""}else e=a.substring(c+1,b);b=[a.substr(0,c),e,a.substr(b)];c=b[1];b[1]=d?c?c+"&"+d:d:c;d=b[0]+(b[1]?"?"+b[1]:"")+b[2]}else d=a;navigator.sendBeacon&&navigator.sendBeacon(d,"")}};var Ya=(a,b)=>{if(a)for(let c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)},Wa=()=>{var a=void 0===a?M:a;return"http:"===a.location.protocol},Za=!!window.google_async_iframe_id;let J=Za&&window.parent||window;var $a=()=>{var a=L;try{return a.querySelectorAll("*[data-ifc]")}catch(b){return[]}},ab=(a,b)=>{a&&Ya(b,(c,d)=>{a.style[d]=c})},bb=a=>{var b=L.body;const c=document.createDocumentFragment(),d=a.length;for(let e=0;e<d;++e)c.appendChild(a[e]);b.appendChild(c)};var cb=(a=[])=>{k.google_logging_queue||(k.google_logging_queue=[]);k.google_logging_queue.push([12,a])};let N=null;var db=()=>{const a=k.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()},eb=()=>{const a=k.performance;return a&&a.now?a.now():null};class fb{constructor(a,b){var c=eb()||db();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0}};const O=k.performance,gb=!!(O&&O.mark&&O.measure&&O.clearMarks),P=La(()=>{var a;if(a=gb){var b;if(null===N){N="";try{a="";try{a=k.top.location.hash}catch(c){a=k.location.hash}a&&(N=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=N;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function hb(a){a&&O&&P()&&(O.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),O.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))} 
class ib{constructor(){var a=Q;this.g=[];this.i=a||k;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.g=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.h=P()||(null!=b?b:1>Math.random())}start(a,b){if(!this.h)return null;a=new fb(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;O&&P()&&O.mark(b);return a}end(a){if(this.h&&"number"===typeof a.value){a.duration=(eb()||db())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;O&&P()&&O.mark(b);!this.h||2048<this.g.length|| 
this.g.push(a)}}};if(Za&&!Qa()){let a="."+L.domain;try{for(;2<a.split(".").length&&!Qa();)L.domain=a=a.substr(a.indexOf(".")+1),J=window.parent}catch(b){}Qa()||(J=window)}const Q=J,R=new ib;var jb=()=>{Q.google_measure_js_timing||(R.h=!1,R.g!=R.i.google_js_reporting_queue&&(P()&&r(R.g,hb),R.g.length=0))};"number"!==typeof Q.google_srt&&(Q.google_srt=Math.random());"complete"==Q.document.readyState?jb():R.h&&I(Q,"load",()=>{jb()});var kb=a=>{I(M,"message",b=>{let c;try{c=JSON.parse(b.data)}catch(d){return}!c||"ig"!==c.googMsgType||a(c,b)})};function S(){this.h=this.h;this.i=this.i}S.prototype.h=!1;function lb(a){a.h||(a.h=!0,a.j())}S.prototype.j=function(){if(this.i)for(;this.i.length;)this.i.shift()()};function X(a,b,c){S.call(this);this.l=a;this.B=b||0;this.o=c;this.u=n(this.A,this)}da(X,S);X.prototype.g=0;X.prototype.j=function(){X.G.j.call(this);0!=this.g&&k.clearTimeout(this.g);this.g=0;delete this.l;delete this.o}; 
X.prototype.start=function(a){0!=this.g&&k.clearTimeout(this.g);this.g=0;var b=this.u;a=void 0!==a?a:this.B;if("function"!==typeof b)if(b&&"function"==typeof b.handleEvent)b=n(b.handleEvent,b);else throw Error("Invalid listener argument");this.g=2147483647<Number(a)?-1:k.setTimeout(b,a||0)};X.prototype.A=function(){this.g=0;this.l&&this.l.call(this.o)};const mb={display:"inline-block",position:"absolute"},nb={display:"none",width:"100%",height:"100%",top:"0",left:"0"},Y=(a,b)=>{a&&(a.style.display=b?"inline-block":"none")};function ob(a=""){const b={top:0,right:0,bottom:0,left:0};a&&(a=a.split(","),4===a.length&&a.reduce((c,d)=>c&&!isNaN(+d),!0)&&([b.top,b.right,b.bottom,b.left]=a.map(c=>+c)));return b} 
function pb(a,b,c=2147483647){const d=L.createElement("div");ab(d,Object.assign(Object.assign(Object.assign({},mb),{"z-index":String(c)}),b));C(a.data,10)&&I(d,"click",aa);if(C(a.data,11)){a=b=L.createElement("a");c=Xa();const e=Ja(Va);e===Aa&&c("#");c=new G(Ka(e),F);c instanceof G||c instanceof G||(c="object"==typeof c&&c.i?c.h():String(c),xa.test(c)||(c="about:invalid#zClosurez"),c=new G(c,F));a.href=wa(c);b.appendChild(d);return b}return d} 
function qb(a,b){var c,d,e,h,g=window;switch(B(b.m,5,1)){case 2:null===(d=null===(c=g.AFMA_Communicator)||void 0===c?void 0:c.addEventListener)||void 0===d?void 0:d.call(c,"onshow",()=>{Z(a,b)});break;case 10:I(M,"i-creative-view",()=>{Z(a,b)});break;case 4:I(L,"DOMContentLoaded",()=>{Z(a,b)});break;case 8:kb(f=>{f.rr&&Z(a,b)});break;case 9:"IntersectionObserver"in M&&(g=new IntersectionObserver(f=>{for(const l of f)if(0<l.intersectionRatio){Z(a,b);break}}),g.observe(L.body),a.H.push(g));break;case 11:null=== 
(h=null===(e=g.AFMA_Communicator)||void 0===e?void 0:e.addEventListener)||void 0===h?void 0:h.call(e,"onAdVisibilityChanged",()=>{Z(a,b)})}}function rb(a,b){b=ob(b);const c=B(a.data,9,0);a.i=[{width:"100%",height:b.top+c+"px",top:-c+"px",left:"0"},{width:b.right+c+"px",height:"100%",top:"0",right:-c+"px"},{width:"100%",height:b.bottom+c+"px",bottom:-c+"px",left:"0"},{width:b.left+c+"px",height:"100%",top:"0",left:-c+"px"}].map(d=>pb(a,d,9019))} 
function sb(a){var b=0;for(const d of a.B){const e=d.m,h=a.u[B(e,5,1)];d.s||void 0===h||(b=Math.max(b,h+B(e,2,0)))}a.j&&lb(a.j);b-=Date.now();const c=a.g;0<b?(Y(c,!0),a.j=new X(()=>{Y(c,!1)},b),a.j.start()):Y(c,!1)}function Z(a,b){b.s||(a.u[B(b.m,5,1)]=Date.now(),C(b.m,9)&&(a.B.push(b),sb(a)))};window.googqscp=new class{constructor(){this.i=[];this.j=this.g=null;this.B=[];this.data=null;this.A=[];this.h=[];this.o=[];this.u={};this.H=[];this.l=null}init(a){cb([a]);this.data=new va(a);a=qa(this.data);r(sa(a),e=>{this.o.push({C:0,s:!1,D:0,m:e,v:-1})});this.h=$a();let b=!1;a=this.h.length;for(let e=0;e<a;++e){var c=new ra(JSON.parse(this.h[e].getAttribute("data-ifc")||"[]"));r(sa(c),h=>{this.o.push({C:0,s:!1,D:0,m:h,v:e});1===B(h,4,1)&&(b=!0)})}a=!1;for(var d of this.o)c=d.m,0<B(c,2,0)&&0<B(c, 
5,1)?(!this.g&&C(c,9)&&(this.g=pb(this,nb)),qb(this,d)):B(c,1,"")&&C(c,9)&&rb(this,B(c,1,"")),B(c,1,"")&&(a=!0);d=[];this.g&&d.push(this.g);!b&&d.push(...this.i);L.body&&bb(d);C(this.data,13)&&Sa(()=>{const e=L.body.querySelectorAll(".amp-fcp, .amp-bcp");for(let g=0;g<e.length;++g){var h=(h=e[g])?M.getComputedStyle(h).getPropertyValue("position"):void 0;"absolute"===h&&Y(e[g],!1)}});I(L,"click",e=>{if(!1===e.isTrusted&&C(this.data,15))e.preventDefault?e.preventDefault():e.returnValue=!1,e.stopImmediatePropagation(), 
Ua();else{var h=-1,g=[];for(const v of this.o){var f=v.v,l=-1!==f;if(!(B(v.m,3,0)<=h||v.s||l&&!1===g[f])){var m=!l||g[f]||this.h[f].contains(e.target);l&&m&&(g[f]=!0);if(f=m)if(f=e,m=v,l=m.m,0<B(l,2,0)&&0<B(l,5,1))f=this.u[B(l,5,1)],f=void 0!==f&&Date.now()<f+B(l,2,0);else if(B(l,1,"")){{l=(0<=m.v?this.h[m.v]:L.body).getBoundingClientRect();var E=Number;var z=(z=L.body)?M.getComputedStyle(z).getPropertyValue("zoom"):void 0;E=E(z||"1");const [tb,ub]=[f.clientX,f.clientY],[T,U,ea,fa]=[tb/E-l.left,ub/ 
E-l.top,l.width,l.height];if(!(0<ea&&0<fa)||isNaN(T)||isNaN(U)||0>T||0>U)f=!1;else{m=ob(B(m.m,1,""));z=!(T>=m.left&&ea-T>m.right&&U>=m.top&&fa-U>m.bottom);if(this.l&&C(this.data,12)&&300>f.timeStamp-this.l.timeStamp){f=this.l.changedTouches[0];const [V,W]=[f.clientX/E-l.left,f.clientY/E-l.top];!isNaN(V)&&!isNaN(W)&&0<=V&&0<=W&&(z=z||!(V>=m.left&&ea-V>m.right&&W>=m.top&&fa-W>m.bottom))}f=z}}}else f=!0;if(f){var w=v;h=B(v.m,3,0)}}}if(w)switch(h=w.m,B(h,4,1)){case 2:case 3:e.preventDefault?e.preventDefault(): 
e.returnValue=!1;g=Date.now();500<g-w.D&&(w.D=g,++w.C);g=w.m;if(B(g,8,0)&&w.C>=B(g,8,0))if(w.s=!0,this.g&&0<B(g,2,0))sb(this);else if(0<this.i.length&&B(g,1,""))for(var ha of this.i)Y(ha,!1);Ua();ha=h.toJSON();for(const v of this.A)v(e,ha)}}},Ma);a&&C(this.data,12)&&I(L,"touchend",e=>{this.l=e},Na)}registerCallback(a){this.A.push(a)}};}).call(this);
