(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';const f=Symbol(void 0);var g=Object,h=g.freeze;var k=[];Array.isArray(k)&&!Object.isFrozen(k)&&(f?k[f]|=1:void 0!==k.g?k.g|=1:Object.defineProperties(k,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));h.call(g,k);/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function l(a,b,d){a.addEventListener&&a.addEventListener(b,d,!1)};function m(a,b,d){if(Array.isArray(b))for(var c=0;c<b.length;c++)m(a,String(b[c]),d);else null!=b&&d.push(a+(""===b?"":"="+encodeURIComponent(String(b))))};function n(a){a=void 0===a?document:a;var b="IMG";let d;"application/xhtml+xml"===(null==(d=a)?void 0:d.contentType)&&(b=b.toLowerCase());return a.createElement(b)};function p(a,b,d=null){q(a,b,d)}function q(a,b,d){a.google_image_requests||(a.google_image_requests=[]);const c=n(a.document);if(d){const e=B=>{d&&d(B);c.removeEventListener&&c.removeEventListener("load",e,!1);c.removeEventListener&&c.removeEventListener("error",e,!1)};l(c,"load",e);l(c,"error",e)}c.src=b;a.google_image_requests.push(c)};function r(a=null){return a&&"22"===a.getAttribute("data-jc")?a:document.querySelector('[data-jc="22"]')};var t=document,u=window;function v(a){return"undefined"!==typeof a}function w(a){l(t,a.i,()=>{if(t[a.h])a.g&&(a.g=!1,a.j=Date.now(),x(a,0));else{if(-1!==a.j){const b=Date.now()-a.j;0<b&&(a.j=-1,x(a,1,b))}x(a,3)}})}function y(a){l(u,"click",b=>{a.handleClick(b)})} 
function x(a,b,d=0){var c={gqid:a.m,qqid:a.o};0===b&&(c["return"]=0);1===b&&(c["return"]=1,c.timeDelta=d);2===b&&(c.bgload=1);3===b&&(c.fg=1);b=[];for(var e in c)m(e,c[e],b);p(u,a.l+"&label=window_focus&"+b.join("&"),void 0);if(!(.01<Math.random())){a=r(document.currentScript);a=`https://${"pagead2.googlesyndication.com"}/pagead/gen_204?id=jca&jc=${22}&version=${a&&a.getAttribute("data-jc-version")||"unknown"}&sample=${.01}`;c=window;if(e=c.navigator)e=c.navigator.userAgent,e=/Chrome/.test(e)&&!/Edge/.test(e)? 
!0:!1;e&&c.navigator.sendBeacon?c.navigator.sendBeacon(a):p(c,a)}} 
var A=class{constructor(){var a=z["gws-id"],b=z["qem-id"];this.l=z.url;this.m=a;this.o=b;this.g=!1;a=v(t.hidden)?{h:"hidden",i:"visibilitychange"}:v(t.mozHidden)?{h:"mozHidden",i:"mozvisibilitychange"}:v(t.msHidden)?{h:"msHidden",i:"msvisibilitychange"}:v(t.webkitHidden)?{h:"webkitHidden",i:"webkitvisibilitychange"}:{h:"hidden",i:"visibilitychange"};this.h=a.h;this.i=a.i;this.j=-1;t[this.h]&&x(this,2);w(this);y(this)}handleClick(){this.g=!0;u.setTimeout(()=>{this.g=!1},5E3)}};const C=r(document.currentScript);if(null==C)throw Error("JSC not found 22");var z;const D={},E=C.attributes;for(let a=E.length-1;0<=a;a--){const b=E[a].name;0===b.indexOf("data-jcp-")&&(D[b.substring(9)]=E[a].value)}z=D;window.window_focus_for_click=new A;}).call(this);
