(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var m=this||self;function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}} 
function n(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?n=aa:n=ba;return n.apply(null,arguments)};function ca(a,b){Array.prototype.forEach.call(a,b,void 0)};(class{constructor(a,b){this.g=b===da?a:""}}).prototype.toString=function(){return this.g.toString()};var da={};function p(a){p[" "](a);return a}p[" "]=function(){};var ia="function"===typeof Uint8Array;const ja=Symbol("IS_REPEATED_FIELD");function r(){var a=[];Array.isArray(a)&&!Object.isFrozen(a)&&(a[ja]=!0);return a};function ka(){}let t;const la=Object.freeze(r());function v(a,b){if(b<a.m){b+=a.l;var c=a.g[b];return c!==la?c:a.g[b]=r()}if(a.i)return c=a.i[b],c!==la?c:a.i[b]=r()}function w(a,b,c){a=v(a,b);return null==a?c:a}function x(a,b){return w(a,b,"")}function B(a,b){a=v(a,b);a=null==a?a:!!a;return null==a?!1:a}function ma(a){a=v(a,13);a=null==a?a:+a;return null==a?0:a} 
function E(a){if(a.j)for(var b in a.j){var c=a.j[b];if(Array.isArray(c))for(var d=0;d<c.length;d++)c[d]&&E(c[d]);else c&&E(c)}return a.g}function na(a){var b=oa;t=a=a?JSON.parse(a):null;b=new b(a);t=null;return b}ka.prototype.toString=function(){return E(this).toString()};var oa=class extends ka{constructor(a){super();this.j=null;t&&(a||(a=t),t=null);var b=this.constructor.messageId;a||(a=b?[b]:[]);this.l=b?0:-1;this.g=a;a:{if(a=this.g.length)if(--a,b=this.g[a],!(null===b||"object"!=typeof b||Array.isArray(b)||ia&&b instanceof Uint8Array)){this.m=a-this.l;this.i=b;break a}this.m=Number.MAX_VALUE}}};function pa(a=window){return a};var qa=document,F=window;class ra{constructor(a,b){this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta={}}};function G(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)}function H(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};var sa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function I(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{p(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}}function ta(a,b){if(a)for(const c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)}let J=[];const K=()=>{const a=J;J=[];for(const b of a)try{b()}catch(c){}}; 
var ua=(a,b)=>{"complete"===a.readyState||"interactive"===a.readyState?(J.push(b),1==J.length&&(window.Promise?Promise.resolve().then(K):window.setImmediate?setImmediate(K):setTimeout(K,0))):a.addEventListener("DOMContentLoaded",b)};function L(a,b,c=null){va(a,b,c)}function va(a,b,c){a.google_image_requests||(a.google_image_requests=[]);const d=a.document.createElement("img");if(c){const e=f=>{c&&c(f);H(d,"load",e);H(d,"error",e)};G(d,"load",e);G(d,"error",e)}d.src=b;a.google_image_requests.push(d)};let wa=0;function xa(a){return(a=ya(a,document.currentScript))&&a.getAttribute("data-jc-version")||"unknown"}function ya(a,b=null){return b&&b.getAttribute("data-jc")===String(a)?b:document.querySelector(`[${"data-jc"}="${a}"]`)} 
function za(){if(!(.01<Math.random())){var a=`https://${"pagead2.googlesyndication.com"}/pagead/gen_204?id=jca&jc=${24}&version=${xa(24)}&sample=${.01}`,b=window,c;if(c=b.navigator)c=b.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&b.navigator.sendBeacon?b.navigator.sendBeacon(a):L(b,a)}};var Aa=a=>a.innerHeight>=a.innerWidth?0:90,Ba=!!window.google_async_iframe_id;let M=Ba&&window.parent||window;const Ca=/^https?:\/\/(\w|-)+\.cdn\.ampproject\.(net|org)(\?|\/|$)/;var Da=class{constructor(a,b){this.g=a;this.i=b}},Ia=class{constructor(a,b){this.url=a;this.R=!!b;this.depth=null}};function O(a,b){const c={};c[a]=b;return[c]}function Ja(a,b,c,d,e){const f=[];ta(a,function(g,k){(g=Ka(g,b,c,d,e))&&f.push(k+"="+g)});return f.join(b)} 
function Ka(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){const f=[];for(let g=0;g<a.length;g++)f.push(Ka(a[g],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(Ja(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}function La(a){let b=1;for(const c in a.i)b=c.length>b?c.length:b;return 3997-b-a.j.length-1} 
function Ma(a,b,c){b=b+"//pagead2.googlesyndication.com"+c;let d=La(a)-c.length;if(0>d)return"";a.g.sort(function(f,g){return f-g});c=null;let e="";for(let f=0;f<a.g.length;f++){const g=a.g[f],k=a.i[g];for(let l=0;l<k.length;l++){if(!d){c=null==c?g:c;break}let h=Ja(k[l],a.j,",$");if(h){h=e+h;if(d>=h.length){d-=h.length;b+=h;e=a.j;break}c=null==c?g:c}}}a="";null!=c&&(a=e+"trn="+c);return b+a}class Na{constructor(){this.j="&";this.i={};this.l=0;this.g=[]}};function P(a,b,c,d,e,f){if((d?a.g:Math.random())<(e||.01))try{let g;c instanceof Na?g=c:(g=new Na,ta(c,(l,h)=>{var q=g,u=q.l++;l=O(h,l);q.g.push(u);q.i[u]=l}));const k=Ma(g,a.i,"/pagead/gen_204?id="+b+"&");k&&("undefined"!==typeof f?L(m,k,f):L(m,k))}catch(g){}}class Oa{constructor(){this.i="http:"===F.location.protocol?"http:":"https:";this.g=Math.random()}};let Q=null;var Pa=()=>{const a=m.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()},Qa=()=>{const a=m.performance;return a&&a.now?a.now():null};class Ra{constructor(a,b){var c=Qa()||Pa();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0}};const R=m.performance,Sa=!!(R&&R.mark&&R.measure&&R.clearMarks),S=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=Sa){var b;if(null===Q){Q="";try{a="";try{a=m.top.location.hash}catch(c){a=m.location.hash}a&&(Q=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=Q;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function Ta(a){a&&R&&S()&&(R.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),R.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))} 
class Ua{constructor(){var a=U;this.events=[];this.i=a||m;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.events=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=S()||(null!=b?b:1>Math.random())}start(a,b){if(!this.g)return null;a=new Ra(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;R&&S()&&R.mark(b);return a}end(a){if(this.g&&"number"===typeof a.value){a.duration=(Qa()||Pa())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;R&&S()&&R.mark(b);!this.g|| 
2048<this.events.length||this.events.push(a)}}};function Va(a){let b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;try{-1==a.indexOf(b)&&(a=b+"\n"+a);let c;for(;a!=c;)c=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(c){}}return b} 
function Wa(a,b,c){let d,e;try{a.g&&a.g.g?(e=a.g.start(b.toString(),3),d=c(),a.g.end(e)):d=c()}catch(f){c=!0;try{Ta(e),c=a.m(b,new ra(f,{message:Va(f)}),void 0,void 0)}catch(g){a.J(217,g)}if(c){let g,k;null==(g=window.console)||null==(k=g.error)||k.call(g,f)}else throw f;}return d}function Xa(a,b){var c=V;return(...d)=>Wa(c,a,()=>b.apply(void 0,d))} 
class Ya{constructor(){var a=Za;this.j=W;this.i=null;this.m=this.J;this.g=void 0===a?null:a;this.l=!1}pinger(){return this.j}J(a,b,c,d,e){e=e||"jserror";let f;try{const y=new Na;var g=y;g.g.push(1);g.i[1]=O("context",a);b.error&&b.meta&&b.id||(b=new ra(b,{message:Va(b)}));if(b.msg){g=y;var k=b.msg.substring(0,512);g.g.push(2);g.i[2]=O("msg",k)}var l=b.meta||{};b=l;if(this.i)try{this.i(b)}catch(C){}if(d)try{d(b)}catch(C){}d=y;l=[l];d.g.push(3);d.i[3]=l;d=m;l=[];b=null;do{var h=d;if(I(h)){var q=h.location.href; 
b=h.document&&h.document.referrer||null}else q=b,b=null;l.push(new Ia(q||""));try{d=h.parent}catch(C){d=null}}while(d&&h!=d);for(let C=0,Ea=l.length-1;C<=Ea;++C)l[C].depth=Ea-C;h=m;if(h.location&&h.location.ancestorOrigins&&h.location.ancestorOrigins.length==l.length-1)for(q=1;q<l.length;++q){var u=l[q];u.url||(u.url=h.location.ancestorOrigins[q-1]||"",u.R=!0)}var z=l;let T=new Ia(m.location.href,!1);h=null;const ea=z.length-1;for(u=ea;0<=u;--u){var A=z[u];!h&&Ca.test(A.url)&&(h=A);if(A.url&&!A.R){T= 
A;break}}A=null;const pb=z.length&&z[ea].url;0!=T.depth&&pb&&(A=z[ea]);f=new Da(T,A);if(f.i){z=y;var D=f.i.url||"";z.g.push(4);z.i[4]=O("top",D)}var fa={url:f.g.url||""};if(f.g.url){var ha=f.g.url.match(sa),N=ha[1],Fa=ha[3],Ga=ha[4];D="";N&&(D+=N+":");Fa&&(D+="//",D+=Fa,Ga&&(D+=":"+Ga));var Ha=D}else Ha="";N=y;fa=[fa,{url:Ha}];N.g.push(5);N.i[5]=fa;P(this.j,e,y,this.l,c)}catch(y){try{P(this.j,e,{context:"ecmserr",rctx:a,msg:Va(y),url:f&&f.g.url},this.l,c)}catch(T){}}return!0}};let W,V;if(Ba&&!I(M)){let a="."+qa.domain;try{for(;2<a.split(".").length&&!I(M);)qa.domain=a=a.substr(a.indexOf(".")+1),M=window.parent}catch(b){}I(M)||(M=window)}const U=M,Za=new Ua;var $a=()=>{if(!U.google_measure_js_timing){var a=Za;a.g=!1;a.events!=a.i.google_js_reporting_queue&&(S()&&ca(a.events,Ta),a.events.length=0)}};W=new Oa;"number"!==typeof U.google_srt&&(U.google_srt=Math.random());var ab=W,bb=U.google_srt;0<=bb&&1>=bb&&(ab.g=bb);V=new Ya; 
V.i=a=>{const b=wa;0!==b&&(a.jc=String(b),a.shv=xa(b))};V.l=!0;"complete"==U.document.readyState?$a():Za.g&&G(U,"load",()=>{$a()});var X=(a,b)=>Xa(a,b);function Y(a,b,c={}){c.msg_type=b;c.googMsgType="sth";b=JSON.stringify(c);a.parent.postMessage(b,"*")}function cb(a){if(a.C||B(a.i,2))return!0;let b=!0;const c=db(a);c&&(b=36E5<=c);if(b)try{a.g.localStorage.removeItem("LAST_INTERSTITIAL_TIME")}catch(d){}return b}function Z(a,b,c){x(a.i,3)&&(b.qid=x(a.i,3));x(a.i,10)&&(b.eid=x(a.i,10));b.req=F.location.href;P(W,a.L(),b,!0,c,void 0)} 
function db(a){try{const b=+a.g.localStorage.getItem("LAST_INTERSTITIAL_TIME"),c=Date.now();if(b&&b<c)return c-b}catch(b){}return null} 
class eb{constructor(a,b){this.g=F;this.l=a;this.o=!1;this.u=null;this.m=0;this.i=b;this.C=B(this.i,11)||10===w(this.i,12,0)||11===w(this.i,12,0)}L(){}F(){if(this.o=cb(this))if(this.G(),x(this.i,1)){var a=x(this.i,1);this.g.parent.postMessage(a,"*")}}s(){if(!this.m){this.u&&H(this.g,"storage",this.u);var a=this.m=Date.now();if(!B(this.i,2)&&!this.C)try{this.g.localStorage.setItem("LAST_INTERSTITIAL_TIME",""+a)}catch(b){}this.P();this.l&&(a=this.g.document.createEvent("Event"),a.initEvent("i-creative-view", 
!0,!1),this.l.dispatchEvent(a),a=this.g.document.createEvent("Event"),a.initEvent("onshow",!0,!1),this.g.dispatchEvent(a))}}G(){this.g.IntersectionObserver&&.01<ma(this.i)?(new this.g.IntersectionObserver((a,b)=>{a.forEach(c=>{if(!(0>=c.intersectionRatio)){this.s();for(const d of this.l.document.getElementsByClassName("GoogleActiveViewElement"))d.removeAttribute("data-google-av-dm");b.disconnect()}})},{threshold:ma(this.i)})).observe(this.g.document.documentElement):G(this.g,"message",X(262,a=>{a:{if(a&& 
(this.g.parent==a.source||this.g.parent.parent==a.source)){var b={};try{b=this.g.JSON.parse(a.data)}catch(c){a=void 0;break a}"i-view"==(b&&b.msg_type)&&this.o&&this.s()}a=void 0}return a}));this.C||(this.u=X(263,()=>{this.o=cb(this);if(!this.o){var a={["i_tslv"]:db(this)};Y(this.g,"i-no",a)}}),G(this.g,"storage",this.u));Y(this.g,"i-adframe-load")}P(a){let b;try{const c=pa(this.l);c.vv?c.vv():b=!0}catch(c){V.J(533,c,void 0,void 0);return}a=a||1;b?(Z(this,{vf:a}),3<=a||this.g.setTimeout(n(eb.prototype.P, 
this,a+1),3E3)):1<a&&Z(this,{vs:a})}};function fb(a){window.parent.postMessage(JSON.stringify({type:"rewarded",message:a}),"*")};var gb=a=>{a=a.document;let b={};a&&(b="CSS1Compat"==a.compatMode?a.documentElement:a.body);return b||{}};function hb(a,b,c){a={context:"iaf::itf",req:F.location.href,db:a?1:0,ls:b?1:0,eid:x(c,10),qid:x(c,3),rtype:w(c,12,0)};P(W,"jserror",a,!0,void 0,void 0)}function ib(a,b){jb(a,b)&&(a.j.style.background="rgba(255,255,255, .8)",b=x(a.i,21),""!==b&&(a.j.style.background=b),m.setTimeout(()=>{a.j.style.background="transparent";a.dismiss(2)},750))} 
function kb(a,b){let c;b.some(d=>"intervention"===d.type&&"HeavyAdIntervention"===(null==(c=d.body)?void 0:c.id))&&(Z(a,{hai:"1"},1),a.m?a.dismiss(8):Y(a.g,"i_iif"))}function lb(a){var b=a.j.getBoundingClientRect(),c=b.bottom,d=b.right;const e=gb(a.g).clientHeight,f=gb(a.g).clientWidth,g=Math.floor(c-e),k=Math.floor(d-f);if(0<=g||5<k)c-=b.top,d-=b.left,b=a.g,Z(a,{dhb:g>=c?1:0,dhr:k>=d?1:0,h:e,w:f,bh:c,bw:d,opb:g,opr:k,pt:b.innerHeight>=b.innerWidth?1:0,req:a.g.location.href})} 
function mb(a){const b=X(259,n(function(){Y(this.g,"i-blur");H(this.g,"blur",b)},a));G(a.g,"blur",b)}function nb(a,b){var c={};B(a.i,15)?(fb("canceled"),fb("closed")):Y(a.g,b,c)}function ob(a,b){const c=a.g.document.getElementById("creative");a.g.goog_vignette_survey&&(a.g.goog_vignette_survey.display(c,()=>{a.dismiss(3)},()=>{},1),b&&b.stopPropagation())} 
function qb(a){!1===a.A&&a.enableDismissListeners();a.O&&G(a.O,"click",X(261,c=>ob(a,c)));var b=a.g.document.getElementById("card");b&&B(a.i,20)&&b.addEventListener("click",X(909,c=>{null==c||c.stopPropagation()}));(b=a.g.document.getElementById("abgc"))&&G(b,"click",X(830,c=>{c&&c.stopPropagation()}))}function rb(a){G(a.g,"resize",()=>{const b=Aa(a.g);a.D?(a.D=!1,a.I=90===b):(a.I?0===b:90===b)&&a.dismiss(4)})} 
function sb(a){var b=X(617,c=>{var d=a.j,e=document.activeElement;2==w(a.i,5,0)&&(e=a.l.document.activeElement);(27===c.which||13===c.which&&e===d)&&a.dismiss(5);if(9===c.which){d=tb(a);e=Array.prototype.indexOf.call(d,e,void 0);d=ub.length;const f=tb(a);c.shiftKey&&0===e?(c.preventDefault(),f[d-1].focus()):c.shiftKey||e!==d-1||(c.preventDefault(),f[0].focus())}});G(a.g,"keydown",b);2===w(a.i,5,0)&&G(a.l,"keydown",b);b=tb(a).filter((c,d)=>{c||Z(a,{missingFocusableChild:1,index:d});return!!c});ca(b, 
(c,d)=>{c.setAttribute("tabindex",d+1)});b.length&&b[0].focus()}function tb(a){return 2===w(a.i,5,0)?vb.map(b=>a.l.document.getElementById(b)):ub.map(b=>document.getElementById(b))}function jb(a,b){if(!b)return!0;if((b.preventDefault?b.defaultPrevented:!1===b.returnValue)||b.target&&b.target.ownerDocument==a.l.document)return!1;for(a=b.target;a;){if("creative"==a.id)return!1;a=a.parentElement}return!0} 
class wb extends eb{constructor(a,b,c,d){super(a,d);this.j=b;this.O=c;this.K=0;this.N=X(260,e=>{this.dismiss(1);e&&e.stopPropagation()});this.M=e=>ib(this,e);this.H=[];this.B=[];this.D=this.I=this.A=!1;this.v=null}F(){super.F();(this.v=this.g.ReportingObserver?new this.g.ReportingObserver((a,b)=>{kb(this,a)&&b.disconnect()},{buffered:!0}):null)&&G(this.g,"unload",()=>{kb(this,this.v.takeRecords());this.v.disconnect()})}L(){return"ia_evt"}addViewListener(a){a=Xa(483,a);this.m?a():this.H.push(a)}addDismissListener(a){this.B.push(Xa(484, 
a))}disableDismissListeners(){this.A=!0;H(this.j,"click",this.N);H(this.g.document,"click",this.M)}enableDismissListeners(){this.A=!1;G(this.j,"click",this.N);G(this.g.document,"click",this.M)}dismiss(a){document.body.setAttribute("aria-hidden","true");Z(this,{ttd:Date.now()-this.m,req:F.location.href,pda:this.K,ds:a});this.K++||mb(this);let b=0;for(let d=0;d<this.B.length;d++)b=Math.max(b,this.B[d]());b=Math.min(b,1E3);let c="i-dismiss";6===a?c="r-dismiss-before-reward":7===a&&(c="r-dismiss-after-reward"); 
0===b?nb(this,c):m.setTimeout(()=>nb(this,c),b)}G(){super.G();B(this.i,18)&&qb(this)}s(){super.s();this.I=90===Aa(this.g);this.D=0===this.g.innerWidth&&0===this.g.innerHeight;this.j.setAttribute("aria-label",x(this.i,7));B(this.i,18)||qb(this);rb(this);Wa(V,772,()=>sb(this));lb(this);for(let a=0;a<this.H.length;a++)this.H[a]();za()}}var ub=["dismiss-button","creative"],vb=["dismiss-button","creative-content"];wa=24;const xb=ya(24,document.currentScript);if(null==xb)throw Error("JSC not found 24");const yb={},zb=xb.attributes;for(let a=zb.length-1;0<=a;a--){const b=zb[a].name;0===b.indexOf("data-jcp-")&&(yb[b.substring(9)]=zb[a].value)} 
(function(a){const b=na(a.config);a=X(258,()=>{{var c=document.getElementById("ad_iframe").contentWindow;var d=F.document;const e=c.document,f=w(b,5,0),g=0===f||2===f?e.getElementById(x(b,6)):d.getElementById(x(b,6));d=0===f?e.getElementById(x(b,8)):d.getElementById(x(b,8));let k;try{k=!!F.localStorage}catch(l){}g?(k||hb(g,k,b),c=new wb(c,g,d,b),c.F()):(hb(g,k,b),Y(F,"i_iif"),c=null)}return window.interstitialAdFrame=c});if(0===w(b,5,0)||2===w(b,5,0)||B(b,16)){const c=document.getElementById("ad_iframe"); 
null!=c.contentDocument?ua(c.contentDocument,a):document.getElementById("ad_iframe").addEventListener("load",a)}else a()})(yb);}).call(this);
